import test from 'node:test';
import assert from 'node:assert/strict';
import {Match} from '../src/match.js';
import {defaults} from '../src/settings.js';
import {STAT_FIELDS,defaultSquads,cleanProfile} from '../src/squads.js';
import {displayValue,engineValue,ratingRange,overallRating,ratingSummary} from '../src/player-ratings.js';
import {collectionMovement,activePass,interceptPoint} from '../src/ball-assistance.js';
import {keeperContact} from '../src/keeper-balance.js';
import {keeperProfile} from '../src/attributes.js';
import {DuelMatch} from '../src/duel.js';
import {updateTeamAI} from '../src/ai.js';
const idle={axis:{x:0,z:0}};
function setup(team=0){const m=new Match({...defaults,userTeam:team,seed:739});m.start(true);m.state='playing';m.lock=0;m.aiClock=1e6;m.time=10;const p=m.controlled;p.x=-20*m.direction(team);p.z=0;p.vx=p.vz=0;p.cooldown=p.touchCooldown=0;p.target={x:p.x,z:p.z};m.physics.reset(p.x+m.direction(team)*.54,-m.direction(team)*.11);return {m,p};}
const advance=(m,t,input=idle)=>{for(let i=0;i<t*120;i++)m.step(1/120,input);};

test('all default ratings and physical sizes display as bounded integers',()=>{for(const p of defaultSquads().players){for(const key of Object.keys(STAT_FIELDS)){const value=displayValue(key,p[key]);assert.ok(Number.isInteger(value)&&value>=0&&value<=100);assert.equal(ratingRange(key)[2],1);}assert.ok(displayValue('height',p.height)>=155);assert.ok(overallRating(p)>=0&&overallRating(p)<=100);assert.equal(ratingSummary(p).length,6);}});
test('legacy minimum and maximum attributes remain valid in the integer editor',()=>{for(const [key,[,lo,hi]]of Object.entries(STAT_FIELDS)){const [min,max]=ratingRange(key);for(const v of [lo,hi])assert.ok(displayValue(key,v)>=min&&displayValue(key,v)<=max);}});
test('edited ratings convert to actual simulation attributes without being capped to one',()=>{const p=cleanProfile({passing:engineValue('passing',95),shooting:engineValue('shooting',70),pace:engineValue('pace',90),acceleration:engineValue('acceleration',75),reach:engineValue('reach',85),height:engineValue('height',180),build:engineValue('build',105)});assert.equal(p.passing,.95);assert.equal(p.shooting,.7);assert.equal(p.pace,9);assert.equal(p.acceleration,15);assert.equal(displayValue('reach',p.reach),85);assert.equal(p.height,1.8);assert.equal(p.build,1.05);});
test('role-weighted overall reacts to skills relevant to each position',()=>{for(const [role,key]of [['FWD','shooting'],['MID','passing'],['DEF','tackling'],['GK','reflexes']]){const weak=cleanProfile({role,[key]:.2}),strong={...weak,[key]:1};assert.ok(overallRating(strong)>overallRating(weak));}});
test('neutral controlled players collect an unowned ball without manual movement',()=>{for(const team of [0,1]){const {m,p}=setup(team);m.owner=null;m.physics.reset(p.x+5*m.direction(team),3);advance(m,2.5);assert.equal(m.owner,p);}});
test('loose-ball assistance can be disabled and never overrides a directional input',()=>{const {m,p}=setup();m.owner=null;m.physics.reset(p.x+5,0);m.settings.looseBallAssist=false;advance(m,.5);assert.equal(p.vx,0);m.settings.looseBallAssist=true;advance(m,.25,{axis:{x:-1,z:0}});assert.ok(p.vx<0);});
test('pass receivers begin meeting a pass beyond the previous eight-metre limit',()=>{const {m,p}=setup();m.owner=null;m.physics.reset(p.x-18,0);m.physics.ball.velocity.set(15,0,0);m.receiving={player:p,expires:15};const move=collectionMovement(m,p,idle.axis,idle);assert.ok(move&&move.axis.x<0);assert.ok(interceptPoint(m,p).x>m.physics.ball.position.x);m.settings.receiveAssist=false;assert.equal(collectionMovement(m,p,idle.axis,idle),null);});
test('assisted ground passes reach moving receivers in either attack direction',()=>{for(const team of [0,1])for(const span of [15,28,35]){const {m,p}=setup(team),dir=m.direction(team),q=m.players[team*11+6];Object.assign(q,{active:true,x:p.x+dir*span,z:4,vz:2.5,cooldown:0,touchCooldown:0});q.target={x:q.x,z:q.z};m.input={axis:{x:dir,z:0}};assert.ok(m.queueKick(p,'pass',.5));advance(m,4.5);assert.equal(m.owner,q,`${team}, ${span}m`);assert.equal(m.controlled,q);}});
test('assistance excludes opponents in possession, high balls and offside collectors',()=>{const {m,p}=setup();m.owner=null;m.physics.reset(p.x+3,0,50);assert.equal(collectionMovement(m,p,idle.axis,idle),null);m.physics.reset(p.x+3,0);m.offside.add(p.id);assert.equal(collectionMovement(m,p,idle.axis,idle),null);m.offside.clear();m.owner=m.players[11];assert.equal(collectionMovement(m,p,idle.axis,idle),null);});
test('pass tracking expires and is invalidated by an interception',()=>{const {m,p}=setup();m.owner=null;m.lastTouch=p;m.passFlight={receiver:6,kicker:p.id,team:0,expires:12};assert.ok(activePass(m));m.lastTouch=m.players[12];assert.equal(activePass(m),null);m.lastTouch=p;m.time=12;assert.equal(activePass(m),null);});
function keeperSetup(){const {m}=setup(),g=m.players[11];Object.assign(g,{active:true,x:49,z:0,vx:0,vz:0,dive:0,cooldown:0,touchCooldown:0});m.owner=null;m.lastTouch=m.players[9];m.lastTouchTeam=0;m.lastKickTime=m.time;m.physics.reset(48.7,0,.7);m.physics.ball.velocity.set(12,0,0);return {m,g};}
test('keepers cannot catch an opponent shot before their reaction delay',()=>{const {m,g}=keeperSetup();assert.equal(keeperContact(m,g),null);m.time+=keeperProfile(g).reaction+.01;assert.ok(keeperContact(m,g));});
test('keepers cannot save behind themselves or on the opposite side of a dive',()=>{const {m,g}=keeperSetup();m.time+=1;m.physics.ball.position.x=49.4;assert.equal(keeperContact(m,g),null);m.physics.ball.position.x=48.8;m.physics.ball.position.z=-.4;g.dive=.2;g.diveDuration=.5;g.diveDirection=1;g.diveHeight=.7;assert.equal(keeperContact(m,g),null);m.physics.ball.position.z=.4;assert.ok(keeperContact(m,g));});
test('powerful reachable shots are parried and high reflexes still reduce reaction delay',()=>{const {m,g}=keeperSetup();m.time+=1;m.physics.ball.velocity.set(28,0,0);assert.equal(keeperContact(m,g).catchable,false);assert.ok(keeperProfile({...g,reflexes:.95}).reaction<keeperProfile({...g,reflexes:.3}).reaction);});
test('neutral assisted finishing aims at an open side instead of the central keeper',()=>{const {m,p}=setup();p.x=38;m.physics.reset(38.54,-.11);m.players[11].active=true;m.players[11].x=50;m.players[11].z=0;m.input=idle;assert.ok(m.queueKick(p,'shoot',.6));assert.ok(Math.abs(p.action.target.z)>2);});
test('online teams use their own loose-ball preference when assigning AI collectors',()=>{const m=new DuelMatch();m.start();m.state='playing';m.owner=null;m.physics.reset(0,0);for(const p of m.players){p.x=30;p.z=25;p.action=null;p.down=0;}const human=m.selected(1),helper=m.players[17];human.x=1;human.z=0;helper.x=5;helper.z=0;m.setInput(0,idle,'basic',{looseBallAssist:true});m.setInput(1,idle,'basic',{looseBallAssist:false});updateTeamAI(m);assert.equal(helper.aiState,'PRESS');m.setInput(1,idle,'basic',{looseBallAssist:true});updateTeamAI(m);assert.equal(helper.aiState,'COVER');});
