import test from 'node:test';
import assert from 'node:assert/strict';
import {Match} from '../src/match.js';
import {defaults} from '../src/settings.js';
import {Input} from '../src/input.js';
import {runTarget} from '../src/control-assist.js';
function rig(){const m=new Match({...defaults});m.start();m.state='playing';m.time=10;m.owner=null;m.manualSwitchUntil=m.controlLockUntil=0;const old=m.controlled,q=m.players[5];old.x=-30;old.z=0;q.x=5;q.z=0;for(const p of m.players)if(p!==old&&p!==q){p.x=-45;p.z=30;}m.physics.reset(5,0,.11);m.lastTouchTeam=1;return {m,old,q};}
test('recommended aerial switching never changes a grounded defensive cursor',()=>{const {m,old}=rig();for(let i=0;i<200;i++){m.time+=.01;m.updateAutoControl();}assert.equal(m.controlled,old);});
test('aerial selection changes once and respects manual selection lock',()=>{const {m,old,q}=rig();m.physics.ball.position.y=2;m.updateAutoControl();assert.equal(m.controlled,q);m.selectControlled(old,'manual');m.updateAutoControl();assert.equal(m.controlled,old);m.time+=.71;m.updateAutoControl();assert.equal(m.controlled,q);});
test('pass recipient remains selected through a brief incidental teammate touch',()=>{const {m,old,q}=rig();m.selectControlled(q,'pass');m.owner=old;old.possessedAt=m.time-.3;m.updateAutoControl();assert.equal(m.controlled,q);m.time+=.9;m.updateAutoControl();assert.equal(m.controlled,old);});
test('no direction carry gives the new player the current input immediately',()=>{const {m,old,q}=rig();m.input={axis:{x:1,z:0}};m.selectControlled(q,'manual');assert.equal(m.carryInput,null);m.input.axis={x:0,z:-1};q.vx=q.vz=0;q.action=null;q.down=0;q.target={x:q.x,z:q.z};m.updatePlayer(q,.1,m.input);assert.ok(q.vz<0);assert.equal(q.vx,0);});
test('semi assistance preserves more requested cross direction than automatic mode',()=>{const {m,old,q}=rig();old.x=0;old.z=0;old.yaw=Math.PI/2;m.controlled=old;m.owner=old;m.physics.reset(.54,-.11);q.x=20;q.z=2;for(const p of m.players)if(p.team!==old.team){p.x=35;p.z=25;}m.input={axis:{x:1,z:.5}};m.settings.crossAssist='auto';m.queueKick(old,'lob');const automatic=old.action.aim.z;old.action=null;m.settings.crossAssist='semi';m.queueKick(old,'lob');assert.ok(old.action.aim.z>automatic);assert.ok(old.action.assistOffset);});
test('keyboard sprint remains full speed while analog gamepad triggers can vary',()=>{const input=new Input({...defaults,analogSprint:true},()=>{},()=>({attack:true}),{target:{addEventListener(){}},getPads:()=>[]});input.enabled=true;input.keyDown('KeyE');input.poll();assert.equal(input.sprintAmount,1);input.keyUp('KeyE');const pad={axes:[0,1],buttons:Array.from({length:10},()=>({pressed:false,value:0}))};pad.buttons[7]={pressed:true,value:.5};input.getPads=()=>[pad];input.poll();assert.equal(input.sprintAmount,.5);input.settings.analogSprint=false;input.poll();assert.equal(input.sprintAmount,1);});
test('run type three avoids a defender occupying the straight running lane',()=>{const {m,old}=rig();old.x=0;old.z=0;const defender=m.players[11];defender.x=13;defender.z=0;const target=runTarget(m,old);assert.ok(Math.abs(target.z)>=4);assert.ok(target.x>old.x);});
