import test from 'node:test';
import assert from 'node:assert/strict';
import {Match} from '../src/match.js';
import {defaults} from '../src/settings.js';
import {createPhysics} from '../src/physics.js';
import {crossFlight,chooseCross} from '../src/crossing.js';
import {setpieceFlight} from '../src/setpiece-styles.js';
import {DuelMatch,matchSnapshot} from '../src/duel.js';
import {secondTouch} from '../src/setpieces.js';
const idle={axis:{x:0,z:0}};
function scene(kind,team=0,half=1){const m=new Match({...defaults,userTeam:team,halfSeconds:120,seed:41});m.start(false);m.state='playing';m.half=half;const d=m.direction(team);m.beginRestart({kind,team,x:d*(kind==='corner'?52:27),z:kind==='corner'?33.5:4,label:kind});m.finishRestart();return m;}
function advance(m,t,input=idle){for(let i=0;i<t*120;i++)m.step(1/120,input);}
test('crosses reach a playable descending height under the real drag and spin model',()=>{for(const distance of [12,25,40])for(const foot of ['left','right'])for(const lowCross of [false,true]){const a={distance,foot,lowCross},f=crossFlight(a,{y:.11}),p=createPhysics();p.reset(0,0,.11);p.kick({x:Math.cos(f.aimOffset),z:Math.sin(f.aimOffset)},f.speed,f.lift,f.curve);let peak=0;const dt=f.flightTime/Math.ceil(f.flightTime*240);for(let i=0;i<Math.ceil(f.flightTime*240);i++){p.step(dt);peak=Math.max(peak,p.ball.position.y);}assert.ok(Math.abs(p.ball.position.x-distance)<.35,`${distance}: range ${p.ball.position.x}`);assert.ok(Math.abs(p.ball.position.z)<.25);assert.ok(Math.abs(p.ball.position.y-(lowCross?.55:1.25))<.2);assert.ok(p.ball.velocity.y<0);if(!lowCross&&distance>=25)assert.ok(peak>2.2);}});
test('cross selection from the wing prioritizes an onside penalty-area attacker',()=>{const m=scene('corner'),p=m.setPiece.taker;const target=chooseCross(m,p,null);assert.ok(target);assert.equal(target.player.role,'FWD');assert.ok(Math.abs(target.z)<15);});
test('free kicks form a four-player wall and retain lawful distances for both teams and halves',()=>{for(const team of [0,1])for(const half of [1,2]){const m=scene('free',team,half),s=m.setPiece,b=m.physics.ball.position;assert.equal(s.wall.length,4);for(const q of m.players.filter(q=>q.active&&q.team!==team))assert.ok(Math.hypot(q.x-b.x,q.z-b.z)>=9.15,q.name);for(const q of m.players.filter(q=>q.active&&q.team===team&&q!==s.taker))for(const id of s.wall)assert.ok(Math.hypot(q.x-m.players[id].x,q.z-m.players[id].z)>=1);}});
test('free kicks and penalties stay stationary while aimed and charged',()=>{for(const kind of ['free','penalty']){const m=scene(kind),before=m.physics.ball.position.clone();m.action('charge');advance(m,.5,{axis:{x:1,z:-1}});assert.equal(m.state,'playing');assert.deepEqual(m.physics.ball.position,before);assert.equal(m.physics.ball.velocity.length(),0);assert.ok(m.setPiece.aimZ>.5);assert.ok(m.setPiece.aimHeight>1.2);assert.equal(m.lastKickTime,-10);}});
test('penalty positions put the keeper on the line and everyone else outside the box and arc',()=>{for(const team of [0,1])for(const half of [1,2]){const m=scene('penalty',team,half),s=m.setPiece,b=m.physics.ball.position,d=m.direction(team),g=m.players.find(p=>p.team!==team&&p.role==='GK');assert.equal(b.x,41.5*d);assert.equal(g.x,52.5*d);for(const q of m.players.filter(q=>q.active&&q!==s.taker&&q!==g)){assert.ok(q.x*d<36);assert.ok(q.x*d<b.x*d);assert.ok(Math.hypot(q.x-b.x,q.z-b.z)>=9.15);}advance(m,.4);assert.equal(g.x,52.5*d);}});
test('a human set piece is not forced after the old eight-second timeout',()=>{const m=scene('free');advance(m,9);assert.ok(m.setPiece);assert.equal(m.stats.passes[0],0);});
test('penalty and free-kick shots release on contact and keep player aim instead of auto-picking a corner',()=>{for(const kind of ['free','penalty']){const m=scene(kind);m.setPiece.aimZ=-1.6;m.setPiece.aimHeight=1;const p=m.setPiece.taker;assert.ok(m.queueKick(p,'shoot',.6));assert.equal(p.action.target.z,-1.6);advance(m,.32);assert.equal(m.setPiece,null);assert.equal(m.lastTouch?.id,p.id);assert.equal(m.lastKickType,'shoot');assert.ok(m.physics.ball.velocity.length()>8);assert.ok(m.lastKickTime>0);}});
test('the keeper and opponents cannot kick or switch away from the taker before a restart',()=>{const m=scene('penalty'),p=m.controlled;const opponent=m.players.find(q=>q.team!==p.team);opponent.x=m.physics.ball.position.x;opponent.z=m.physics.ball.position.z;assert.equal(m.queueKick(opponent,'shoot'),false);m.action('switch');assert.equal(m.controlled,p);});
test('a curled free kick clears wall height on its way to the chosen goal position',()=>{const a={distance:25,power:.55,foot:'right',target:{y:1.15}},f=setpieceFlight('inside',{power:.9},a,{y:.11}),p=createPhysics();p.reset(0,0,.11);p.kick({x:Math.cos(f.aimOffset),z:Math.sin(f.aimOffset)},f.speed,f.lift,f.curve);let wallHeight;for(let i=0;i<Math.ceil(f.flightTime*240);i++){p.step(f.flightTime/Math.ceil(f.flightTime*240));if(wallHeight===undefined&&p.ball.position.x>=9.15)wallHeight=p.ball.position.y;}assert.ok(wallHeight>1.85,`wall height ${wallHeight}`);assert.ok(Math.abs(p.ball.position.y-1.15)<.2);assert.ok(Math.abs(p.ball.position.z)<.25);});
test('restart taker cannot play an untouched rebound twice',()=>{const m=scene('free'),p=m.setPiece.taker;m.setPiece=null;m.restartOrigin={kind:'free',team:p.team,player:p.id};assert.equal(secondTouch(m,p),true);assert.equal(m.restart.kind,'indirect');assert.equal(m.restart.team,1-p.team);});
test('penalties are allowed to be taken at the end of the half',()=>{const m=scene('penalty');m.elapsed=121;advance(m,.5);assert.equal(m.state,'playing');assert.ok(m.setPiece);});
test('both network seats keep independent penalty aiming and serialize the target',()=>{const m=new DuelMatch({halfSeconds:120,seed:1});m.start(false);m.state='playing';m.beginRestart({kind:'penalty',team:1,x:-41.5,z:0,label:'PK'});m.finishRestart();m.setInput(0,{axis:{x:1,z:1}});m.setInput(1,{axis:{x:-1,z:-1}});advance(m,.4);const snap=matchSnapshot(m);assert.ok(snap.setPiece.aimZ>.5);assert.ok(snap.setPiece.aimHeight>1.2);assert.equal(snap.controlled[1],m.setPiece.taker.id);});

test('corner kicks release toward the box from either end without a missed stationary contact',()=>{for(const team of [0,1])for(const half of [1,2]){const m=scene('corner',team,half),p=m.setPiece.taker;assert.ok(m.queueKick(p,'lob',.5));advance(m,.9);assert.equal(m.setPiece,null);assert.equal(m.lastKickType,'lob');assert.ok(m.physics.ball.position.y>1);assert.ok(m.physics.ball.position.z<31);assert.equal(m.offside.size,0);}});
test('a penalty played backwards awards an indirect free kick',()=>{const m=scene('penalty'),p=m.setPiece.taker;assert.ok(m.queueKick(p,'pass',.5,{x:-10,z:0}));advance(m,1);assert.equal(m.state,'restart');assert.equal(m.restart.kind,'indirect');assert.equal(m.restart.team,1);});
test('starting a new game clears a previous wall hold',()=>{const m=scene('free');for(const p of m.players)p.wallHoldUntil=50;m.start(false);assert.ok(m.players.every(p=>!p.wallHoldUntil));});
