import test from 'node:test';
import assert from 'node:assert/strict';
import {Match} from '../src/match.js';
import {defaults} from '../src/settings.js';
import {guidePass} from '../src/guided-pass.js';
import {activePass,collectionMovement} from '../src/ball-assistance.js';
import {DuelMatch} from '../src/duel.js';
import {updateTeamAI} from '../src/ai.js';
import {keeperRelease,throwIn} from '../src/commands.js';
const idle={axis:{x:0,z:0}};
function setup(type='pass',team=0,span=18){const m=new Match({...defaults,userTeam:team,seed:42});m.start(true);m.state='playing';m.aiClock=1e6;m.lock=0;const p=m.controlled,d=m.direction(team),q=m.players[team*11+6];Object.assign(p,{x:-20*d,z:0,yaw:d*Math.PI/2,cooldown:0,touchCooldown:0,target:{x:-20*d,z:0},passing:.2,longPass:.2});Object.assign(q,{active:true,x:p.x+span*d,z:4,vx:0,vz:0,cooldown:0,touchCooldown:0,target:{x:p.x+span*d,z:4}});m.physics.reset(p.x+d*.54,-d*.11);m.owner=p;m.input={axis:{x:d,z:0}};assert.ok(m.queueKick(p,type,.6));return {m,p,q};}
function advance(m,seconds,input=idle){for(let i=0;i<seconds*120;i++)m.step(1/120,input);}
test('every unobstructed short, through and lofted pass reaches a stationary receiver with low passing stats',()=>{for(const team of [0,1])for(const type of ['pass','through','lob'])for(const span of [8,18,32]){const {m,q}=setup(type,team,span),start={x:q.x,z:q.z};let received=false;for(let i=0;i<7*120;i++){m.step(1/120,idle);if(m.owner===q){received=true;break;}}assert.ok(received,`${type} team ${team} span ${span}`);assert.ok(Math.hypot(q.x-start.x,q.z-start.z)<.01,'receiver must not be dragged to the ball');}});
test('ball follows a receiver who changes their running direction after the kick',()=>{for(const type of ['pass','through']){const {m,q}=setup(type,0,28);advance(m,.5);assert.ok(activePass(m)?.follow);let received=false;for(let i=0;i<600;i++){const axis=i<70?{x:0,z:1}:i<150?{x:1,z:-.5}:{x:0,z:0};m.step(1/120,{axis,sprint:true});if(m.owner===q){received=true;break;}}assert.ok(received,type);}});
test('velocity guidance cannot teleport the ball or move the receiver',()=>{const {m,q}=setup();advance(m,.35);const b=m.physics.ball.position.clone(),pos={x:q.x,z:q.z};q.z+=4;const changed={x:q.x,z:q.z};guidePass(m,1/120);assert.deepEqual(m.physics.ball.position,b);assert.deepEqual({x:q.x,z:q.z},changed);assert.equal(collectionMovement(m,q,idle.axis,idle),null);assert.notEqual(pos.z,changed.z);});
test('an opponent on the passing lane can intercept and stops target following',()=>{const {m,p,q}=setup('pass',0,24),enemy=m.players[17];Object.assign(enemy,{active:true,x:p.x+12,z:2,vx:0,vz:0,cooldown:0,touchCooldown:0,target:{x:p.x+12,z:2}});let intercepted=false;for(let i=0;i<600;i++){m.step(1/120,idle);if(m.lastTouch?.team===1){intercepted=true;break;}}assert.ok(intercepted);assert.equal(activePass(m),null);assert.notEqual(m.owner,q);const v=m.physics.ball.velocity.clone();guidePass(m,1/120);assert.deepEqual(m.physics.ball.velocity,v);});
test('unintended teammates do not steal a guided pass from the selected receiver',()=>{const {m,p,q}=setup('pass',0,24),middle=m.players[7];Object.assign(middle,{active:true,x:p.x+12,z:2,cooldown:0,touchCooldown:0,target:{x:p.x+12,z:2}});advance(m,4);assert.equal(m.owner,q);});
test('disabling target following restores the physical pass without random changes to shots',()=>{const {m}=setup();m.settings.passFollow=false;advance(m,.35);assert.equal(activePass(m).follow,false);const v=m.physics.ball.velocity.clone();guidePass(m,1/120);assert.deepEqual(m.physics.ball.velocity,v);m.passFlight=null;assert.equal(guidePass(m,1/120),false);});
test('AI receivers keep their run lane rather than intercepting the ball trajectory',()=>{const {m,q}=setup('through');advance(m,.35);m.autoplay=true;const f=activePass(m);updateTeamAI(m);assert.equal(q.aiState,'THROUGH RUN');assert.deepEqual(q.target,f.runTarget);});
test('online seats sanitize and retain independent target-following preferences',()=>{const m=new DuelMatch();m.setInput(0,idle,'basic',{passFollow:false});m.setInput(1,idle,'basic',{passFollow:true});assert.equal(m.assistanceForTeam(0).passFollow,false);assert.equal(m.assistanceForTeam(1).passFollow,true);});
test('keeper hand passes and throw-ins use the same receiver guidance without dragging the receiver',()=>{for(const kind of ['keeper','throw']){const {m,p,q}=setup('pass',0,18);p.action=null;m.physics.reset(p.x+.4,p.z,kind==='throw'?1.7:1.05);if(kind==='keeper'){m.heldBy=p;keeperRelease(m,'keeperPass');}else{m.setPiece={kind:'throw',taker:p,team:0};throwIn(m,'pass');}assert.ok(m.passFlight.follow);const start={x:q.x,z:q.z};let caught=false;for(let i=0;i<840;i++){m.step(1/120,idle);if(m.owner===q){caught=true;break;}}assert.ok(caught,kind);assert.ok(Math.hypot(q.x-start.x,q.z-start.z)<.01,kind);}});
