import test from 'node:test';
import assert from 'node:assert/strict';
import {Match} from '../src/match.js';
import {defaults} from '../src/settings.js';
import {guidePass} from '../src/guided-pass.js';
import {activePass,collectionMovement} from '../src/ball-assistance.js';
import {DuelMatch} from '../src/duel.js';
import {updateTeamAI} from '../src/ai.js';
import {keeperRelease,throwIn} from '../src/commands.js';
const idle={axis:{x:0,z:0}};
function setup(type='pass',team=0,span=18){const m=new Match({...defaults,userTeam:team,seed:42});m.start(true);m.state='playing';m.aiClock=1e6;m.lock=0;const p=m.controlled,d=m.direction(team),q=m.players[team*11+6];Object.assign(p,{x:-20*d,z:0,yaw:d*Math.PI/2,cooldown:0,touchCooldown:0,target:{x:-20*d,z:0},passing:.2,longPass:.2});Object.assign(q,{active:true,x:p.x+span*d,z:4,vx:0,vz:0,cooldown:0,touchCooldown:0,target:{x:p.x+span*d,z:4}});m.physics.reset(p.x+d*.54,-d*.11);m.owner=p;m.input={axis:{x:d,z:0}};assert.ok(m.queueKick(p,type,.6));return {m,p,q};}
function advance(m,seconds,input=idle){for(let i=0;i<seconds*120;i++)m.step(1/120,input);}
test('every unobstructed short, through and lofted pass is collected by a receiver who moves to meet it',()=>{for(const team of [0,1])for(const type of ['pass','through','lob'])for(const span of [8,18,32]){const {m,q}=setup(type,team,span);let received=false;for(let i=0;i<7*120;i++){m.step(1/120,idle);if(m.owner===q){received=true;break;}}assert.ok(received,`${type} team ${team} span ${span}`);}});
test('a pass is never steered toward a receiver who changes direction after the kick',()=>{for(const type of ['pass','through']){const {m,q}=setup(type,0,28);advance(m,.35);assert.equal(activePass(m)?.follow,false);const v=m.physics.ball.velocity,before=Math.atan2(v.z,v.x);for(let i=0;i<60;i++){m.step(1/120,{axis:{x:0,z:1},sprint:true});if(m.lastTouch!==m.players[9])break;}assert.ok(Math.abs(Math.atan2(v.z,v.x)-before)<1e-6,type);}});
test('the pass tracker never moves the ball or the receiver',()=>{const {m,q}=setup();advance(m,.35);const b=m.physics.ball.position.clone(),v=m.physics.ball.velocity.clone();q.z+=4;const changed={x:q.x,z:q.z};guidePass(m,1/120);assert.deepEqual(m.physics.ball.position,b);assert.deepEqual(m.physics.ball.velocity,v);assert.deepEqual({x:q.x,z:q.z},changed);});
test('an opponent on the passing lane can intercept and stops target following',()=>{const {m,p,q}=setup('pass',0,24),enemy=m.players[17];Object.assign(enemy,{active:true,x:p.x+12,z:2,vx:0,vz:0,cooldown:0,touchCooldown:0,target:{x:p.x+12,z:2}});let intercepted=false;for(let i=0;i<600;i++){m.step(1/120,idle);if(m.lastTouch?.team===1){intercepted=true;break;}}assert.ok(intercepted);assert.equal(activePass(m),null);assert.notEqual(m.owner,q);const v=m.physics.ball.velocity.clone();guidePass(m,1/120);assert.deepEqual(m.physics.ball.velocity,v);});
test('a teammate standing in the pass path plays the ball like any other player',()=>{const {m,p,q}=setup('pass',0,24),middle=m.players[7];Object.assign(middle,{active:true,x:p.x+12,z:2,cooldown:0,touchCooldown:0,target:{x:p.x+12,z:2}});advance(m,4);assert.notEqual(m.lastTouch,p);assert.notEqual(m.owner,q);});
test('disabling target following restores the physical pass without random changes to shots',()=>{const {m}=setup();m.settings.passFollow=false;advance(m,.35);assert.equal(activePass(m).follow,false);const v=m.physics.ball.velocity.clone();guidePass(m,1/120);assert.deepEqual(m.physics.ball.velocity,v);m.passFlight=null;assert.equal(guidePass(m,1/120),false);});
test('AI receivers run to meet the actual ball path',()=>{const {m,q}=setup('through');advance(m,.35);m.autoplay=true;updateTeamAI(m);assert.equal(q.aiState,'MEET PASS');});
test('online seats sanitize and retain independent target-following preferences',()=>{const m=new DuelMatch();m.setInput(0,idle,'basic',{passFollow:false});m.setInput(1,idle,'basic',{passFollow:true});assert.equal(m.assistanceForTeam(0).passFollow,false);assert.equal(m.assistanceForTeam(1).passFollow,true);});
test('keeper hand passes and throw-ins are physical and collected by the receiver',()=>{for(const kind of ['keeper','throw']){const {m,p,q}=setup('pass',0,18);p.action=null;m.physics.reset(p.x+.4,p.z,kind==='throw'?1.7:1.05);if(kind==='keeper'){m.heldBy=p;keeperRelease(m,'keeperPass');}else{m.setPiece={kind:'throw',taker:p,team:0};throwIn(m,'pass');for(let i=0;i<120&&m.setPiece;i++)m.step(1/120,idle);}assert.equal(m.passFlight.follow,false);let caught=false;for(let i=0;i<840;i++){m.step(1/120,idle);if(m.owner===q){caught=true;break;}}assert.ok(caught,kind);}});
