import * as THREE from '../vendor/three.module.js';
import {distantGeometry} from '../src/geometry-lod.js';
import {Online} from '../src/online.js';
import {networkFace} from '../src/face-settings.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {Match} from '../src/match.js';
import {defaults} from '../src/settings.js';
import {Input} from '../src/input.js';
import {prepareReception} from '../src/receive-control.js';
import {cushionFirstTouch} from '../src/assists.js';
import {safeAutoTackle} from '../src/auto-defence.js';
import {sampleMotion} from '../src/motion.js';
import {anatomy} from '../src/anatomy-data.js';
import {sculptedHeadGeometry,sculptPoint} from '../src/sculpted-head.js';
import {cleanFace} from '../src/face-settings.js';
import {proportionsFromLandmarks} from '../src/face-fit.js';
import {CELEBRATIONS} from '../src/celebrations.js';
import {SKILLS,skillAction,skillImpulse} from '../src/skills.js';
import {SETPIECE_STYLES,setpieceFlight} from '../src/setpiece-styles.js';
import {cleanOptions,cleanInput,DuelMatch,matchSnapshot} from '../src/duel.js';
import {netOffset} from '../src/goal-net.js';
import {bodyMetrics} from '../src/body-shape.js';
import {THROW} from '../src/throw-in.js';
import {locomotionCadence} from '../src/motion-planner.js';
// Forward kinematics of a sampled pose: ankle position and foot rotation in unscaled root space.
function footFrame(pose,p,i){const m=bodyMetrics(p),q=a=>new THREE.Quaternion().setFromEuler(new THREE.Euler(a[0],a[1],a[2],'XYZ')),hips=q(pose.hips),ankle=new THREE.Vector3((i?1:-1)*m.hipX,-.075,0).applyQuaternion(hips);ankle.y+=pose.hipY+m.hipOffset;const r1=hips.clone().multiply(q(pose.legs[i].upper));ankle.add(new THREE.Vector3(0,-m.upperLeg,0).applyQuaternion(r1));const knee=ankle.clone(),r2=r1.clone().multiply(q(pose.legs[i].lower));ankle.add(new THREE.Vector3(0,-m.lowerLeg,0).applyQuaternion(r2));return {ankle,knee,rotation:r2.multiply(q(pose.feet[i])),m};}
function setup(){const m=new Match({...defaults,seed:10});m.start(false);m.state='playing';m.aiClock=1e6;m.lock=0;m.time=2;for(const p of m.players){p.active=false;p.action=null;p.cooldown=p.touchCooldown=0;}const p=m.players[9],q=m.players[20];p.active=q.active=true;p.x=p.z=0;p.vx=p.vz=0;p.yaw=Math.PI/2;q.x=5;q.z=0;q.vx=q.vz=0;q.yaw=-Math.PI/2;m.controlled=p;m.owner=q;m.physics.reset(4.5,-.11);return {m,p,q};}
test('D holds automatic defending in both defensive layouts and releases without a shot',()=>{for(const defence of ['basic','tactical']){const events=[],input=new Input({...defaults,defence},(action,options)=>events.push({action,options}),()=>({attack:false}),{target:{addEventListener(){}},getPads:()=>[]});input.enabled=true;input.keyDown('KeyD');assert.equal(input.poll().autoDefend,true);assert.equal(input.charging,false);assert.deepEqual(events.at(-1),{action:'tackle',options:{automatic:true}});input.keyUp('KeyD');assert.equal(input.poll().autoDefend,false);assert.ok(!events.some(x=>x.action==='shoot'));input.keyDown('KeyD');input.clear();assert.equal(input.autoDefend,false);}});
test('D approaches on the goal side, shows a lowered stance and stops on release',()=>{const {m,p}=setup();const before=Math.hypot(p.x-4.5,p.z+.11);for(let i=0;i<90;i++){m.time+=1/120;m.updatePlayer(p,1/120,{axis:{x:0,z:0},autoDefend:true});}assert.ok(Math.hypot(p.x-4.5,p.z+.11)<before-1);assert.ok(p.autoDefending&&p.defending);const pose=sampleMotion({...p,vx:0,vz:0,action:null},0,m.time);assert.equal(pose.state,'jockey');assert.ok(pose.hipY<.87);m.updatePlayer(p,.01,{axis:{x:0,z:0}});assert.equal(p.autoDefending,false);assert.equal(p.defending,false);});
test('automatic defence respects manual retreat and never tackles through the opponent',()=>{const {m,p,q}=setup();m.updatePlayer(p,.1,{axis:{x:-1,z:0},autoDefend:true});assert.ok(p.vx<0);assert.equal(p.action,null);p.x=0;p.yaw=Math.PI/2;q.x=.4;q.z=0;m.physics.reset(.8,0);assert.equal(safeAutoTackle(m,p),false);q.z=1;assert.equal(safeAutoTackle(m,p),true);m.owner=p;assert.equal(safeAutoTackle(m,p),false);});
test('a distant D press does not start a tackle cooldown',()=>{const {m,p}=setup();m.action('tackle',{automatic:true});assert.equal(p.action,null);assert.equal(p.cooldown,0);});
test('both online seats retain their automatic-defence input and pose',()=>{const m=new DuelMatch();m.start(false);m.state='playing';m.owner=null;m.physics.reset(0,0);m.setInput(0,{autoDefend:true});m.setInput(1,{autoDefend:true});m.step(1/120);const s=matchSnapshot(m);for(let t=0;t<2;t++)assert.equal(s.players[s.controlled[t]].autoDefending,true);assert.equal(cleanInput({autoDefend:'true'}).autoDefend,false);});
test('receivers prepare before ownership without rotating against manual input',()=>{const {m,p}=setup();m.owner=null;m.physics.reset(3,0);m.physics.ball.velocity.set(-6,0,0);m.passFlight={receiver:p.id,team:p.team,kicker:6,expires:m.time+3};const yaw=p.yaw;prepareReception(m,p,.1,{axis:{x:0,z:1}});assert.ok(p.receivePrep);assert.equal(m.owner,null);assert.equal(p.yaw,yaw);assert.equal(sampleMotion(p,0,m.time,m.physics.ball.position).state,'receive-prepare');});
test('first touch follows an intentional exit direction and never relocates the ball',()=>{const {m,p}=setup();m.owner=null;m.physics.reset(.5,0);m.physics.ball.velocity.set(-8,0,0);m.input={axis:{x:0,z:1}};const before=m.physics.ball.position.clone();cushionFirstTouch(m,p);assert.deepEqual(m.physics.ball.position,before);assert.ok(m.physics.ball.velocity.z>.5);assert.ok(m.physics.ball.velocity.length()<3);});
test('human body has normalized weights, articulated fingers and a genuinely separate head',()=>{const b=anatomy.body;assert.ok(b.positions.length/3>7000);assert.ok(anatomy.head.positions.length/3>4000);for(let i=0;i<b.skinWeights.length;i+=4){assert.ok(Math.abs(b.skinWeights.slice(i,i+4).reduce((n,x)=>n+x,0)-1)<3e-6);assert.ok(b.skinIndices.slice(i,i+4).every(x=>x>=0&&x<13));}assert.ok(b.indices.every(i=>i<b.positions.length/3));assert.ok([...b.positions,...anatomy.head.positions].every(Number.isFinite));});
test('sculpt changes facial geometry while keeping the lower neck attached',()=>{const shape=cleanFace({shape:{width:1.2,depth:1.25,length:1.15,nose:1.5}}).shape;assert.deepEqual(sculptPoint(.04,-.12,.02,shape),[.04,-.12,.02]);const a=sculptedHeadGeometry(),b=sculptedHeadGeometry({shape});a.computeBoundingBox();b.computeBoundingBox();assert.ok(b.boundingBox.max.x>a.boundingBox.max.x);assert.ok(b.boundingBox.max.z>a.boundingBox.max.z);assert.ok([...b.attributes.normal.array].every(Number.isFinite));a.dispose();b.dispose();assert.throws(()=>proportionsFromLandmarks([],100,100));assert.throws(()=>proportionsFromLandmarks(Array(478).fill({x:0,y:NaN,z:0}),400,400));});
test('all authored celebration sequences have finite poses and survive profile-independent playback',()=>{const signatures=new Set();for(const clip of CELEBRATIONS){const frames=[];for(let t=0;t<5;t+=.05){const p=sampleMotion({id:9,celebration:clip.id,celebrationStart:0},0,t,null,true);assert.equal(p.state,'celebrate');assert.ok(p.hipY>.15&&p.hipY<1);assert.ok(!JSON.stringify(p).includes('null'));frames.push(p.arms,p.legs,p.hips);}signatures.add(JSON.stringify(frames));}assert.equal(CELEBRATIONS.length,42);assert.ok(signatures.size>35);});
test('skills and free-kick styles survive online sanitization without arbitrary options',()=>{for(const skill of Object.keys(SKILLS)){const a=skillAction({yaw:0,foot:'left'},{x:0,z:1},1,skill);assert.equal(cleanOptions({skill}).skill,skill);assert.equal(a.events.length,2);assert.ok(a.events[1].at<a.duration);for(let stage=0;stage<2;stage++){const impulse=skillImpulse({yaw:0},a,stage);assert.ok(Number.isFinite(impulse.speed));assert.ok(Math.hypot(impulse.aim.x,impulse.aim.z)>.1);}}for(const style of Object.keys(SETPIECE_STYLES)){assert.equal(cleanOptions({style}).style,style);const flight=setpieceFlight(style,{power:.8},{power:.6,distance:25,foot:'right'},{y:.11});assert.ok(flight.speed>10&&flight.lift>=0);}assert.deepEqual(cleanOptions({skill:'__proto__',style:'invalid'}),{});});
test('post contact keeps the player capsule outside the frame and removes inward speed',()=>{const {m,p}=setup();p.x=52.1;p.z=3.72;p.vx=5;p.vz=0;m.move(p,{x:1,z:0},true,false,.1);assert.ok(Math.hypot(p.x-52.5,p.z-3.72)>=.3799);assert.ok(p.vx<=0);});
test('net deformation is local and decays to the resting shape',()=>{const hit={y:1,z:0,speed:24};assert.ok(Math.abs(netOffset({y:1,z:0},hit,.1))>Math.abs(netOffset({y:1,z:3},hit,.1)));assert.equal(netOffset({y:1,z:0},hit,2),0);});

test('online transport includes the D hold flag and privacy opt-out removes derived facial shape',()=>{const fake={active:true,buffer:{sample:()=>null},renderConnection(){}};Online.prototype.update.call(fake,{axis:{x:0,z:0},autoDefend:true},0);assert.equal(fake.latestInput.autoDefend,true);const p={skin:'#aa8877',face:{enabled:true,fitted:true,assetId:'private',shape:{jaw:1.3,nose:1.5}}};const off=networkFace(p,null,false),on=networkFace(p,null,true);assert.equal(off.face.fitted,false);assert.equal(off.face.shape.jaw,1);assert.equal(off.skin,'#c89572');assert.equal(on.face.shape.nose,1.5);assert.equal(on.face.assetId,null);});

test('walking, running and sprinting keep the planted heel, ball or flat foot fixed on the pitch',()=>{for(const speed of [1.7,3.4,5.8,8.6]){const p={id:4,x:0,z:0,vx:0,vz:speed,yaw:0},rate=locomotionCadence(speed,undefined,p),dt=1/480,prev=[null,null];let worst=0;for(let k=0;k<480;k++){const t=k*dt,pose=sampleMotion(p,rate*t,t);for(let i=0;i<2;i++){const g=pose.gaitTargets[i],f=footFrame(pose,p,i);if(!g.contact){prev[i]=null;continue;}const pivot=g.pitch>1e-3?1:g.pitch<-1e-3?-1:0,pin=new THREE.Vector3(0,-.075,pivot>0?.12*f.m.foot:pivot<0?-.076*f.m.foot:0).applyQuaternion(f.rotation).add(f.ankle).multiplyScalar(f.m.scale);pin.z+=speed*t;if(prev[i]?.pivot===pivot)worst=Math.max(worst,Math.hypot(pin.x-prev[i].pin.x,pin.z-prev[i].pin.z)/dt);prev[i]={pin,pivot};}}assert.ok(worst<.3,`${speed}m/s planted sole moves ${worst}m/s`);}});
test('defending side and back steps stay low and flat-footed without folding the body',()=>{for(const [vx,vz] of [[3,0],[-2,0],[0,-3],[4,0]])for(let k=0;k<60;k++){const pose=sampleMotion({id:3,x:0,z:0,vx,vz,yaw:0,defending:true},k*.21,k/60);assert.equal(pose.state,'jockey');assert.ok(pose.hipY>.7&&pose.hipY<.84);for(const g of pose.gaitTargets)assert.ok(Math.abs(g.pitch)<1e-9);for(const leg of pose.legs)assert.ok(leg.lower[0]>=0&&leg.lower[0]<=Math.PI);}});
test('inside-foot passes open the kicking foot toward the target and mirror for the left foot',()=>{const toe=(type,foot)=>{const p={id:9,x:0,z:0,vx:0,vz:0,yaw:0,foot,action:{type,foot,elapsed:.16,contactAt:.18,power:.8}},pose=sampleMotion(p,0,0,{x:foot==='left'?-.11:.11,y:.11,z:.5});return new THREE.Vector3(0,0,1).applyQuaternion(footFrame(pose,p,foot==='left'?0:1).rotation);};assert.ok(toe('pass','right').x>.7);assert.ok(toe('pass','left').x<-.7);assert.ok(Math.abs(toe('lob','right').x)<.3);});
test('a due dribble touch puts the touching foot on the ball at any point of the stride',()=>{const ball={x:.1,y:.11,z:.55};for(let phase=0;phase<6.28;phase+=.7){const p={id:7,x:0,z:0,vx:0,vz:3,yaw:0,dribbleAim:{x:0,z:1},nextDribbleTouch:0},pose=sampleMotion(p,phase,1,ball),i=pose.reach.findIndex(Boolean),f=footFrame(pose,p,i),s=f.m.scale;assert.ok(i>=0);assert.equal(pose.planted[i],false);assert.ok(Math.hypot(f.ankle.x*s-ball.x,f.ankle.z*s-ball.z)<.22);assert.ok(f.ankle.y*s<.2);}});
test('first touches meet the arriving ball with the inside of the foot, the instep or the raised thigh',()=>{const base={id:8,x:0,z:0,vx:0,vz:0,yaw:0,foot:'right'},prep=(kind,y,z)=>({...base,receivePrep:{kind,foot:'right',start:0,until:2,eta:.05,weight:1,target:{x:.14,y,z},incoming:{x:0,z:-1}}});
 const inside=prep('inside',.11,.5),a=footFrame(sampleMotion(inside,0,1,{x:.14,y:.11,z:.95}),inside,1),s=a.m.scale,toe=new THREE.Vector3(0,0,1).applyQuaternion(a.rotation);assert.ok(Math.hypot(a.ankle.x*s-.14,a.ankle.z*s-.5)<.25);assert.ok(toe.x>.6);
 const thigh=prep('thigh',1,.35),b=footFrame(sampleMotion(thigh,0,1,{x:.14,y:1.1,z:.8}),thigh,1),standing=footFrame(sampleMotion(base,0,1,null),base,1);assert.ok(b.knee.y-standing.knee.y>.25);});
test('a standing tackle reaches the ball at the moment the rules resolve it and keeps only the support foot planted',()=>{const ball={x:.15,y:.11,z:.6},p={id:5,x:0,z:0,vx:0,vz:0,yaw:0,action:{type:'tackle',elapsed:.13}},pose=sampleMotion(p,0,0,ball),f=footFrame(pose,p,1),s=f.m.scale;assert.ok(Math.hypot(f.ankle.x*s-ball.x,f.ankle.z*s-ball.z)<.2);assert.deepEqual(pose.planted,[true,false]);assert.ok(pose.hipY<.8);const done=sampleMotion({...p,action:{type:'tackle',elapsed:.55}},0,0,ball);assert.ok(done.hipY>.84);});
test('a sliding tackle drops onto the hip with the tackling leg along the grass and stands up again',()=>{const ball={x:.15,y:.11,z:.6},at=t=>{const p={id:5,x:0,z:0,vx:0,vz:0,yaw:0,action:{type:'slide',elapsed:t}};return {pose:sampleMotion(p,0,0,ball),p};},mid=at(.35),f=footFrame(mid.pose,mid.p,1);assert.ok(mid.pose.hipY<.3);assert.ok(f.ankle.z*f.m.scale>.65);assert.ok(f.ankle.y<.2);assert.ok(Math.abs(mid.pose.rootRoll)>.3);assert.ok(at(.85).pose.hipY>.84);});
test('a header jumps, arches back, strikes forward at contact and lands upright',()=>{const at=t=>sampleMotion({id:5,x:0,z:0,vx:0,vz:0,yaw:0,action:{type:'shoot',aerial:true,elapsed:t,contactAt:.19}},0,0,{x:0,y:1.7,z:.4});assert.equal(at(.19).state,'header');assert.ok(at(.19).hipY-at(0).hipY>.25);assert.ok(at(.1).torso[0]<-.15);assert.ok(at(.25).torso[0]>.3);assert.ok(Math.abs(at(.7).torso[0])<.1);assert.equal(at(.19).rootY,0);});
test('a volley swings the kicking foot to the ball height with the support foot planted and stays a volley after the ball leaves',()=>{for(const foot of ['right','left']){const i=foot==='left'?0:1,strike={x:foot==='left'?-.1:.1,y:.9,z:.5},p={id:5,x:0,z:0,vx:0,vz:0,yaw:0,action:{type:'shoot',aerial:true,foot,elapsed:.21,contactAt:.21,contactTarget:strike}},pose=sampleMotion(p,0,0,strike),kick=footFrame(pose,p,i),support=footFrame(pose,p,1-i),s=kick.m.scale;assert.equal(pose.state,'volley');assert.ok(Math.abs(kick.ankle.y*s-.84)<.12);assert.ok(support.ankle.y*s<.12);assert.equal(sampleMotion({...p,action:{...p.action,elapsed:.4}},0,0,{x:0,y:2.2,z:4}).state,'volley');}});
test('a knocked-down player lies low, gets up through hands and knees and ends standing',()=>{const at=down=>sampleMotion({id:5,x:0,z:0,vx:0,vz:0,yaw:0,down},0,0,null);assert.ok(at(.9).hipY<.3);assert.ok(at(.3).hipY>at(.9).hipY&&at(.3).hipY<.6);assert.equal(at(.1).state,'recover');assert.ok(at(.02).hipY>.8);});
test('a throw-in holds the ball overhead on the touchline, throws it after the wind-up and never before',()=>{for(const team of [0,1]){const m=new Match({...defaults,seed:4});m.start(false);m.state='playing';m.aiClock=1e6;m.lock=0;m.beginRestart({kind:'throw',team,x:6,z:-33.7,label:'throw'});let held=false,start=null;for(let i=0;i<1400&&(m.setPiece||start===null);i++){m.step(1/120,{axis:{x:0,z:0}});const s=m.setPiece;if(s?.kind==='throw'&&s.taker){const p=s.taker,b=m.physics.ball.position;if(p.throwHold){held=true;assert.ok(b.y>1.6);assert.ok(Math.abs(p.z)>33.8);assert.ok(Math.abs(b.z)<=34.1);assert.equal(sampleMotion(p,0,m.time,b).state,'throw-hold');}if(team===0&&held&&!p.action&&m.time>8)m.action('pass');if(p.action?.type==='throw'&&start===null)start=m.time;}}assert.ok(held);assert.ok(start!==null);assert.equal(m.setPiece,null);assert.ok(m.time-start>=THROW.release-.02);assert.ok(m.physics.ball.velocity.z>2);assert.equal(m.lastTouchKind,'throw');}});
function crossScene(seed,defender){const m=new Match({...defaults,seed});m.start(false);m.state='playing';m.autoplay=true;m.aiClock=1e6;m.lock=0;m.time=3;for(const q of m.players){q.active=false;q.action=null;}const dir=m.direction(0),p=m.players.find(q=>q.team===0&&q.role==='FWD');p.active=true;p.x=dir*42;p.z=0;p.vx=p.vz=0;p.target={x:p.x,z:0};let q=null;if(defender){q=m.players.find(r=>r.team===1&&r.role==='DEF');q.active=true;q.x=p.x+dir*.45;q.z=.35;q.vx=q.vz=0;q.target={x:q.x,z:q.z};}m.owner=null;m.lastTouchTeam=0;m.physics.reset(p.x,-9,1.5);m.physics.ball.velocity.set(0,3.05,18);return {m,p,q};}
test('a cross at head height is met by a timed jump header toward goal instead of passing overhead',()=>{const {m,p}=crossScene(7,false);let started=null;for(let i=0;i<200&&m.state==='playing';i++){m.step(1/120,{axis:{x:0,z:0}});if(p.action?.header&&!started)started={...p.action};}assert.ok(started);assert.equal(started.type,'shoot');assert.equal(started.clipId,'header');assert.ok(started.contactAt>.08&&started.contactAt<=.27);assert.equal(m.lastTouch,p);assert.equal(m.stats.shots[0],1);});
test('an aerial duel makes both players jump and lets only the winner touch the ball',()=>{for(const seed of [7,8,9]){const {m,p,q}=crossScene(seed,true);const jumped=new Set(),touched=new Set();for(let i=0;i<240&&m.state==='playing';i++){m.step(1/120,{axis:{x:0,z:0}});for(const w of [p,q]){if(w.action?.aerial)jumped.add(w.id);if(w.action?.aerial&&w.action.contactTime)touched.add(w.id);}}assert.equal(jumped.size,2);assert.equal(touched.size,1);}});
test('roulette, la croqueta and rainbow flick play both touches, keep the ball and the rainbow clears head height',()=>{for(const skill of ['roulette','la-croqueta','rainbow-flick']){const m=new Match({...defaults,seed:3});m.start(false);m.state='playing';m.aiClock=1e6;m.lock=0;m.time=3;for(const q of m.players){q.active=false;q.action=null;}const p=m.controlled;p.active=true;p.x=p.z=0;p.vx=0;p.vz=2;p.yaw=0;p.cooldown=p.touchCooldown=0;m.owner=p;p.possessedAt=0;m.physics.reset(0,.4,.11);const input={axis:{x:0,z:1}};m.input=input;m.action('skill',{skill});const a=p.action;assert.equal(a.skill,skill);let top=0;for(let i=0;i<260;i++){m.step(1/120,input);top=Math.max(top,m.physics.ball.position.y);const pose=sampleMotion(p,0,m.time,m.physics.ball.position);assert.ok(!JSON.stringify(pose).includes('null'));}assert.ok(a.events.every(e=>e.done)&&!a.failed,skill);assert.equal(m.owner,p,skill);if(skill==='rainbow-flick')assert.ok(top>1.8);}});
test('distant anatomy preserves normalized joint influences and reduces geometry',()=>{const b=anatomy.body,g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(b.positions,3));g.setAttribute('skinIndex',new THREE.Uint16BufferAttribute(b.skinIndices,4));g.setAttribute('skinWeight',new THREE.Float32BufferAttribute(b.skinWeights,4));g.setIndex(b.indices);const low=distantGeometry(g,.035);assert.ok(low.index.count<g.index.count*.5);assert.ok(low.attributes.position.count>500);for(let i=0;i<low.attributes.skinWeight.count;i++){let sum=0;for(let j=0;j<4;j++){sum+=low.attributes.skinWeight.array[i*4+j];assert.ok(low.attributes.skinIndex.array[i*4+j]<13);}assert.ok(Math.abs(sum-1)<1e-6);}assert.ok([...low.attributes.normal.array].every(Number.isFinite));assert.ok(low.boundingSphere.radius>0);});
