import test from 'node:test';
import assert from 'node:assert/strict';
import {DuelMatch,cleanInput,matchSnapshot} from '../src/duel.js';
import {Room} from '../server/room.js';
import {applyCard} from '../src/referee.js';
import {updateTeamAI} from '../src/ai.js';
import {sampleMotion} from '../src/motion.js';
import {SnapshotBuffer} from '../src/net-state.js';
const advance=(m,s)=>{for(let i=0;i<s*120;i++)m.step(1/120);};
function duel(){const m=new DuelMatch();m.start();m.state='playing';m.aiClock=1e5;for(const p of m.players)p.target={x:p.x,z:p.z};return m;}
test('both humans move independently while AI leaves their commands alone',()=>{const m=duel(),a=m.selected(0),b=m.selected(1);m.owner=null;m.physics.reset(0,25);a.x=-10;a.z=-10;b.x=10;b.z=10;const ax=a.x,bx=b.x;m.setInput(0,{axis:{x:1,z:0},sprint:true});m.setInput(1,{axis:{x:-1,z:0},sprint:true});updateTeamAI(m);assert.equal(a.action,null);assert.equal(b.action,null);advance(m,.5);assert.ok(a.x>ax+.5);assert.ok(b.x<bx-.5);assert.equal(m.settings.userTeam,0);});
test('away player charges and shoots with their own input and selects their receiver',()=>{const m=duel(),b=m.selected(1);b.x=15;b.z=0;b.yaw=-Math.PI/2;b.action=null;m.physics.reset(14.46,.11);m.owner=b;m.setInput(1,{axis:{x:-1,z:0}});m.command(1,'charge',{curve:true});advance(m,.3);assert.ok(m.seats[1].charge>.2);assert.equal(m.seats[0].charge,0);m.command(1,'shoot');advance(m,.7);assert.equal(m.stats.shots[1],1);assert.ok(m.physics.ball.velocity.x<0);assert.equal(m.settings.userTeam,0);});
test('two humans receive separate pass controls and set-piece ownership',()=>{const m=duel(),b=m.selected(1),q=m.players[17];b.x=10;b.z=0;b.yaw=-Math.PI/2;q.x=0;q.z=8;m.owner=b;m.physics.reset(9.46,.11);m.withSeat(1,()=>m.queueKick(b,'pass',.5,{x:-10,z:8},q));advance(m,.7);assert.equal(m.selected(1),q);assert.equal(m.selected(0).team,0);m.state='playing';m.beginRestart({kind:'throw',team:1,x:4,z:33.7,label:'스로인'});advance(m,1.8);assert.equal(m.setPiece.team,1);assert.equal(m.selected(1),m.setPiece.taker);m.command(1,'pass');advance(m,.5);assert.equal(m.setPiece,null);assert.ok(m.physics.ball.velocity.z<0);});
test('sent-off humans are replaced independently and both controls survive halftime',()=>{const m=duel(),p=m.selected(1);applyCard(m,p,'red');m.step(1/120);assert.notEqual(m.selected(1),p);m.half=2;m.kickoff(1);assert.equal(p.active,false);assert.equal(m.selected(0).team,0);assert.equal(m.selected(1).team,1);assert.equal(m.direction(1),1);});
test('input sanitization bounds axes and refuses client-authored world state',()=>{const input=cleanInput({axis:{x:Infinity,z:4},sprint:'true',score:[99,0],position:{x:200},teamPressCount:100});assert.deepEqual(input.axis,{x:0,z:1});assert.equal(input.sprint,false);assert.equal(input.score,undefined);assert.equal(input.teamPressCount,1);});
function roomRig(){let now=10000,id=0;const room=new Room({code:'ABCD2345',now:()=>now,random:()=>`test-token-${++id}`}),a=room.reserve('Host',true),b=room.reserve('Guest');const outputs=[[],[]];const send0=x=>outputs[0].push(JSON.parse(JSON.stringify(x))),send1=x=>outputs[1].push(JSON.parse(JSON.stringify(x)));room.connect(a.token,send0);room.connect(b.token,send1);return {room,a,b,outputs,send0,send1,tick:ms=>{for(let i=0;i<ms;i+=10){now+=10;room.tick();}},now:()=>now};}
test('room seats cap at two, authenticate tokens and require both ready plus host start',()=>{const {room}=roomRig();assert.throws(()=>room.reserve('Intruder'));assert.throws(()=>room.connect('wrong',()=>{}));room.message(0,{type:'start'});assert.equal(room.phase,'lobby');room.message(0,{type:'ready',ready:true});room.message(1,{type:'ready',ready:true});room.message(1,{type:'start'});assert.equal(room.phase,'lobby');room.message(0,{type:'start'});assert.equal(room.phase,'playing');});
test('clients receive identical authoritative ball, score and player positions',()=>{const r=roomRig();for(let t=0;t<2;t++)r.room.message(t,{type:'ready',ready:true});r.room.message(0,{type:'start'});r.tick(1500);for(let t=0;t<2;t++)r.room.message(t,{type:'input',seq:1,input:{axis:{x:t?-1:1,z:0}}});r.tick(300);const snapshots=r.outputs.map(list=>list.filter(x=>x.type==='snapshot').at(-1));assert.deepEqual(snapshots[0],snapshots[1]);assert.ok(snapshots[0].data.players.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.z)));});
test('out-of-order inputs and over-capacity action batches cannot replay a shot',()=>{const r=roomRig();for(let t=0;t<2;t++)r.room.message(t,{type:'ready',ready:true});r.room.message(0,{type:'start'});r.room.match.state='playing';r.room.message(1,{type:'input',seq:7,input:{axis:{x:-1,z:0}}});r.room.message(1,{type:'input',seq:6,input:{axis:{x:1,z:0}}});assert.equal(r.room.match.inputForTeam(1).axis.x,-1);});
test('disconnect pauses the shared simulation and reconnect resumes the same match',()=>{const r=roomRig();for(let t=0;t<2;t++)r.room.message(t,{type:'ready',ready:true});r.room.message(0,{type:'start'});r.tick(1500);r.room.disconnect(1,r.send1);const time=r.room.match.time;r.tick(2000);assert.equal(r.room.match.time,time);r.room.connect(r.b.token,r.send1);r.tick(200);assert.ok(r.room.match.time>time);assert.equal(r.room.phase,'playing');});
test('abandoned room ends after the reconnect deadline',()=>{const r=roomRig();for(let t=0;t<2;t++)r.room.message(t,{type:'ready',ready:true});r.room.message(0,{type:'start'});r.room.disconnect(1,r.send1);for(let i=0;i<46;i++){r.room.message(0,{type:'ping',sent:0});r.tick(1000);}assert.equal(r.room.phase,'closed');assert.equal(r.room.match,null);});
test('stale input releases movement and charge; leaving closes both clients',()=>{const r=roomRig();for(let t=0;t<2;t++)r.room.message(t,{type:'ready',ready:true});r.room.message(0,{type:'start'});r.room.match.state='playing';r.room.message(0,{type:'input',seq:1,input:{axis:{x:1,z:0}},actions:[{action:'charge'}]});r.tick(600);assert.equal(r.room.match.inputForTeam(0).axis.x,0);assert.equal(r.room.match.seats[0].charging,false);r.room.message(0,{type:'leave'});assert.equal(r.room.phase,'closed');assert.ok(r.outputs[1].some(x=>x.type==='ended'));});
test('motion poses stay finite across run, direction change, kick, slide and recovery',()=>{for(const type of [null,'shoot','pass','lob','slide','tackle','feint'])for(let i=0;i<80;i++){const p={x:0,z:0,yaw:1.5,vx:7,vz:2,down:i>65?.2:0,action:type?{type,elapsed:i/120,contactAt:.18,hit:i>22,power:.8}:null};const pose=sampleMotion(p,i*.2,i/30,{x:.5,y:.11,z:0},false,{turn:4,acceleration:12});const nums=JSON.stringify(pose);assert.ok(!nums.includes('null'));assert.ok(pose.hipY>.2&&pose.hipY<1.1);for(const leg of pose.legs)assert.ok(leg.lower[0]>=0&&leg.lower[0]<=Math.PI);}});
test('snapshot interpolation takes the shortest route across the yaw wrap',()=>{const m=duel(),a=matchSnapshot(m),b=JSON.parse(JSON.stringify(a));a.time=0;b.time=.1;a.players[0].yaw=3.12;b.players[0].yaw=-3.12;const buffer=new SnapshotBuffer();buffer.push(a,0);buffer.push(b,100);const s=buffer.sample(115);assert.ok(Math.abs(s.players[0].yaw)>3);});
