import fs from 'node:fs';
import {Vector3,Quaternion} from '../vendor/three.module.js';
const folder='assets-source/makehuman/',lines=fs.readFileSync(folder+'base.obj','utf8').split('\n'),vertices=[],faces=[];let group='';
for(const line of lines){const [kind,...v]=line.trim().split(/\s+/);if(kind==='v')vertices.push(v.map(Number));if(kind==='g')group=v[0];if(kind==='f'&&group==='body')faces.push(v.map(n=>Number(n.split('/')[0])-1));}
for(const [name,w]of [['asian-male-young',1],['universal-male-young-averagemuscle-averageweight',.65],['universal-male-young-maxmuscle-averageweight',.35]])for(const line of fs.readFileSync(folder+name+'.target','utf8').split('\n')){if(!/^\d/.test(line))continue;const [i,...d]=line.trim().split(/\s+/).map(Number);for(let k=0;k<3;k++)vertices[i][k]+=d[k]*w;}
const rig=JSON.parse(fs.readFileSync(folder+'default.mhskel')),rawWeights=JSON.parse(fs.readFileSync(folder+'default_weights.mhw')).weights;
const joint=name=>new Vector3(...rig.joints[name].reduce((a,i)=>a.map((v,k)=>v+vertices[i][k]/rig.joints[name].length),[0,0,0]));
const point=(bone,end='head')=>joint(rig.bones[bone][end]);
const ids=['hips','torso','head','armR','forearmR','armL','forearmL','thighR','shinR','footR','thighL','shinL','footL'];
function boneId(name){const side=name.endsWith('.L')?'L':'R';if(/upperarm|shoulder/.test(name))return ids.indexOf('arm'+side);if(/lowerarm|wrist|finger|metacarpal/.test(name))return ids.indexOf('forearm'+side);if(/upperleg/.test(name))return ids.indexOf('thigh'+side);if(/lowerleg/.test(name))return ids.indexOf('shin'+side);if(/foot|toe/.test(name))return ids.indexOf('foot'+side);if(/root|pelvis|spine05/.test(name))return 0;if(/spine|breast|clavicle|neck/.test(name))return 1;return 2;}
const weights=vertices.map(()=>new Map());for(const [name,values]of Object.entries(rawWeights))for(const [i,w]of values){const id=boneId(name);weights[i].set(id,(weights[i].get(id)||0)+w);}
const transforms={};
function limb(id,source,end,target,length){const start=point(source),direction=point(end,'tail').sub(start),scale=length/direction.length(),q=new Quaternion().setFromUnitVectors(direction.normalize(),new Vector3(0,-1,0));transforms[id]=v=>v.clone().sub(start).applyQuaternion(q).multiplyScalar(scale).add(new Vector3(...target));}
for(const [s,suffix]of [[-1,'R'],[1,'L']]){limb(ids.indexOf('arm'+suffix),'upperarm01.'+suffix,'upperarm02.'+suffix,[s*.222,1.357,0],.255);limb(ids.indexOf('forearm'+suffix),'lowerarm01.'+suffix,'lowerarm02.'+suffix,[s*.222,1.102,0],.24);limb(ids.indexOf('thigh'+suffix),'upperleg01.'+suffix,'upperleg02.'+suffix,[s*.112,.835,0],.35);limb(ids.indexOf('shin'+suffix),'lowerleg01.'+suffix,'lowerleg02.'+suffix,[s*.112,.485,0],.4);const origin=point('foot.'+suffix);transforms[ids.indexOf('foot'+suffix)]=v=>v.clone().sub(origin).multiplyScalar(.1).add(new Vector3(s*.112,.085,0));}
const sourceRoot=point('spine05'),headRoot=point('head');transforms[0]=v=>v.clone().sub(sourceRoot).multiplyScalar(.105).add(new Vector3(0,.91,0));transforms[1]=v=>new Vector3(v.x*.112,.91+(v.y-sourceRoot.y)*.104,(v.z+.12)*.105);transforms[2]=v=>v.clone().sub(headRoot).multiplyScalar(.105).add(new Vector3(0,1.585,.005));
const round=n=>Math.round(n*1e6)/1e6,body={positions:[],indices:[],skinIndices:[],skinWeights:[],regions:[]},head={positions:[],indices:[]};const bodyMap=new Map(),headMap=new Map();
const transformed=vertices.map((v,i)=>{let ws=[...weights[i]].sort((a,b)=>b[1]-a[1]).slice(0,4);if(v[1]>4.9&&Math.abs(v[0])<.9){const t=Math.max(0,Math.min(1,(v[1]-4.9)/.85));ws=[[1,1-t],[2,t]].filter(x=>x[1]>0);}const total=ws.reduce((n,x)=>n+x[1],0)||1,out=new Vector3();if(!ws.length)ws.push([1,1]);for(const [id,w]of ws)out.addScaledVector(transforms[id](new Vector3(...v)),w/total);return {v:out,ws:ws.map(([id,w])=>[id,w/total])};});
for(const f of faces){const isHead=f.every(i=>vertices[i][1]>5.78),isFoot=f.every(i=>transformed[i].ws.some(([id,w])=>[9,12].includes(id)&&w>.75));if(isFoot)continue;const out=isHead?head:body,map=isHead?headMap:bodyMap;const add=i=>{if(map.has(i))return map.get(i);const index=map.size;map.set(i,index);const {v,ws}=transformed[i];if(isHead){const p=transforms[2](new Vector3(...vertices[i])).sub(new Vector3(0,1.585,.005));out.positions.push(...p.toArray().map(round));}else{out.positions.push(...v.toArray().map(round));const pairs=[...ws];while(pairs.length<4)pairs.push([0,0]);out.skinIndices.push(...pairs.map(x=>x[0]));out.skinWeights.push(...pairs.map(x=>round(x[1])));const major=ws[0][0];out.regions.push(major>=3&&major<=6?(v.y>1.23?1:0):v.y<.42?3:v.y<.71?0:v.y<.965?2:v.y<1.44?1:0);}return index;};for(let k=1;k<f.length-1;k++)out.indices.push(add(f[0]),add(f[k]),add(f[k+1]));}
const eyes=['R','L'].map(s=>point('eye.'+s).sub(headRoot).multiplyScalar(.105).toArray().map(round));
const data={source:'MakeHuman hm08 core mesh, CC0; young adult male athletic blend',bones:ids,body,head,eyes};
fs.writeFileSync('src/anatomy-data.js','// Generated from the CC0 MakeHuman core assets. See licenses/MAKEHUMAN-CC0.md.\nexport const anatomy='+JSON.stringify(data)+';\n');console.log({bodyVertices:body.positions.length/3,headVertices:head.positions.length/3,triangles:(body.indices.length+head.indices.length)/3,eyes});
