import {defaultSquads,lineupProfiles} from '../src/squads.js';
import {cleanGameplay} from '../src/gameplay-settings.js';
import {FACE_ANCHORS} from '../src/face-identity.js';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../../.deploy-tools/package.json',import.meta.url)),WebSocket=require('ws');
const base=process.env.ONLINE_SERVER||'https://project-touchline-arena.project-touchline.workers.dev';
const origin=process.env.ONLINE_ORIGIN||'https://project-touchline-three.vercel.app';
async function api(path,body){const r=await fetch(base+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(JSON.stringify(data));return data;}
function connect(session){return new Promise((resolve,reject)=>{const messages=[],ws=new WebSocket(base.replace('https:','wss:')+`/rooms/${session.room}/socket`,{headers:{Origin:origin}});const timer=setTimeout(()=>{ws.close();reject(Error('Socket timeout'));},12000);ws.on('error',reject);ws.on('open',()=>ws.send(JSON.stringify({type:'auth',token:session.token,protocol:1})));ws.on('message',raw=>{const m=JSON.parse(raw);messages.push(m);if(m.type==='welcome'){clearTimeout(timer);resolve({ws,messages,send:data=>ws.send(JSON.stringify(data))});}});});}
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
let a,b,keep;
try{
 const gameplay=cleanGameplay({acceleration:112,braking:108,turnResponse:104,ballRoll:96,ballBounce:92,firstTouch:116,referee:'strict'});const profiles=defaultSquads(),home=lineupProfiles(profiles,0),away=lineupProfiles(profiles,1);const face='data:image/jpeg;base64,'+fs.readFileSync(new URL('../tests/face-online-fixture.jpg',import.meta.url)).toString('base64');for(const p of home){p.face={...p.face,enabled:true,assetId:'device-only-asset'};p.faceTexture=face;}home[9].weight=92.4;home[9].body={...home[9].body,shoulders:117,armLength:109,legLength:106,waist:88};home[9].face.identity={version:2,likeness:1,points:Object.entries(FACE_ANCHORS).map(([id,p])=>[+id,p[0]*1.015,p[1]])};home[9].face.fitted=true;home[9].name='CUSTOM HOME';away[9].name='CUSTOM AWAY';away[9].foot='left';away[9].height=1.96;const host=await api('/rooms',{name:'NETWORK CHECK A',halfSeconds:60,squad:home,gameplay}),guest=await api(`/rooms/${host.room}/join`,{name:'NETWORK CHECK B',squad:away});
 a=await connect(host);b=await connect(guest);a.send({type:'ready',ready:true});b.send({type:'ready',ready:true});await sleep(300);a.send({type:'start'});
 let seq=0;keep=setInterval(()=>{a.send({type:'input',seq:++seq,input:{axis:{x:1,z:0},sprint:true}});b.send({type:'input',seq,input:{axis:{x:0,z:0},autoDefend:true}});},1000/30);
 await sleep(4200);const sa=a.messages.filter(m=>m.type==='snapshot'),sb=b.messages.filter(m=>m.type==='snapshot');assert.ok(sa.length>20&&sb.length>20,'both clients must receive snapshots');const byFrame=new Map(sb.map(m=>[m.frame,m])),common=sa.filter(m=>byFrame.has(m.frame));assert.ok(common.length>=20,'both clients must receive at least 20 shared frames');for(const snapshot of common)assert.ok(JSON.stringify(snapshot)===JSON.stringify(byFrame.get(snapshot.frame)),`same frame ${snapshot.frame} must contain identical server state`);assert.ok(sb.some(m=>m.data.players.some(p=>p.autoDefending)), 'D hold must activate automatic defending on the live server');
 const startA=a.messages.find(m=>m.type==='start'),startB=b.messages.find(m=>m.type==='start');assert.deepEqual(startA.gameplay,gameplay);assert.deepEqual(startB.gameplay,gameplay);assert.deepEqual(a.messages.find(m=>m.type==='welcome').gameplay,gameplay);assert.deepEqual(startA.squads,startB.squads);assert.equal(startA.squads[0][9].name,'CUSTOM HOME');assert.equal(startA.squads[0][9].weight,92.4);assert.deepEqual(startA.squads[0][9].body,home[9].body,'body proportions must survive the live server');assert.deepEqual(startA.squads[0][9].face.identity,home[9].face.identity,'54 feature identity must survive the live server');assert.ok(startA.squads[0].every(p=>p.faceTexture===face&&p.face.assetId===null));assert.ok(startA.squads[1].every(p=>!p.faceTexture));assert.ok(sa.every(m=>!JSON.stringify(m).includes('data:image')));assert.equal(startA.squads[1][9].name,'CUSTOM AWAY');assert.equal(startA.squads[1][9].height,1.96);clearInterval(keep);a.send({type:'input',seq:++seq,input:{axis:{x:0,z:0}}});b.send({type:'input',seq,input:{axis:{x:0,z:0},autoDefend:false}});const releaseFrame=b.messages.filter(m=>m.type==='snapshot').at(-1).frame,releaseDeadline=Date.now()+3000;let released=false;while(Date.now()<releaseDeadline){a.send({type:'input',seq:++seq,input:{axis:{x:0,z:0}}});b.send({type:'input',seq,input:{axis:{x:0,z:0},autoDefend:false}});await sleep(50);released=b.messages.some(m=>m.type==='snapshot'&&m.frame>releaseFrame&&m.data.players.every(p=>!p.autoDefending));if(released)break;}assert.ok(released,'D release must clear automatic defending in a fresh snapshot');b.ws.close();await sleep(500);const before=a.messages.filter(m=>m.type==='snapshot').at(-1);await sleep(500);const after=a.messages.filter(m=>m.type==='snapshot').at(-1);assert.equal(before.frame,after.frame,'simulation pauses on disconnect');
 b=await connect(guest);await sleep(600);assert.deepEqual(b.messages.find(m=>m.type==='welcome').gameplay,gameplay,'host settings survive reconnect');const resumed=a.messages.filter(m=>m.type==='snapshot').at(-1);assert.ok(resumed.frame>after.frame,'same room resumes after token reconnect');
 const report={server:base,origin,room:host.room,clients:2,identicalAuthoritativeState:true,autoDefenceHoldAndRelease:true,customSquadsShared:true,hostGameplaySettingsShared:true,gameplay,photoFeatureIdentityShared:true,bodyProportionsShared:true,allElevenFaceTexturesShared:true,unsharedFacesAbsent:true,photosAbsentFromSnapshots:true,faceTextureCharacters:face.length,snapshots:[sa.length,sb.length],reconnectPassed:true,lastScore:resumed.data.score,checkedAt:new Date().toISOString()};fs.writeFileSync(process.env.ONLINE_REPORT||'reports/online-live-check.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{clearInterval(keep);a?.send({type:'leave'});a?.ws.close();b?.ws.close();}
