// Public factual roster snapshot, no photographs or third-party game ratings.
import fs from 'node:fs/promises';
import {normalizeRoster} from './normalize-kleague.mjs';
const codes={bucheon:'K26',seoul:'K09',ulsan:'K01',jeonbuk:'K05',pohang:'K03',incheon:'K18',gangwon:'K21',daejeon:'K10',jeju:'K04',gwangju:'K22',anyang:'K27',gimcheon:'K35'};
const root='https://www.kleague.com';
const text=s=>s.replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').trim();
function players(html){return [...html.matchAll(/onclick="onPlayerClicked\((\d+)\)"([\s\S]*?)(?=onclick="onPlayerClicked|<\/section|<ul class="pagination|<div class="al-right|$)/g)].flatMap(m=>{const name=m[2].match(/class="name">([^<]+)/)?.[1],number=m[2].match(/class="num campton">No\.(\d+)/)?.[1];return name&&number?[{id:m[1],name:text(name),number:Number(number)}]:[];});}
async function get(url){const res=await fetch(url,{headers:{'Accept-Language':'ko-KR,ko;q=0.9'},signal:AbortSignal.timeout(30000)});if(!res.ok)throw Error(`${res.status} ${url}`);return res.text();}
const clubs={},sources={};
const queue=Object.entries(codes);
async function worker(){while(queue.length){const [club,code]=queue.shift(),url=`${root}/club/club.do?teamId=${code}`,html=await get(url),current=players(html),roles=new Map();
 for(const [pos,role] of [['gk','GK'],['df','DEF'],['mf','MID'],['fw','FWD']]){
  const base=`${root}/player.do?type=active&leagueId=1&teamId=${code}&pos=${pos}`;
  const page=await get(base);for(const p of players(page))roles.set(p.id,role);
  const last=Number(page.match(/class="last[^" ]*(?: disabled)?" onclick="goToPage\((\d+)\)/)?.[1]||1);
  for(let n=2;n<=last;n++)for(const p of players(await get(`${base}&page=${n}`)))roles.set(p.id,role);
 }
 const rows=normalizeRoster(current.map(p=>({...p,role:roles.get(p.id)})));
 const missing=rows.filter(p=>!p.role);if(missing.length)throw Error(`${club}: missing position ${JSON.stringify(missing)}`);
 if(rows.length<18||new Set(rows.map(p=>p.id)).size!==rows.length)throw Error(`Invalid ${club} roster`);
 clubs[club]=rows;sources[club]={url,asOf:html.match(/(2026\.\d{2}\.\d{2}) 현재/)?.[1]||null};console.log(club,rows.length);
}}
await Promise.all([worker(),worker(),worker()]);
const ordered=Object.fromEntries(Object.keys(codes).map(id=>[id,clubs[id]]));
await fs.writeFile(new URL('../src/kleague-rosters.js',import.meta.url),`// Generated by tools/update-kleague.mjs from K League's current club lists.\nexport const ROSTER_DATE=${JSON.stringify(new Date().toISOString().slice(0,10))};\nexport const ROSTER_SOURCES=${JSON.stringify(sources,null,2)};\nexport const KLEAGUE_ROSTERS=${JSON.stringify(ordered,null,2)};\n`);
