import {BODY_FIELDS,BODY_PRESETS,cleanBody,cleanBodyType,applyBodyPreset} from './body-shape.js';
import {PlayerPortrait} from './player-portrait.js';
const $=id=>document.getElementById(id);
export class BodyStudio{
 constructor(apply){this.apply=apply;this.fields={};const panel=document.createElement('div');panel.id='body-studio';panel.className='overlay hidden';panel.innerHTML=`<section class="body-dialog" role="dialog" aria-modal="true" aria-labelledby="body-title"><div class="workspace-heading"><div><span class="eyebrow">BODY STUDIO</span><h2 id="body-title">키부터 실루엣까지.</h2><p>숫자로 맞추고, 돌려 보며 다듬으세요.</p></div><button id="body-close" class="secondary">편집 닫기 ×</button></div><div class="body-workspace"><section class="body-preview"><canvas id="body-portrait" aria-label="체형 전신 3D 미리보기"></canvas><div class="body-views"><button data-body-angle="0">정면</button><button data-body-angle="1.570796">측면</button><button data-body-angle="3.141593">뒷면</button><button id="body-motion">달리기 보기</button></div><p class="portrait-tip">드래그해서 360도 회전</p><output id="body-summary" aria-live="polite"></output><button id="body-compare" class="secondary">변경 전 체형과 비교</button><p id="body-preview-state">편집 중인 체형</p></section><section class="body-controls"><div class="body-preset"><label>체형 유형<select id="body-preset"></select></label><button id="body-reset" class="text-button">부위 비율 초기화</button></div><p class="body-help">키는 cm, 몸무게는 kg입니다. 부위 비율은 100%가 기본이며 근육량·볼륨은 0–100 단계입니다. 몸무게는 외형과 몸싸움 밀림에 반영됩니다. 속력·슈팅은 선수 능력치에서 따로 설정하세요.</p><div id="body-fields"></div></section></div><footer class="body-footer"><p id="body-status" role="status">적용한 뒤 선수 설정을 저장하세요.</p><button id="body-apply" class="primary">이 선수에 적용 ✓</button></footer></section>`;document.body.append(panel);
  for(const [key,preset]of Object.entries(BODY_PRESETS)){const o=document.createElement('option');o.value=key;o.textContent=preset.label;$('body-preset').append(o);}
  this.field('height','키',155,210,181,'cm','기본 치수',.1);this.field('weight','몸무게',45,125,78,'kg','기본 치수',.1);this.field('build','전체 체격',80,125,100,'%','기본 치수');
  for(const [key,[label,min,max,base,group]]of Object.entries(BODY_FIELDS))this.field(key,label,min,max,base,['muscle','softness'].includes(key)?'단계':'%',group);
  $('body-close').onclick=()=>this.close();$('body-apply').onclick=()=>this.save();$('body-reset').onclick=()=>{this.draft.body=cleanBody();this.sync();this.changed();};
  $('body-preset').onchange=e=>{const preset=BODY_PRESETS[e.target.value];if(preset){this.draft=applyBodyPreset(this.draft,e.target.value);this.sync();this.changed(false);}};
  $('body-compare').onclick=()=>{this.comparing=!this.comparing;this.preview();};
  for(const button of panel.querySelectorAll('[data-body-angle]'))button.onclick=()=>{this.portrait.angle=Number(button.dataset.bodyAngle);this.portrait.draw();};
  $('body-motion').onclick=()=>{this.portrait.motion=this.portrait.motion==='run'?'idle':'run';$('body-motion').textContent=this.portrait.motion==='run'?'서 있는 자세':'달리기 보기';this.portrait.rig.plantState=null;};
  addEventListener('keydown',e=>{if(e.code==='Escape'&&!panel.classList.contains('hidden')){e.preventDefault();this.close();}});
 }
 field(key,label,min,max,base,unit,group,step=1){let fieldset=[...$('body-fields').children].find(e=>e.dataset.group===group);if(!fieldset){fieldset=document.createElement('fieldset');fieldset.dataset.group=group;const legend=document.createElement('legend');legend.textContent=group;fieldset.append(legend);$('body-fields').append(fieldset);}const wrap=document.createElement('div');wrap.className='body-field';const title=document.createElement('label');title.htmlFor='body-'+key;title.textContent=label;const number=document.createElement('input');number.id='body-'+key;number.type='number';number.required=true;number.setAttribute('aria-label',label+' · '+unit);const range=document.createElement('input');range.id='body-range-'+key;range.type='range';range.setAttribute('aria-label',label+' 슬라이더');for(const input of [number,range]){input.min=min;input.max=max;input.step=step;input.value=base;}const suffix=document.createElement('span');suffix.textContent=unit;wrap.append(title,number,suffix,range);fieldset.append(wrap);this.fields[key]={number,range};const change=(input,other)=>{if(!input.checkValidity()||input.value===''){this.status('표시된 범위 안의 숫자를 입력해 주세요.');return;}const value=Number(input.value);other.value=value;if(key==='height'||key==='build')this.draft[key]=value/100;else if(key==='weight')this.draft.weight=value;else this.draft.body[key]=value;this.changed();};number.oninput=()=>change(number,range);range.oninput=()=>change(range,number);}
 open(profile,team){this.original=structuredClone(profile);this.draft=structuredClone(profile);this.draft.body=cleanBody(profile.body);this.team=team;this.comparing=false;$('body-studio').classList.remove('hidden');$('players-panel').inert=true;this.portrait??=new PlayerPortrait($('body-portrait'));this.portrait.mode='body';this.portrait.motion='idle';this.portrait.angle=0;$('body-motion').textContent='달리기 보기';$('body-preset').value=cleanBodyType(profile.bodyType,profile.body);this.sync();this.preview();this.status('조절값은 미리보기에 반영됩니다. 적용 후 선수 설정을 저장하세요.');$('body-height').focus();}
 sync(){for(const [key,{number,range}]of Object.entries(this.fields)){const value=key==='height'||key==='build'?Math.round(this.draft[key]*1000)/10:key==='weight'?this.draft.weight:this.draft.body[key];number.value=range.value=value;}}
 changed(custom=true){this.comparing=false;if(custom){this.draft.bodyType='unique';$('body-preset').value='unique';}this.summary();clearTimeout(this.timer);this.timer=setTimeout(()=>this.preview(),120);this.status('체형을 수정했습니다. 아직 선수 설정에 저장하지 않았습니다.');}
 summary(){const p=this.comparing?this.original:this.draft;$('body-summary').textContent=`${BODY_PRESETS[cleanBodyType(p.bodyType,p.body)].label} · ${Math.round(p.height*1000)/10} cm · ${p.weight} kg`;$('body-compare').textContent=this.comparing?'편집 중인 체형으로 돌아가기':'변경 전 체형과 비교';$('body-preview-state').textContent=this.comparing?'변경 전 체형':'편집 중인 체형';}
 preview(){clearTimeout(this.timer);this.summary();this.portrait.update(this.comparing?this.original:this.draft,this.team);}
 status(message){$('body-status').textContent=message;}
 close(){clearTimeout(this.timer);$('body-studio').classList.add('hidden');$('players-panel').inert=false;$('player-body-open').focus();}
 save(){for(const {number}of Object.values(this.fields))if(!number.checkValidity()||number.value===''){number.reportValidity();return;}this.apply({height:this.draft.height,weight:this.draft.weight,build:this.draft.build,body:cleanBody(this.draft.body),bodyType:this.draft.bodyType});this.close();}
}
