import {defaultFacePhotos} from './default-face.js';
import {fitPhoto} from './face-fit.js';
import {FACE_SHAPE,cleanFace,cleanCrop,facePreviewProfile} from './face-settings.js';
import {readFacePhoto,loadImage,drawCrop,bakeFaceAsset,putFaceAssets} from './face-assets.js';
import {PlayerPortrait} from './player-portrait.js';
const $=id=>document.getElementById(id),labels={front:'앞모습',side:'옆모습',back:'뒷모습'};
export class FaceStudio{
 constructor(apply){this.apply=apply;this.token=0;this.shapeFields={};for(const [key,[label,min,max]]of Object.entries(FACE_SHAPE)){const wrap=document.createElement('label');wrap.textContent=label;const slider=document.createElement('input');slider.type='range';slider.min=min;slider.max=max;slider.step=.01;slider.value=1;slider.id='face-shape-'+key;slider.setAttribute('aria-label',label);slider.oninput=()=>{this.face.shape[key]=Number(slider.value);this.drawPlayer();};wrap.append(slider);$('face-shapes').append(wrap);this.shapeFields[key]=slider;}
  for(const view of Object.keys(labels)){$('face-upload-'+view).onchange=e=>this.upload(view,e.target);$('face-select-'+view).onclick=()=>this.select(view);$('face-remove-'+view).onclick=()=>{delete this.sources[view];delete this.images[view];this.baked=null;this.select(view);this.drawPlayer();};}
  for(const field of ['zoom','x','y','rotation','eyes','nose','mouth'])$('face-'+field).oninput=()=>{this.crops[this.view][field]=Number($('face-'+field).value);this.baked=null;this.drawCrop();};$('face-flip').onchange=e=>{this.crops[this.view].flip=e.target.checked;this.baked=null;this.drawCrop();};$('face-photo-hair').onchange=e=>{this.face.photoHair=e.target.checked;this.drawPlayer();};$('face-bake').onclick=()=>this.bake();$('face-apply').onclick=()=>this.save();$('face-close').onclick=()=>this.close();$('face-reset-crop').onclick=()=>{this.crops[this.view]=cleanCrop();this.baked=null;this.select(this.view);};
  const canvas=$('face-crop');canvas.onpointerdown=e=>{if(this.busy||!this.images[this.view])return;canvas.setPointerCapture(e.pointerId);this.drag={x:e.clientX,y:e.clientY,crop:{...this.crops[this.view]}};};canvas.onpointermove=e=>{if(!this.drag)return;const rect=canvas.getBoundingClientRect();this.crops[this.view].x=Math.max(-1,Math.min(1,this.drag.crop.x+(e.clientX-this.drag.x)/rect.width));this.crops[this.view].y=Math.max(-1,Math.min(1,this.drag.crop.y+(e.clientY-this.drag.y)/rect.height));this.baked=null;this.select(this.view);};canvas.onpointerup=canvas.onpointercancel=()=>this.drag=null;
  $('face-example').onclick=async()=>{if(this.busy)return;this.setBusy(true);try{const data=await defaultFacePhotos();this.sources={...data.sources};this.crops=structuredClone(data.crops);for(const view of Object.keys(labels))this.images[view]=await loadImage(this.sources[view]);this.baked=null;this.face.fitted=false;this.face.identity=null;this.face.photoHair=true;$('face-photo-hair').checked=true;this.select('front');this.status('가상 선수의 예시 사진입니다. 사진에서 3D 얼굴 만들기를 누르세요.');}catch(e){this.status(e.message);}finally{this.setBusy(false);}};
  const controls=document.createElement('div');controls.className='face-model-controls';controls.innerHTML='<label>얼굴 표현<select id="face-mode"><option value="sculpt">입체 선수 얼굴 · 3D</option><option value="photo">사진 표면 · 이전 방식</option></select></label><button id="face-fit" class="primary">사진에서 3D 얼굴 만들기 ↗</button><p>정면 사진의 눈매·눈썹·입 위치·턱선을 분석해 3D 얼굴을 변형합니다. 사진은 이 브라우저 안에서만 분석됩니다.</p>'; $('face-shapes').before(controls);$('face-mode').onchange=e=>{this.face.mode=e.target.value;this.drawPlayer();};$('face-fit').onclick=()=>this.fit();const compare=document.createElement('button');compare.id='face-compare';compare.className='secondary';compare.textContent='분석 전 얼굴과 비교';compare.onclick=()=>{this.compare=!this.compare;compare.textContent=this.compare?'사진 분석 얼굴로 돌아가기':'분석 전 얼굴과 비교';this.drawPlayer();};controls.append(compare);
  $('face-camera').onchange=e=>{this.portrait.mode=e.target.value;this.portrait.draw();};addEventListener('keydown',e=>{if(e.code==='Escape'&&!$('face-studio').classList.contains('hidden')){e.preventDefault();this.close();}});
 }
 async open(profile,asset,team){this.token++;this.busy=false;this.setBusy(false);this.profile=structuredClone(profile);this.compare=false;$('face-compare').textContent='분석 전 얼굴과 비교';this.team=team;this.face=cleanFace(profile.face);this.sources={...asset?.sources};this.crops=Object.fromEntries(Object.keys(labels).map(v=>[v,cleanCrop(asset?.crops?.[v])]));this.images={};this.baked=asset||null;this.busy=false;this.portrait??=new PlayerPortrait($('face-portrait'));this.portrait.mode='face';$('face-camera').value='face';$('face-mode').value=this.face.mode;$('face-studio').classList.remove('hidden');$('face-studio').scrollTop=0;$('players-panel').inert=true;for(const [key,el]of Object.entries(this.shapeFields))el.value=this.face.shape[key];$('face-photo-hair').checked=this.face.photoHair;const token=this.token;for(const view of Object.keys(this.sources)){const image=await loadImage(this.sources[view]);if(token!==this.token)return;this.images[view]=image;}this.select('front');this.drawPlayer();this.status(this.face.fitted&&!this.face.identity?'이전 분석 방식으로 저장된 얼굴입니다. 사진에서 3D 얼굴 만들기를 다시 눌러 눈매·턱선을 새로 분석하세요.':'앞모습 사진을 선택하면 바로 분석합니다. 옆·뒤 사진은 두상과 머리 모양을 맞추는 참고로 사용할 수 있습니다.');}
 close(){if(this.busy)return;this.token++;$('face-studio').classList.add('hidden');$('players-panel').inert=false;$('player-face-open').focus();}
 setBusy(value){this.busy=value;for(const el of $('face-studio').querySelectorAll('input,button,select'))el.disabled=value;if(!value&&this.view)this.select(this.view);}
 status(text){$('face-status').textContent=text;}
 select(view){this.view=view;for(const key of Object.keys(labels)){$('face-select-'+key).classList.toggle('selected',key===view);$('face-photo-state-'+key).textContent=this.sources[key]?'사진 있음':'사진 없음';$('face-remove-'+key).disabled=!this.sources[key];}for(const key of ['zoom','x','y','rotation','eyes','nose','mouth'])$('face-'+key).value=this.crops[view][key];$('face-flip').checked=this.crops[view].flip;$('face-crop-title').textContent=labels[view]+' · 사진 정렬';this.drawCrop();}
 drawCrop(){drawCrop($('face-crop'),this.images[this.view],this.crops[this.view],true);}
 drawPlayer(){this.portrait.update(facePreviewProfile(this.profile,this.face,this.baked,this.compare),this.team);}
 async fit(){if(this.busy)return;if(!this.images.front){this.status('앞모습 사진을 먼저 넣어 주세요.');return;}this.setBusy(true);this.status('기기 안에서 얼굴 비율을 분석하는 중… 첫 실행은 모델을 준비하는 데 시간이 걸립니다.');try{const result=await fitPhoto(this.images.front);this.compare=false;$('face-compare').textContent='분석 전 얼굴과 비교';this.face={...this.face,mode:'sculpt',enabled:true,fitted:true,identity:result.identity,shape:result.shape};this.profile.skin=result.skin;if(this.baked)this.baked={...this.baked,skin:result.skin};for(const [key,input]of Object.entries(this.shapeFields))input.value=this.face.shape[key];$('face-mode').value='sculpt';this.drawPlayer();this.status('사진의 눈매·눈썹·코·입·턱선 위치를 입체 얼굴에 적용했습니다. 사진과 미리보기를 비교한 뒤 이 선수에 적용을 누르세요. 코 깊이와 머리 모양은 직접 다듬을 수 있습니다.');}catch(e){this.status(e.message);}finally{this.setBusy(false);}}
 async upload(view,input){if(!input.files[0]||this.busy)return;const token=this.token;let loaded=false;this.setBusy(true);try{this.status('사진을 읽는 중…');const source=await readFacePhoto(input.files[0]);if(token!==this.token)return;const image=await loadImage(source);if(token!==this.token)return;if(view==='front'){this.face.fitted=false;this.face.identity=null;}this.sources[view]=source;this.images[view]=image;loaded=true;this.crops[view]=cleanCrop();this.baked=null;this.select(view);this.status('입체 얼굴은 사진에서 3D 얼굴 만들기를 누르세요. 정렬 도구는 이전 사진 표면 방식에 사용합니다.');}catch(e){this.status(e.message);}finally{input.value='';if(token===this.token)this.setBusy(false);}if(loaded&&view==='front'&&token===this.token)await this.fit();}
 async bake(){if(this.busy)return null;this.setBusy(true);this.status('사진과 얼굴 설정을 저장할 준비 중…');try{await new Promise(requestAnimationFrame);this.baked=await bakeFaceAsset(this.sources,this.crops,this.profile.skin);if(this.face.mode==='sculpt'&&this.face.fitted)this.baked.skin=this.profile.skin;this.drawPlayer();this.status('3D에 적용했습니다. 돌려서 확인한 뒤 선수에 적용을 누르세요.');return this.baked;}catch(e){this.status(e.message);return null;}finally{this.setBusy(false);}}
 async save(){if(this.busy)return;if(!this.sources.front&&Object.keys(this.sources).length){this.status('앞모습 사진을 먼저 넣어 주세요.');return;}if(!this.baked&&this.sources.front&&!await this.bake())return;this.setBusy(true);try{if(this.baked)await putFaceAssets([this.baked]);this.apply({...this.face,assetId:this.baked?.id||null,enabled:true},this.baked);this.setBusy(false);this.close();}catch(e){this.status(e.message);}finally{this.setBusy(false);}}
}
