import {cleanCrop,projectionSample,validFaceTexture} from './face-settings.js';
import {loadCanonicalFace,warpTriangles} from './face-uv.js';
const VIEWS=['front','side','back'],FACE_UV_SIZE=512;
let database;
function db(){return database??=new Promise((resolve,reject)=>{const r=indexedDB.open('touchline-face-assets',1);r.onupgradeneeded=()=>r.result.createObjectStore('faces',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>{database=null;reject(Error('사진 저장 공간을 열 수 없습니다. 브라우저 저장 권한을 확인해 주세요.'));};});}
export async function getFaceAsset(id){if(!id)return null;const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction('faces').objectStore('faces').get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);});}
export async function putFaceAssets(assets){const clean=assets.map(cleanFaceAsset),d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('faces','readwrite');for(const asset of clean)tx.objectStore('faces').put(asset);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(Error('사진 저장 공간이 부족합니다. 먼저 선수 파일을 내보내 주세요.'));tx.onabort=()=>reject(Error('사진을 저장하지 못했습니다. 다시 시도해 주세요.'));});}
export function cleanFaceAsset(raw){if(!raw||!/^[a-z\d-]{1,64}$/i.test(raw.id))throw Error('페이스온 파일의 식별자가 올바르지 않습니다.');const atlas=validFaceTexture(raw.atlas,180000),online=validFaceTexture(raw.online,32000);if(!atlas||!online)throw Error('페이스온 이미지 형식을 확인해 주세요.');const sources={},crops={};for(const view of VIEWS){if(raw.sources?.[view]){const value=validFaceTexture(raw.sources[view],750000);if(!value)throw Error('지원하지 않거나 너무 큰 사진입니다.');sources[view]=value;}crops[view]=cleanCrop(raw.crops?.[view]);}
 // faceUV (canonical MediaPipe face space, src/face-uv.js) is only produced when the bake had 468 landmarks;
 // older saved assets have neither field, and src/human-kit.js composePhotoHead falls back to the original
 // headToAtlas mapping for them.
 return {id:raw.id,version:1,atlas,online,faceUV:validFaceTexture(raw.faceUV,140000),faceUVOnline:validFaceTexture(raw.faceUVOnline,28000),sources,crops,skin:/^#[a-f\d]{6}$/i.test(raw.skin)?raw.skin:'#c89572',createdAt:typeof raw.createdAt==='string'?raw.createdAt.slice(0,30):new Date().toISOString()};}
export function loadImage(source){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('사진을 읽을 수 없습니다. JPG·PNG·WebP 파일을 사용해 주세요.'));image.src=source;});}
export async function readFacePhoto(file){const heic=/hei[cf]/i.test(file.type)||/\.hei[cf]$/i.test(file.name||'');if(file.type&&!file.type.startsWith('image/'))throw Error('사진 파일을 선택해 주세요.');if(file.size>12*1024*1024)throw Error('사진 한 장은 12MB 이하로 넣어 주세요.');const url=URL.createObjectURL(file);try{let image;try{image=await loadImage(url);}catch{throw Error(heic?'이 브라우저는 아이폰 HEIC 사진을 열지 못합니다. 카메라 버튼으로 찍거나, 사진을 JPG로 저장해 넣어 주세요(Safari에서는 바로 열립니다).':'사진을 열지 못했습니다. JPG·PNG·WebP 사진을 넣어 주세요.');}if(image.width*image.height>40000000)throw Error('사진 해상도가 너무 큽니다. 4천만 화소 이하로 줄여 주세요.');const scale=Math.min(1,1024/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#b8b0a2';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);return boundedJPEG(canvas,750000,.88);}finally{URL.revokeObjectURL(url);}}
export function drawCrop(canvas,image,crop={},guides=false){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,c=cleanCrop(crop);ctx.fillStyle='#273c35';ctx.fillRect(0,0,w,h);if(image){const scale=Math.max(w/image.width,h/image.height)*c.zoom;ctx.save();ctx.translate(w/2+c.x*w,h/2+c.y*h);ctx.rotate(c.rotation*Math.PI/180);ctx.scale(c.flip?-scale:scale,scale);ctx.drawImage(image,-image.width/2,-image.height/2);ctx.restore();}if(guides){ctx.save();ctx.strokeStyle='#d9ff8a';ctx.lineWidth=1;ctx.setLineDash([5,4]);ctx.beginPath();ctx.ellipse(w*.5,h*.49,w*.4,h*.48,0,0,Math.PI*2);ctx.moveTo(w*.5,0);ctx.lineTo(w*.5,h);for(const v of [c.eyes,c.nose,c.mouth]){ctx.moveTo(w*.12,h*v);ctx.lineTo(w*.88,h*v);}ctx.stroke();ctx.setLineDash([]);ctx.font='12px sans-serif';ctx.fillStyle='#d9ff8a';ctx.fillText('눈',8,h*c.eyes-5);ctx.fillText('코',8,h*c.nose-5);ctx.fillText('입',8,h*c.mouth-5);ctx.restore();}}
export function cropPixels(image,crop,size=512){const canvas=document.createElement('canvas');canvas.width=size;canvas.height=Math.round(size*1.25);drawCrop(canvas,image,crop);return canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height);}
const hex=n=>Math.max(0,Math.min(255,Math.round(n))).toString(16).padStart(2,'0');
export function sampleSkin(pixels){let rgb=[0,0,0],count=0;for(const center of [[.35,.64],[.65,.64],[.5,.3]])for(let y=-3;y<=3;y++)for(let x=-3;x<=3;x++){const i=(Math.round(center[1]*pixels.height+y)*pixels.width+Math.round(center[0]*pixels.width+x))*4;for(let c=0;c<3;c++)rgb[c]+=pixels.data[i+c];count++;}return '#'+rgb.map(n=>hex(n/count)).join('');}
export async function bakeFaceAsset(sources,crops,skin='#c89572',landmarks=null){if(!sources.front)throw Error('앞모습 사진을 먼저 넣어 주세요.');const images={},pixels={};for(const view of VIEWS)if(sources[view]){images[view]=await loadImage(sources[view]);pixels[view]=cropPixels(images[view],crops[view]);}skin=sampleSkin(pixels.front);const base=[1,3,5].map(i=>parseInt(skin.slice(i,i+2),16)),canvas=document.createElement('canvas');canvas.width=1024;canvas.height=512;const ctx=canvas.getContext('2d'),image=ctx.createImageData(canvas.width,canvas.height);
 for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const sample=projectionSample(x/(canvas.width-1),y/(canvas.height-1)),i=(y*canvas.width+x)*4;let color=[0,0,0];for(const view of VIEWS){const p=sample[view],source=pixels[view];if(!source){for(let c=0;c<3;c++)color[c]+=base[c]*p.weight;continue;}const xx=Math.max(0,Math.min(source.width-1,Math.round(p.u*(source.width-1)))),yy=Math.max(0,Math.min(source.height-1,Math.round(warpFaceV(p.v,crops[view])*(source.height-1)))),j=(yy*source.width+xx)*4;for(let c=0;c<3;c++)color[c]+=source.data[j+c]*p.weight;}for(let c=0;c<3;c++)image.data[i+c]=color[c];image.data[i+3]=255;}ctx.putImageData(image,0,0);const atlas=boundedJPEG(canvas,180000,.87);const small=document.createElement('canvas');small.width=384;small.height=192;small.getContext('2d').drawImage(canvas,0,0,384,192);const online=boundedJPEG(small,32000,.75);
 let faceUV=null,faceUVOnline=null;
 if(landmarks?.length>=468){const uvCanvas=await bakeFaceUV(images.front,landmarks,skin);if(uvCanvas){faceUV=boundedJPEG(uvCanvas,140000,.87);const uvSmall=document.createElement('canvas');uvSmall.width=uvSmall.height=192;uvSmall.getContext('2d').drawImage(uvCanvas,0,0,192,192);faceUVOnline=boundedJPEG(uvSmall,28000,.75);}}
 return cleanFaceAsset({id:crypto.randomUUID(),atlas,online,faceUV,faceUVOnline,sources,crops,skin,createdAt:new Date().toISOString()});}
/**
 * The front photo warped into MediaPipe's canonical face UV space (src/face-uv.js), triangle by triangle,
 * for src/human-kit.js composePhotoHead's per-avatar landmark calibration. `landmarks` are the 468 points in
 * the front image's own normalized coordinates (src/face-fit-worker.js). Returns null (falls back to the
 * original atlas mapping) if the canonical face data can't be loaded.
 */
async function bakeFaceUV(image,landmarks,skin){
 let canonical;try{canonical=await loadCanonicalFace();}catch{return null;}
 const N=FACE_UV_SIZE,canvas=document.createElement('canvas');canvas.width=canvas.height=N;const ctx=canvas.getContext('2d');
 const base=[1,3,5].map(i=>parseInt(skin.slice(i,i+2),16));ctx.fillStyle=`rgb(${base.join(',')})`;ctx.fillRect(0,0,N,N);
 const src=landmarks.map(([x,y])=>[x*image.width,y*image.height]),dst=canonical.uv.map(([u,v])=>[u*N,v*N]);
 warpTriangles(ctx,image,src,dst,canonical.triangles);
 return canvas;
}

export function warpFaceV(v,crop){const c=cleanCrop(crop),from=[0,.444,.603,.797,1],to=[0,c.eyes,c.nose,c.mouth,1];let i=1;while(i<4&&v>from[i])i++;return to[i-1]+(to[i]-to[i-1])*(v-from[i-1])/(from[i]-from[i-1]);}

function boundedJPEG(canvas,max,quality){let image;for(let q=quality;q>=.18;q-=.12){image=canvas.toDataURL('image/jpeg',q);if(image.length<=max)return image;}throw Error('사진의 세부 정보가 너무 많습니다. 얼굴 중심으로 잘라서 다시 넣어 주세요.');}
