import * as THREE from 'three';
// Bake only static meshes. Articulated child groups and instanced crowds remain independent.
export function mergeMeshes(root,recursive=false){root.updateMatrixWorld(true);const inverse=root.matrixWorld.clone().invert(),buckets=new Map(),meshes=[];
 const collect=obj=>{if(obj.isMesh&&!obj.isSkinnedMesh&&!obj.morphTargetInfluences&&!obj.userData.keepSeparate&&!obj.isInstancedMesh&&!Array.isArray(obj.material))meshes.push(obj);};if(recursive)root.traverse(collect);else root.children.forEach(collect);
 for(const m of meshes){const key=m.material.uuid+':'+m.castShadow+':'+m.receiveShadow;let list=buckets.get(key);if(!list)buckets.set(key,list=[]);list.push(m);}
 for(const list of buckets.values()){if(list.length<2)continue;const geometries=list.map(m=>{const g=m.geometry.index?m.geometry.toNonIndexed():m.geometry.clone();g.applyMatrix4(new THREE.Matrix4().multiplyMatrices(inverse,m.matrixWorld));return g;});const geometry=new THREE.BufferGeometry();for(const [name,size]of [['position',3],['normal',3],['uv',2]]){const length=geometries.reduce((sum,g)=>sum+g.attributes.position.count*size,0),buffer=new Float32Array(length);let offset=0;for(const g of geometries){const a=g.attributes[name];if(a)buffer.set(a.array,offset);offset+=g.attributes.position.count*size;}geometry.setAttribute(name,new THREE.BufferAttribute(buffer,size));}const merged=new THREE.Mesh(geometry,list[0].material);merged.castShadow=list[0].castShadow;merged.receiveShadow=list[0].receiveShadow;root.add(merged);list.forEach(m=>m.removeFromParent());geometries.forEach(g=>g.dispose());}
}
const distantMaterial=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.83});
export function addDistantGeometry(root,includeDeforming=false){const near=root.children.filter(m=>m.isMesh&&!m.isSkinnedMesh&&(includeDeforming||!m.morphTargetInfluences&&!m.userData.keepSeparate)&&!m.material.transparent&&!m.material.map);if(near.length<2)return null;const geos=[],positions=[],normals=[],colors=[];root.updateMatrixWorld(true);const inv=root.matrixWorld.clone().invert();
 for(const m of near){const g=m.geometry.index?m.geometry.toNonIndexed():m.geometry.clone();g.applyMatrix4(new THREE.Matrix4().multiplyMatrices(inv,m.matrixWorld));const p=g.attributes.position,n=g.attributes.normal,col=m.material.color;for(let i=0;i<p.count;i++){positions.push(p.getX(i),p.getY(i),p.getZ(i));normals.push(n.getX(i),n.getY(i),n.getZ(i));colors.push(col.r,col.g,col.b);}g.dispose();}
 const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const far=new THREE.Mesh(g,distantMaterial);far.castShadow=true;far.visible=false;root.add(far);return {near,far};}
