import {Vector3,Quaternion} from '../vendor/three.module.js';
import {THROW,throwHandsPosition} from './throw-in.js';
const down=new Vector3(0,-1,0);
export function solveHand(rig,index,target,bendHint=null){const arm=rig.arms[index];rig.root.updateWorldMatrix(true,false);const shoulder=arm.upper.getWorldPosition(new Vector3()),elbow=arm.lower.getWorldPosition(new Vector3()),size=rig.root.scale.y,a=shoulder.distanceTo(elbow),b=(rig.bodyMetrics?.handReach||.27)*size,direction=target.clone().sub(shoulder),requested=direction.length(),r=Math.max(Math.abs(a-b)+.002,Math.min(a+b-.002,requested));direction.normalize();const bend=(bendHint?bendHint.clone():new Vector3(index===0?-.8:.8,-1,-.2)).applyQuaternion(rig.root.quaternion);bend.addScaledVector(direction,-bend.dot(direction)).normalize();const projection=(a*a+r*r-b*b)/(2*r),height=Math.sqrt(Math.max(0,a*a-projection*projection)),mid=shoulder.clone().addScaledVector(direction,projection).addScaledVector(bend,height),end=shoulder.clone().addScaledVector(direction,r);arm.upper.quaternion.setFromUnitVectors(down,mid.clone().sub(shoulder).normalize().applyQuaternion(arm.upper.parent.getWorldQuaternion(new Quaternion()).invert()));rig.root.updateWorldMatrix(true,false);arm.lower.quaternion.setFromUnitVectors(down,end.sub(mid).normalize().applyQuaternion(arm.lower.parent.getWorldQuaternion(new Quaternion()).invert()));rig.root.updateWorldMatrix(true,false);return arm.lower.localToWorld(new Vector3(0,-(rig.bodyMetrics?.handReach||.27),0)).distanceTo(target);}
// Throw-in: both hands grip the sides of the ball the rules hold overhead, elbows forward and
// out, and carry on through the release into the follow-through.
function holdThrowIn(rig,p){const a=p.action,t=a?.type==='throw'?a.elapsed:-1,b=throwHandsPosition(p,t);if(b.weight<=0)return;let error=0;
 for(let i=0;i<2;i++){const arm=rig.arms[i],upper=arm.upper.quaternion.clone(),lower=arm.lower.quaternion.clone();const side=(i===0?-1:1)*b.spread,target=new Vector3(b.x+Math.cos(p.yaw)*side,b.y,b.z-Math.sin(p.yaw)*side);error=Math.max(error,solveHand(rig,i,target,new Vector3((i===0?-1:1)*.6,.35,.75)));if(b.weight<1){arm.upper.quaternion.slerp(upper,1-b.weight);arm.lower.quaternion.slerp(lower,1-b.weight);}}rig.handError=error;}
export function stabilizeHands(rig,p,time){if(p.action?.type==='throw'?p.action.elapsed<=THROW.end:p.throwHold&&!p.action){holdThrowIn(rig,p);return;}const motion=p.keeperMotion;if(!motion||time>motion.until||!motion.target)return;const b=motion.target;let error=0;for(let i=0;i<2;i++){const side=(i===0?-1:1)*.085,target=new Vector3(b.x+Math.cos(p.yaw)*side,b.y,b.z-Math.sin(p.yaw)*side);error=Math.max(error,solveHand(rig,i,target));}rig.handError=error;}
