import * as THREE from '../vendor/three.module.js';
import {createPlayer,animatePlayer,disposePlayerRig} from './player.js';
import {applyBodyPreset,cleanBody} from './body-shape.js';
import {locomotionCadence} from './motion-planner.js';
const $=id=>document.getElementById(id),scene=new THREE.Scene();scene.background=new THREE.Color('#cbd1c7');
const renderer=new THREE.WebGLRenderer({canvas:$('scene'),antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const camera=new THREE.OrthographicCamera(-2.8,2.8,2.2,-.3,.1,100);camera.position.set(0,1.3,8);camera.lookAt(0,1,0);
scene.add(new THREE.HemisphereLight(0xf7f9ee,0x4b6558,2));const key=new THREE.DirectionalLight(0xfff5e6,3);key.position.set(-3,6,5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-4;key.shadow.camera.right=4;key.shadow.camera.top=4;key.shadow.camera.bottom=-4;key.shadow.normalBias=.015;scene.add(key);const rim=new THREE.DirectionalLight(0xdde8ff,1.6);rim.position.set(3,4,-3);scene.add(rim);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(40,40),new THREE.MeshStandardMaterial({color:0xa7b6a1,roughness:.96}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;ground.position.y=-.002;scene.add(ground);
let view=0,time=1,playing=false,last=performance.now(),mode='idle';const base={name:'TOUCHLINE',height:1.81,weight:78,build:1,skin:'#c89572',hair:'#211a15',hairStyle:'crop',boots:'#e3e4dc',face:{mode:'sculpt'},body:cleanBody()};
const profiles=['slim','normal','sturdy','unique'].map(type=>applyBodyPreset(base,type));profiles[3].body=cleanBody({legLength:106,armLength:104,shoulders:106,waist:90,muscle:72,softness:20});
const rigs=profiles.map((profile,i)=>{const r=createPlayer(0,10,false,profile);r.root.position.x=(i-1.5)*1.36;scene.add(r.root);return r;});
function resize(){const w=$('scene').clientWidth,h=$('scene').clientHeight;renderer.setSize(w,h,false);const half=2.83,vertical=half*h/w;camera.left=-half;camera.right=half;camera.top=vertical;camera.bottom=-vertical;camera.updateProjectionMatrix();}
function pose(r,p,i,dt){const speed={idle:0,walk:1.3,run:3.5,sprint:8.5}[mode]||0;r.root.rotation.y=view;r.root.position.x=(i-1.5)*1.36+Math.sin(view)*speed*time;r.root.position.z=Math.cos(view)*speed*time;const state={...p,x:r.root.position.x,z:r.root.position.z,yaw:view,vx:Math.sin(view)*speed,vz:Math.cos(view)*speed,motionPhase:time*locomotionCadence(speed,'balanced',p),motionAcceleration:0,motionTurn:0};animatePlayer(r,speed,dt,time,false,state);if(['t','squat','arms'].includes(mode)){r.hips.position.y=r.bodyMetrics.hipY;r.hips.rotation.set(0,0,0);r.torso.rotation.set(0,0,0);for(let j=0;j<2;j++){r.legs[j].upper.rotation.set(mode==='squat'?-1.05:0,0,0);r.legs[j].lower.rotation.set(mode==='squat'?2.1:0,0,0);r.legs[j].foot.rotation.set(mode==='squat'?-1.05:0,0,0);r.arms[j].upper.rotation.set(0,0,(j===0?-1:1)*(mode==='arms'?2.8:mode==='t'?1.57:.15));r.arms[j].lower.rotation.set(-.2,0,0);}if(mode==='squat')r.hips.position.y-=.36;}r.root.updateMatrixWorld(true);}
function draw(dt=1/60){rigs.forEach((r,i)=>pose(r,profiles[i],i,dt));const speed={idle:0,walk:1.3,run:3.5,sprint:8.5}[mode]||0,x=Math.sin(view)*speed*time,z=Math.cos(view)*speed*time;camera.position.x=x;camera.position.z=z+(camera.position.y>4?.01:8);camera.lookAt(x,1,z);renderer.render(scene,camera);}
for(const button of document.querySelectorAll('[data-view]'))button.onclick=()=>{view={front:0,side:Math.PI/2,back:Math.PI,top:0}[button.dataset.view];camera.position.set(0,button.dataset.view==='top'?8:1.22,button.dataset.view==='top'?.01:8);camera.lookAt(0,1,0);draw();};
$('motion').onchange=e=>{mode=e.target.value;for(const r of rigs){r.plantState=null;r.motionHistory=null;}draw();};$('pause').onclick=()=>{playing=!playing;$('pause').textContent=playing?'동작 멈춤':'동작 재생';};$('step').onclick=()=>{playing=false;time+=1/60;draw();};
const save=document.createElement('button');save.textContent='비교 이미지 저장';document.querySelector('nav').append(save);
save.onclick=()=>{draw();const canvas=document.createElement('canvas'),w=renderer.domElement.width,h=renderer.domElement.height;canvas.width=w;canvas.height=h+140;const cx=canvas.getContext('2d');cx.fillStyle='#111816';cx.fillRect(0,0,w,h+140);cx.fillStyle='#e8ece4';cx.font='bold 26px Arial';cx.fillText('TOUCHLINE · 실제 게임 모델',30,42);cx.drawImage(renderer.domElement,0,65);cx.textAlign='center';['마름','보통','건장','고유'].forEach((text,i)=>cx.fillText(text,w*(i+.5)/4,h+115));const link=document.createElement('a');link.download='touchline-human-'+(view===Math.PI/2?'side':view===Math.PI?'back':'front')+'.png';link.href=canvas.toDataURL('image/png');link.click();};
const sheet=document.createElement('button');sheet.textContent='연속 24프레임 저장';document.querySelector('nav').append(sheet);sheet.onclick=()=>{playing=false;$('pause').textContent='동작 재생';const canvas=document.createElement('canvas'),w=600,h=Math.round(w*renderer.domElement.height/renderer.domElement.width);canvas.width=w*4;canvas.height=(h+30)*6;const cx=canvas.getContext('2d');cx.fillStyle='#111816';cx.fillRect(0,0,canvas.width,canvas.height);for(let frame=0;frame<24;frame++){time+=1/60;draw(1/60);const x=frame%4*w,y=Math.floor(frame/4)*(h+30);cx.drawImage(renderer.domElement,x,y,w,h);cx.fillStyle='#e8ece4';cx.font='16px Arial';cx.fillText(`${mode} · ${frame+1}/24 · t=${time.toFixed(3)} s`,x+12,y+h+21);}const link=document.createElement('a');link.download=`touchline-human-${mode}-frames.png`;link.href=canvas.toDataURL('image/png');link.click();if(['127.0.0.1','localhost'].includes(location.hostname)&&new URLSearchParams(location.search).has('audit'))canvas.toBlob(body=>fetch('/__audit/evidence?name=touchline-'+new URLSearchParams(location.search).get('audit')+'-human-'+mode+'-frames.png',{method:'POST',body}));};
$('measure').onclick=()=>{playing=false;const samples=[],bench=Array.from({length:22},(_,i)=>createPlayer(i%2,10,false,profiles[i%4]));for(let frame=0;frame<100;frame++){const start=performance.now();for(let i=0;i<22;i++){bench[i].distant=i>=6;pose(bench[i],profiles[i%4],i,1/60);(bench[i].distant?bench[i].anatomy.farSkeleton:bench[i].anatomy.skeleton).update();}if(frame>=20)samples.push(performance.now()-start);time+=1/60;}bench.forEach(disposePlayerRig);samples.sort((a,b)=>a-b);$('metrics').textContent=`22명 (근거리 6 · 원거리 16) / CPU 중앙값 ${samples[40].toFixed(2)} ms · 95% ${samples[76].toFixed(2)} ms\n목표 4 ms · GPU 렌더 비용은 별도`;draw();};
addEventListener('resize',()=>{resize();draw();});addEventListener('error',e=>$('error').textContent=e.message);await Promise.all(rigs.map(r=>r.ready));resize();for(let i=0;i<30;i++)draw();$('metrics').textContent=`변형 관절 ${rigs[0].anatomy.skeleton.bones.length}개 · 마름 / 보통 / 건장 / 고유 · 사용자 저장 데이터와 분리된 비교 화면`;
function frame(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(playing){time+=dt;draw(dt);}requestAnimationFrame(frame);}requestAnimationFrame(frame);

// Explicit local audit export, without reading editor saves.
if(['localhost','127.0.0.1'].includes(location.hostname)&&new URLSearchParams(location.search).has('audit')){
 const nativeSave=save.onclick;save.onclick=()=>{nativeSave();const label=new URLSearchParams(location.search).get('audit'),angle=view===Math.PI/2?'side':view===Math.PI?'back':'front';renderer.domElement.toBlob(body=>fetch('/__audit/evidence?name=touchline-'+label+'-human-'+angle+'.png',{method:'POST',body}));};
}
