import {defaultFaceTexture} from './default-face.js';
import {createSculptedHead} from './sculpted-head.js';
import * as THREE from '../vendor/three.module.js';
import {cleanFace} from './face-settings.js';
const gauss=(x,s)=>Math.exp(-((x/s)**2));
const rings=[[-.142,.014,.025,.014],[-.125,.041,.043,.013],[-.106,.06,.058,.007],[-.079,.072,.073,0],[-.05,.079,.085,-.006],[-.018,.09,.094,-.01],[.019,.089,.096,-.014],[.052,.089,.10,-.021],[.091,.085,.094,-.024],[.121,.068,.075,-.023],[.146,.033,.037,-.024],[.153,.001,.001,-.024]];
export function humanHeadGeometry(face={},segments=96,rows=64){const f=cleanFace(face).shape,positions=[],uv=[],indices=[];
 for(let row=0;row<=rows;row++){const v=row/rows,y0=rings[0][0]+v*(rings.at(-1)[0]-rings[0][0]);let r=1;while(r<rings.length-1&&rings[r][0]<y0)r++;const a=rings[r-1],b=rings[r],t=(y0-a[0])/(b[0]-a[0]),mix=i=>{const p0=rings[Math.max(0,r-2)][i],p1=a[i],p2=b[i],p3=rings[Math.min(rings.length-1,r+1)][i];return .5*((2*p1)+(-p0+p2)*t+(2*p0-5*p1+4*p2-p3)*t*t+(-p0+3*p1-3*p2+p3)*t*t*t);},rx=mix(1),rz=mix(2),offset=mix(3);for(let j=0;j<=segments;j++){const u=j/segments,angle=(u-.5)*Math.PI*2,s=Math.sin(angle),c=Math.cos(angle),front=Math.max(0,c)**8,jaw=gauss(y0+.10,.044),cheek=gauss(y0+.014,.039);let x=s*rx*f.width*(1+(f.jaw-1)*jaw+(f.cheek-1)*cheek*.65),y=y0+(f.chin-1)*Math.min(0,y0+.065),z=(c*rz+offset)*f.depth;
  const eyes=.031*f.eyes;z+=front*(.012*gauss(x,.013)*gauss(y0-.014,.042)+.024*f.nose*gauss(x,.015)*gauss(y0+.025,.022)+.008*gauss(Math.abs(x)-.015,.008)*gauss(y0+.037,.01)-.011*gauss(Math.abs(x)-eyes,.014)*gauss(y0-.022,.011)+.007*gauss(Math.abs(x)-eyes,.022)*gauss(y0-.044,.008)+.009*gauss(Math.abs(x)-.051,.02)*gauss(y0+.017,.02)+.007*gauss(x,.034)*gauss(y0+.077,.007)+.005*gauss(x,.027)*gauss(y0+.087,.006)-.003*gauss(x,.021)*gauss(y0+.082,.002)+.01*gauss(x,.039)*gauss(y0+.117,.017));positions.push(x,y,z);uv.push(.5+(u-.5)/(1+(f.eyes-1)*gauss(y0-.022,.03)*front),v);if(row<rows&&j<segments){const p=row*(segments+1)+j;indices.push(p,p+1,p+segments+1,p+1,p+segments+2,p+segments+1);}}
 }
 const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometry.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));geometry.setIndex(indices);geometry.computeVertexNormals();return geometry;
}
function skinTexture(color,seed=10){const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const ctx=canvas.getContext('2d');ctx.fillStyle=color;ctx.fillRect(0,0,128,128);const pixels=ctx.getImageData(0,0,128,128),base=new THREE.Color(color),rgb=[base.r,base.g,base.b].map(n=>THREE.ColorManagement.workingColorSpace===THREE.LinearSRGBColorSpace?Math.round((n<=.0031308?n*12.92:1.055*n**(1/2.4)-.055)*255):n*255);let random=seed+1;for(let y=0;y<128;y++)for(let x=0;x<128;x++){random=(random*1664525+1013904223)>>>0;const noise=((random&255)/255-.5)*5,u=x/127,v=1-y/127,angle=(u-.5)*Math.PI*2,front=Math.max(0,Math.cos(angle))**10,xx=Math.sin(angle)*.092,yy=-.142+v*.295;const cheek=gauss(Math.abs(xx)-.046,.029)*gauss(yy+.034,.038)*front,lips=gauss(xx,.032)*gauss(yy+.082,.007)*front,beard=(gauss(yy+.104,.03)+gauss(Math.abs(xx)-.06,.024)*gauss(yy+.074,.04))*.14*front;const i=(y*128+x)*4;pixels.data[i]=rgb[0]+noise+cheek*5-lips*26-beard*42;pixels.data[i+1]=rgb[1]+noise-cheek*5-lips*33-beard*37;pixels.data[i+2]=rgb[2]+noise-cheek*4-lips*22-beard*26;pixels.data[i+3]=255;}ctx.putImageData(pixels,0,0);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture;}
function poreTexture(){const c=document.createElement('canvas');c.width=c.height=128;const cx=c.getContext('2d'),im=cx.createImageData(128,128);let seed=39;for(let i=0;i<im.data.length;i+=4){seed=(1664525*seed+1013904223)>>>0;const n=115+(seed&31);im.data[i]=im.data[i+1]=im.data[i+2]=n;im.data[i+3]=255;}cx.putImageData(im,0,0);const tex=new THREE.CanvasTexture(c);tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.repeat.set(4,3);return tex;}
function irisTexture(seed){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');x.fillStyle='#382518';x.fillRect(0,0,128,128);for(let i=0;i<220;i++){const a=i/220*Math.PI*2;x.strokeStyle=i%3?'#756443':'#302821';x.beginPath();x.moveTo(64+Math.cos(a)*17,64+Math.sin(a)*17);x.lineTo(64+Math.cos(a)*(49+(i*seed%10)),64+Math.sin(a)*(49+(i*seed%10)));x.stroke();}x.fillStyle='#07090a';x.beginPath();x.arc(64,64,23,0,Math.PI*2);x.fill();const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function oval(parent,material,x,y,z,sx,sy,sz,segments=24){const mesh=new THREE.Mesh(new THREE.SphereGeometry(1,segments,16),material);mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);mesh.castShadow=true;parent.add(mesh);return mesh;}
function brow(parent,material,sign,width){const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(sign*.016*width,.046,.081),new THREE.Vector3(sign*.033*width,.050,.084),new THREE.Vector3(sign*.051*width,.044,.077)]);const mesh=new THREE.Mesh(new THREE.TubeGeometry(curve,12,.0028,5,false),material);parent.add(mesh);}
export function createHumanHead(profile={},number=10){const config=cleanFace(profile.face);if(config.mode==='sculpt')return createSculptedHead(profile.face?.enabled===false?{...profile,face:{}}:profile,number);const group=new THREE.Group(),near=new THREE.Group(),far=new THREE.Group();group.add(near,far);far.visible=false;const skinColor=profile.skin||'#c89572',skinMap=skinTexture(skinColor,number),pore=poreTexture(),skin=new THREE.MeshPhysicalMaterial({color:0xffffff,map:skinMap,bumpMap:pore,bumpScale:.00045,roughness:.65,clearcoat:.035,clearcoatRoughness:.7}),solidSkin=new THREE.MeshStandardMaterial({color:skinColor,roughness:.65}),hair=new THREE.MeshStandardMaterial({color:profile.hair||'#211a15',roughness:.9}),sclera=new THREE.MeshPhysicalMaterial({color:0xdad7ca,roughness:.28,clearcoat:.4}),iris=new THREE.MeshStandardMaterial({color:0xffffff,map:irisTexture(number+3),roughness:.32});
 const geometry=humanHeadGeometry(config),jaw=geometry.attributes.position.clone();for(let i=0;i<jaw.count;i++){const w=THREE.MathUtils.clamp((-jaw.getY(i)-.06)/.08,0,1);jaw.setY(i,jaw.getY(i)-w*.005);jaw.setZ(i,jaw.getZ(i)-w*.001);}geometry.morphAttributes.position=[jaw];const face=new THREE.Mesh(geometry,skin);face.castShadow=face.receiveShadow=true;near.add(face);const low=new THREE.Mesh(humanHeadGeometry(config,32,24),skin);low.castShadow=true;far.add(low);const eyes=[],customPhoto=!!(config.enabled&&profile.faceTexture),photo=customPhoto||profile.hairStyle!=='bald';if(photo){iris.map.dispose();iris.dispose();sclera.dispose();}
 for(const sign of [-1,1]){for(const parent of photo?[]:[near,far]){const ear=oval(parent,solidSkin,sign*.094*config.shape.width,-.014,-.01,.015,.031,.014,16);if(parent===near){oval(parent,new THREE.MeshStandardMaterial({color:new THREE.Color(skinColor).multiplyScalar(.75),roughness:.8}),sign*.098*config.shape.width,-.014,.001,.006,.018,.005,12);}}
  if(!photo){const x=sign*.031*config.shape.eyes,z=.080;const eye=oval(near,sclera,x,.022,z,.013,.006,.009);eyes.push(eye);oval(near,iris,x,.022,z+.008,.005,.005,.0015);brow(near,hair,sign,config.shape.eyes);const lidMat=solidSkin;for(const upper of [true,false]){const points=[];for(let i=0;i<=12;i++){const a=i/12*Math.PI;points.push(new THREE.Vector3(x+Math.cos(a)*.013,.022+Math.sin(a)*(upper?.006:-.005),z+.006));}near.add(new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),16,.0017,5,false),lidMat));}}
 }
 if(profile.hairStyle!=='bald'&&(!customPhoto||!config.photoHair)){for(const parent of [near,far]){const g=hairGeometry(config,profile.hairStyle,parent===near?64:24),cap=new THREE.Mesh(g,hair);cap.castShadow=true;parent.add(cap);}}
 group.scale.set(.96,.84,.94);let disposed=false,resolve;const ready=new Promise(r=>resolve=r);if(customPhoto){new THREE.TextureLoader().load(profile.faceTexture,texture=>{if(disposed){texture.dispose();resolve();return;}texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=4;skinMap.dispose();skin.map=texture;skin.needsUpdate=true;resolve();},undefined,()=>resolve());}else if(photo){defaultFaceTexture().then(({map,skin:base})=>{if(!disposed){skinMap.dispose();skin.map=map;const b=new THREE.Color(base),target=new THREE.Color(skinColor);skin.color.setRGB(target.r/b.r,target.g/b.g,target.b/b.b);skin.needsUpdate=true;hair.map=map;const hb=new THREE.Color('#211a15'),ht=new THREE.Color(profile.hair||'#211a15');hair.color.setRGB(ht.r/hb.r,ht.g/hb.g,ht.b/hb.b);hair.needsUpdate=true;}resolve();}).catch(()=>resolve());}else resolve();return {group,near,far,face,eyes,ready,dispose:()=>{disposed=true;}};
}

function hairGeometry(config,style,segments){const rows=24,source=humanHeadGeometry(config,segments,64),p=source.attributes.position,positions=[],uv=[],indices=[];for(let r=0;r<=rows;r++)for(let i=0;i<=segments;i++){const u=i/segments,t=r/rows,front=Math.max(0,Math.cos((u-.5)*Math.PI*2)),hairline=-.055+.158*Math.sqrt(front),yy=hairline+(.153-hairline)*t,v=(yy+.142)/.295,f=v*64,a=Math.min(63,Math.floor(f)),b=f-a,k=a*(segments+1)+i,above=k+segments+1,lerp=key=>p[key](k)*(1-b)+p[key](above)*b,xx=lerp('getX'),zz=lerp('getZ'),strand=.00055*Math.sin(u*520+t*27),lift=(style==='crop'?.001:.0035)+strand;positions.push(xx*1.026,lerp('getY')+lift+(style==='crest'?.016*Math.exp(-((xx/.023)**2))*t:0),zz+(zz+.02)*.027);uv.push(u,v);if(r<rows&&i<segments){const k=r*(segments+1)+i;indices.push(k,k+1,k+segments+1,k+1,k+segments+2,k+segments+1);}}source.dispose();const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();return g;}
