// Generated by tools/update-kleague.mjs from K League's current club lists.
export const ROSTER_DATE="2026-09-28";
export const ROSTER_SOURCES={
  "bucheon": {
    "url": "https://www.kleague.com/club/club.do?teamId=K26",
    "asOf": "2026.09.28"
  },
  "ulsan": {
    "url": "https://www.kleague.com/club/club.do?teamId=K01",
    "asOf": "2026.09.28"
  },
  "seoul": {
    "url": "https://www.kleague.com/club/club.do?teamId=K09",
    "asOf": "2026.09.28"
  },
  "pohang": {
    "url": "https://www.kleague.com/club/club.do?teamId=K03",
    "asOf": "2026.09.28"
  },
  "jeonbuk": {
    "url": "https://www.kleague.com/club/club.do?teamId=K05",
    "asOf": "2026.09.28"
  },
  "incheon": {
    "url": "https://www.kleague.com/club/club.do?teamId=K18",
    "asOf": "2026.09.28"
  },
  "daejeon": {
    "url": "https://www.kleague.com/club/club.do?teamId=K10",
    "asOf": "2026.09.28"
  },
  "jeju": {
    "url": "https://www.kleague.com/club/club.do?teamId=K04",
    "asOf": "2026.09.28"
  },
  "gangwon": {
    "url": "https://www.kleague.com/club/club.do?teamId=K21",
    "asOf": "2026.09.28"
  },
  "anyang": {
    "url": "https://www.kleague.com/club/club.do?teamId=K27",
    "asOf": "2026.09.28"
  },
  "gwangju": {
    "url": "https://www.kleague.com/club/club.do?teamId=K22",
    "asOf": "2026.09.28"
  },
  "gimcheon": {
    "url": "https://www.kleague.com/club/club.do?teamId=K35",
    "asOf": "2026.09.28"
  }
};
export const KLEAGUE_ROSTERS={
  "bucheon": [
    {
      "id": "20230333",
      "name": "가브리엘",
      "number": 63,
      "role": "FWD"
    },
    {
      "id": "20220353",
      "name": "갈레고",
      "number": 11,
      "role": "FWD"
    },
    {
      "id": "20210184",
      "name": "강재우",
      "number": 88,
      "role": "DEF"
    },
    {
      "id": "20260383",
      "name": "구스타보",
      "number": 99,
      "role": "FWD"
    },
    {
      "id": "20220050",
      "name": "김규민",
      "number": 17,
      "role": "FWD"
    },
    {
      "id": "20240180",
      "name": "김동현",
      "number": 24,
      "role": "MID"
    },
    {
      "id": "20200048",
      "name": "김민준",
      "number": 13,
      "role": "FWD"
    },
    {
      "id": "20190194",
      "name": "김상준",
      "number": 16,
      "role": "MID"
    },
    {
      "id": "20260112",
      "name": "김승빈",
      "number": 71,
      "role": "FWD"
    },
    {
      "id": "20220242",
      "name": "김종민",
      "number": 2,
      "role": "DEF"
    },
    {
      "id": "20150097",
      "name": "김종우",
      "number": 14,
      "role": "MID"
    },
    {
      "id": "20230139",
      "name": "김현엽",
      "number": 21,
      "role": "GK"
    },
    {
      "id": "20160010",
      "name": "김형근",
      "number": 1,
      "role": "GK"
    },
    {
      "id": "20230104",
      "name": "바사니",
      "number": 10,
      "role": "FWD"
    },
    {
      "id": "20190048",
      "name": "박정인",
      "number": 9,
      "role": "FWD"
    },
    {
      "id": "20140203",
      "name": "백동규",
      "number": 29,
      "role": "DEF"
    },
    {
      "id": "20250152",
      "name": "성신",
      "number": 19,
      "role": "MID"
    },
    {
      "id": "20260341",
      "name": "성예건",
      "number": 4,
      "role": "MID"
    },
    {
      "id": "20190161",
      "name": "신재원",
      "number": 77,
      "role": "DEF"
    },
    {
      "id": "20160130",
      "name": "안태현",
      "number": 26,
      "role": "DEF"
    },
    {
      "id": "20260110",
      "name": "어담",
      "number": 27,
      "role": "FWD"
    },
    {
      "id": "20170200",
      "name": "여봉훈",
      "number": 25,
      "role": "MID"
    },
    {
      "id": "20220051",
      "name": "유승현",
      "number": 66,
      "role": "DEF"
    },
    {
      "id": "20100079",
      "name": "윤빛가람",
      "number": 8,
      "role": "MID"
    },
    {
      "id": "20230045",
      "name": "이상혁",
      "number": 5,
      "role": "DEF"
    },
    {
      "id": "20250191",
      "name": "이상현",
      "number": 31,
      "role": "GK"
    },
    {
      "id": "20250310",
      "name": "이예찬",
      "number": 44,
      "role": "DEF"
    },
    {
      "id": "20210159",
      "name": "이의형",
      "number": 18,
      "role": "FWD"
    },
    {
      "id": "20230046",
      "name": "이재원",
      "number": 93,
      "role": "DEF"
    },
    {
      "id": "20200142",
      "name": "정호진",
      "number": 6,
      "role": "DEF"
    },
    {
      "id": "20130340",
      "name": "조성준",
      "number": 83,
      "role": "DEF"
    },
    {
      "id": "20230141",
      "name": "카즈",
      "number": 23,
      "role": "MID"
    },
    {
      "id": "20250150",
      "name": "티아깅요",
      "number": 7,
      "role": "DEF"
    },
    {
      "id": "20260109",
      "name": "패트릭",
      "number": 3,
      "role": "DEF"
    },
    {
      "id": "20100134",
      "name": "한지호",
      "number": 22,
      "role": "FWD"
    },
    {
      "id": "20250151",
      "name": "홍기욱",
      "number": 33,
      "role": "MID"
    },
    {
      "id": "20210174",
      "name": "홍성욱",
      "number": 20,
      "role": "DEF"
    }
  ],
  "seoul": [
    {
      "id": "20140038",
      "name": "강현무",
      "number": 31,
      "role": "GK"
    },
    {
      "id": "20260047",
      "name": "고필관",
      "number": 23,
      "role": "MID"
    },
    {
      "id": "20200301",
      "name": "구성윤",
      "number": 25,
      "role": "GK"
    },
    {
      "id": "20260381",
      "name": "김강준",
      "number": 77,
      "role": "DEF"
    },
    {
      "id": "20260377",
      "name": "김민준",
      "number": 24,
      "role": "MID"
    },
    {
      "id": "20250060",
      "name": "김지원",
      "number": 36,
      "role": "DEF"
    },
    {
      "id": "20170185",
      "name": "김진수",
      "number": 22,
      "role": "DEF"
    },
    {
      "id": "20260048",
      "name": "로스",
      "number": 37,
      "role": "DEF"
    },
    {
      "id": "20170229",
      "name": "문선민",
      "number": 27,
      "role": "FWD"
    },
    {
      "id": "20250081",
      "name": "바또",
      "number": 99,
      "role": "FWD"
    },
    {
      "id": "20260045",
      "name": "바베츠",
      "number": 6,
      "role": "MID"
    },
    {
      "id": "20220163",
      "name": "박성훈",
      "number": 40,
      "role": "DEF"
    },
    {
      "id": "20180233",
      "name": "박수일",
      "number": 66,
      "role": "DEF"
    },
    {
      "id": "20220164",
      "name": "박장한결",
      "number": 88,
      "role": "MID"
    },
    {
      "id": "20260049",
      "name": "손정범",
      "number": 42,
      "role": "MID"
    },
    {
      "id": "20260380",
      "name": "신지섭",
      "number": 73,
      "role": "DEF"
    },
    {
      "id": "20240179",
      "name": "안데르손",
      "number": 10,
      "role": "FWD"
    },
    {
      "id": "20230088",
      "name": "안재민",
      "number": 17,
      "role": "DEF"
    },
    {
      "id": "20240324",
      "name": "야잔",
      "number": 5,
      "role": "DEF"
    },
    {
      "id": "20250082",
      "name": "윤기욱",
      "number": 71,
      "role": "GK"
    },
    {
      "id": "20180008",
      "name": "이상민",
      "number": 4,
      "role": "DEF"
    },
    {
      "id": "20260379",
      "name": "이서현",
      "number": 49,
      "role": "DEF"
    },
    {
      "id": "20170052",
      "name": "이승모",
      "number": 8,
      "role": "MID"
    },
    {
      "id": "20160107",
      "name": "이한도",
      "number": 20,
      "role": "DEF"
    },
    {
      "id": "20220169",
      "name": "임준섭",
      "number": 1,
      "role": "GK"
    },
    {
      "id": "20160099",
      "name": "정승원",
      "number": 7,
      "role": "MID"
    },
    {
      "id": "20260376",
      "name": "정하원",
      "number": 21,
      "role": "MID"
    },
    {
      "id": "20260349",
      "name": "정현우",
      "number": 14,
      "role": "FWD"
    },
    {
      "id": "20260378",
      "name": "정현웅",
      "number": 47,
      "role": "FWD"
    },
    {
      "id": "20180073",
      "name": "조영욱",
      "number": 18,
      "role": "FWD"
    },
    {
      "id": "20230034",
      "name": "천성훈",
      "number": 19,
      "role": "FWD"
    },
    {
      "id": "20200041",
      "name": "최준",
      "number": 16,
      "role": "DEF"
    },
    {
      "id": "20250331",
      "name": "클리말라",
      "number": 9,
      "role": "FWD"
    },
    {
      "id": "20230093",
      "name": "황도윤",
      "number": 41,
      "role": "MID"
    },
    {
      "id": "20240254",
      "name": "후이즈",
      "number": 11,
      "role": "FWD"
    }
  ],
  "ulsan": [
    {
      "id": "20140033",
      "name": "강상우",
      "number": 17,
      "role": "DEF"
    },
    {
      "id": "20250362",
      "name": "김세형",
      "number": 25,
      "role": "GK"
    },
    {
      "id": "20220188",
      "name": "김영권",
      "number": 19,
      "role": "DEF"
    },
    {
      "id": "20250023",
      "name": "류성민",
      "number": 13,
      "role": "GK"
    },
    {
      "id": "20170095",
      "name": "말컹",
      "number": 9,
      "role": "FWD"
    },
    {
      "id": "20170029",
      "name": "문정인",
      "number": 23,
      "role": "GK"
    },
    {
      "id": "20150159",
      "name": "박용우",
      "number": 38,
      "role": "MID"
    },
    {
      "id": "20240330",
      "name": "박우진",
      "number": 16,
      "role": "MID"
    },
    {
      "id": "20250044",
      "name": "백인우",
      "number": 72,
      "role": "MID"
    },
    {
      "id": "20260244",
      "name": "벤지",
      "number": 91,
      "role": "FWD"
    },
    {
      "id": "20230108",
      "name": "보야니치",
      "number": 6,
      "role": "MID"
    },
    {
      "id": "20230140",
      "name": "서명관",
      "number": 4,
      "role": "DEF"
    },
    {
      "id": "20140066",
      "name": "심상민",
      "number": 77,
      "role": "DEF"
    },
    {
      "id": "20230315",
      "name": "야고",
      "number": 99,
      "role": "FWD"
    },
    {
      "id": "20250292",
      "name": "에릭",
      "number": 11,
      "role": "FWD"
    },
    {
      "id": "20170051",
      "name": "윤종규",
      "number": 2,
      "role": "DEF"
    },
    {
      "id": "20150050",
      "name": "이규성",
      "number": 24,
      "role": "MID"
    },
    {
      "id": "20180088",
      "name": "이동경",
      "number": 10,
      "role": "MID"
    },
    {
      "id": "20180105",
      "name": "이재익",
      "number": 28,
      "role": "DEF"
    },
    {
      "id": "20180296",
      "name": "이진현",
      "number": 14,
      "role": "MID"
    },
    {
      "id": "20190171",
      "name": "이희균",
      "number": 8,
      "role": "MID"
    },
    {
      "id": "20230044",
      "name": "장시영",
      "number": 33,
      "role": "MID"
    },
    {
      "id": "20250042",
      "name": "정성빈",
      "number": 3,
      "role": "DEF"
    },
    {
      "id": "20150109",
      "name": "정승현",
      "number": 15,
      "role": "DEF"
    },
    {
      "id": "20240051",
      "name": "정재상",
      "number": 20,
      "role": "FWD"
    },
    {
      "id": "20260030",
      "name": "조민서",
      "number": 43,
      "role": "MID"
    },
    {
      "id": "20130156",
      "name": "조현우",
      "number": 21,
      "role": "GK"
    },
    {
      "id": "20200055",
      "name": "조현택",
      "number": 26,
      "role": "DEF"
    },
    {
      "id": "20240107",
      "name": "최석현",
      "number": 96,
      "role": "DEF"
    },
    {
      "id": "20260028",
      "name": "최주호",
      "number": 1,
      "role": "GK"
    },
    {
      "id": "20250087",
      "name": "토마스",
      "number": 55,
      "role": "DEF"
    },
    {
      "id": "20250326",
      "name": "트로야크",
      "number": 66,
      "role": "DEF"
    },
    {
      "id": "20250194",
      "name": "페드링요",
      "number": 27,
      "role": "MID"
    },
    {
      "id": "20200099",
      "name": "허율",
      "number": 18,
      "role": "FWD"
    },
    {
      "id": "20150130",
      "name": "황병근",
      "number": 31,
      "role": "GK"
    }
  ],
  "jeonbuk": [
    {
      "id": "20250353",
      "name": "감보아",
      "number": 16,
      "role": "MID"
    },
    {
      "id": "20220276",
      "name": "강상윤",
      "number": 13,
      "role": "MID"
    },
    {
      "id": "20250077",
      "name": "강현종",
      "number": 39,
      "role": "FWD"
    },
    {
      "id": "20230256",
      "name": "공시현",
      "number": 29,
      "role": "GK"
    },
    {
      "id": "20260064",
      "name": "곽희벽",
      "number": 80,
      "role": "DEF"
    },
    {
      "id": "20260387",
      "name": "구교빈",
      "number": 61,
      "role": "MID"
    },
    {
      "id": "20260224",
      "name": "기티스",
      "number": 81,
      "role": "FWD"
    },
    {
      "id": "20250078",
      "name": "김민재",
      "number": 73,
      "role": "MID"
    },
    {
      "id": "20250291",
      "name": "김수형",
      "number": 74,
      "role": "DEF"
    },
    {
      "id": "20180212",
      "name": "김승섭",
      "number": 11,
      "role": "FWD"
    },
    {
      "id": "20140143",
      "name": "김영빈",
      "number": 2,
      "role": "DEF"
    },
    {
      "id": "20260058",
      "name": "김주형",
      "number": 44,
      "role": "DEF"
    },
    {
      "id": "20250050",
      "name": "김준영",
      "number": 22,
      "role": "DEF"
    },
    {
      "id": "20150052",
      "name": "김진규",
      "number": 97,
      "role": "MID"
    },
    {
      "id": "20230077",
      "name": "김창훈",
      "number": 79,
      "role": "FWD"
    },
    {
      "id": "20260388",
      "name": "김태영",
      "number": 62,
      "role": "DEF"
    },
    {
      "id": "20180185",
      "name": "김태현",
      "number": 77,
      "role": "DEF"
    },
    {
      "id": "20100052",
      "name": "김태환",
      "number": 23,
      "role": "DEF"
    },
    {
      "id": "20230250",
      "name": "김하준",
      "number": 15,
      "role": "DEF"
    },
    {
      "id": "20260374",
      "name": "도도",
      "number": 30,
      "role": "FWD"
    },
    {
      "id": "20240239",
      "name": "마지강",
      "number": 24,
      "role": "DEF"
    },
    {
      "id": "20190084",
      "name": "맹성웅",
      "number": 6,
      "role": "MID"
    },
    {
      "id": "20230224",
      "name": "모따",
      "number": 99,
      "role": "FWD"
    },
    {
      "id": "20260056",
      "name": "문준혁",
      "number": 26,
      "role": "MID"
    },
    {
      "id": "20240241",
      "name": "박주영",
      "number": 19,
      "role": "FWD"
    },
    {
      "id": "20220076",
      "name": "박준범",
      "number": 37,
      "role": "FWD"
    },
    {
      "id": "20130142",
      "name": "박지수",
      "number": 5,
      "role": "DEF"
    },
    {
      "id": "20260148",
      "name": "박현민",
      "number": 70,
      "role": "MID"
    },
    {
      "id": "20240274",
      "name": "서정혁",
      "number": 39,
      "role": "DEF"
    },
    {
      "id": "20180025",
      "name": "송범근",
      "number": 31,
      "role": "GK"
    },
    {
      "id": "20250317",
      "name": "아나스모",
      "number": 42,
      "role": "FWD"
    },
    {
      "id": "20260057",
      "name": "안태훈",
      "number": 40,
      "role": "FWD"
    },
    {
      "id": "20220177",
      "name": "엄승민",
      "number": 34,
      "role": "FWD"
    },
    {
      "id": "20160157",
      "name": "연제운",
      "number": 3,
      "role": "DEF"
    },
    {
      "id": "20260020",
      "name": "우현수",
      "number": 42,
      "role": "MID"
    },
    {
      "id": "20250281",
      "name": "윤주영",
      "number": 47,
      "role": "DEF"
    },
    {
      "id": "20250051",
      "name": "윤현석",
      "number": 88,
      "role": "MID"
    },
    {
      "id": "20260059",
      "name": "이건희",
      "number": 47,
      "role": "MID"
    },
    {
      "id": "20170121",
      "name": "이동준",
      "number": 7,
      "role": "FWD"
    },
    {
      "id": "20250159",
      "name": "이상명",
      "number": 24,
      "role": "DEF"
    },
    {
      "id": "20220042",
      "name": "이승우",
      "number": 10,
      "role": "FWD"
    },
    {
      "id": "20150104",
      "name": "이영재",
      "number": 28,
      "role": "MID"
    },
    {
      "id": "20220077",
      "name": "이우연",
      "number": 40,
      "role": "DEF"
    },
    {
      "id": "20190057",
      "name": "이주현",
      "number": 1,
      "role": "GK"
    },
    {
      "id": "20260365",
      "name": "이탈로",
      "number": 95,
      "role": "FWD"
    },
    {
      "id": "20250282",
      "name": "이한결",
      "number": 51,
      "role": "GK"
    },
    {
      "id": "20250330",
      "name": "임준휘",
      "number": 98,
      "role": "FWD"
    },
    {
      "id": "20240042",
      "name": "장남웅",
      "number": 36,
      "role": "MID"
    },
    {
      "id": "20220300",
      "name": "전지완",
      "number": 71,
      "role": "GK"
    },
    {
      "id": "20260060",
      "name": "정대영",
      "number": 91,
      "role": "GK"
    },
    {
      "id": "20250083",
      "name": "정상운",
      "number": 90,
      "role": "FWD"
    },
    {
      "id": "20220174",
      "name": "조위제",
      "number": 4,
      "role": "DEF"
    },
    {
      "id": "20230029",
      "name": "최우진",
      "number": 66,
      "role": "DEF"
    },
    {
      "id": "20250154",
      "name": "최진웅",
      "number": 55,
      "role": "DEF"
    },
    {
      "id": "20250335",
      "name": "츄마시",
      "number": 21,
      "role": "FWD"
    },
    {
      "id": "20250061",
      "name": "콤파뇨",
      "number": 96,
      "role": "FWD"
    },
    {
      "id": "20220244",
      "name": "티아고",
      "number": 9,
      "role": "FWD"
    },
    {
      "id": "20240275",
      "name": "한석진",
      "number": 33,
      "role": "FWD"
    },
    {
      "id": "20260389",
      "name": "한승민",
      "number": 63,
      "role": "MID"
    },
    {
      "id": "20260385",
      "name": "한재빈",
      "number": 37,
      "role": "DEF"
    },
    {
      "id": "20250079",
      "name": "황승준",
      "number": 27,
      "role": "DEF"
    },
    {
      "id": "20250226",
      "name": "황정구",
      "number": 50,
      "role": "DEF"
    }
  ],
  "pohang": [
    {
      "id": "20250015",
      "name": "강민준",
      "number": 13,
      "role": "DEF"
    },
    {
      "id": "20240061",
      "name": "강성혁",
      "number": 41,
      "role": "GK"
    },
    {
      "id": "20240298",
      "name": "권능",
      "number": 91,
      "role": "GK"
    },
    {
      "id": "20060073",
      "name": "기성용",
      "number": 40,
      "role": "MID"
    },
    {
      "id": "20260366",
      "name": "김광원",
      "number": 22,
      "role": "FWD"
    },
    {
      "id": "20240063",
      "name": "김동진",
      "number": 16,
      "role": "MID"
    },
    {
      "id": "20260022",
      "name": "김범준",
      "number": 26,
      "role": "MID"
    },
    {
      "id": "20230159",
      "name": "김승호",
      "number": 8,
      "role": "MID"
    },
    {
      "id": "20180215",
      "name": "김예성",
      "number": 3,
      "role": "DEF"
    },
    {
      "id": "20260023",
      "name": "김용학",
      "number": 30,
      "role": "FWD"
    },
    {
      "id": "20260026",
      "name": "김호진",
      "number": 36,
      "role": "DEF"
    },
    {
      "id": "20260024",
      "name": "니시야 켄토",
      "number": 31,
      "role": "MID"
    },
    {
      "id": "20200146",
      "name": "박찬용",
      "number": 20,
      "role": "DEF"
    },
    {
      "id": "20250019",
      "name": "백승원",
      "number": 34,
      "role": "FWD"
    },
    {
      "id": "20060066",
      "name": "신광훈",
      "number": 17,
      "role": "DEF"
    },
    {
      "id": "20200043",
      "name": "안재준",
      "number": 9,
      "role": "FWD"
    },
    {
      "id": "20210182",
      "name": "어정원",
      "number": 2,
      "role": "DEF"
    },
    {
      "id": "20150253",
      "name": "완델손",
      "number": 77,
      "role": "DEF"
    },
    {
      "id": "20180204",
      "name": "원기종",
      "number": 7,
      "role": "FWD"
    },
    {
      "id": "20260027",
      "name": "윤대근",
      "number": 55,
      "role": "DEF"
    },
    {
      "id": "20130151",
      "name": "윤평국",
      "number": 1,
      "role": "GK"
    },
    {
      "id": "20250309",
      "name": "이수아",
      "number": 47,
      "role": "MID"
    },
    {
      "id": "20250021",
      "name": "이창우",
      "number": 14,
      "role": "DEF"
    },
    {
      "id": "20150067",
      "name": "전민광",
      "number": 4,
      "role": "DEF"
    },
    {
      "id": "20200030",
      "name": "정한민",
      "number": 37,
      "role": "FWD"
    },
    {
      "id": "20230225",
      "name": "조르지",
      "number": 25,
      "role": "FWD"
    },
    {
      "id": "20250022",
      "name": "조상혁",
      "number": 18,
      "role": "FWD"
    },
    {
      "id": "20180056",
      "name": "조성욱",
      "number": 33,
      "role": "DEF"
    },
    {
      "id": "20260025",
      "name": "조영준",
      "number": 32,
      "role": "DEF"
    },
    {
      "id": "20230148",
      "name": "주닝요",
      "number": 11,
      "role": "FWD"
    },
    {
      "id": "20240233",
      "name": "진시우",
      "number": 5,
      "role": "DEF"
    },
    {
      "id": "20260021",
      "name": "트란지스카",
      "number": 10,
      "role": "FWD"
    },
    {
      "id": "20240277",
      "name": "홍성민",
      "number": 29,
      "role": "GK"
    },
    {
      "id": "20240062",
      "name": "황서웅",
      "number": 70,
      "role": "MID"
    },
    {
      "id": "20160079",
      "name": "황인재",
      "number": 21,
      "role": "GK"
    },
    {
      "id": "20220334",
      "name": "황재환",
      "number": 12,
      "role": "MID"
    }
  ],
  "incheon": [
    {
      "id": "20240105",
      "name": "강도욱",
      "number": 24,
      "role": "MID"
    },
    {
      "id": "20250190",
      "name": "강민성",
      "number": 29,
      "role": "FWD"
    },
    {
      "id": "20240286",
      "name": "강영훈",
      "number": 34,
      "role": "DEF"
    },
    {
      "id": "20260164",
      "name": "고정민",
      "number": 22,
      "role": "DEF"
    },
    {
      "id": "20230053",
      "name": "김건희",
      "number": 4,
      "role": "DEF"
    },
    {
      "id": "20190064",
      "name": "김동헌",
      "number": 1,
      "role": "GK"
    },
    {
      "id": "20210305",
      "name": "김명순",
      "number": 39,
      "role": "DEF"
    },
    {
      "id": "20220113",
      "name": "김성민",
      "number": 17,
      "role": "FWD"
    },
    {
      "id": "20170245",
      "name": "김연수",
      "number": 28,
      "role": "DEF"
    },
    {
      "id": "20240108",
      "name": "김영환",
      "number": 30,
      "role": "MID"
    },
    {
      "id": "20240103",
      "name": "김훈",
      "number": 30,
      "role": "MID"
    },
    {
      "id": "20200151",
      "name": "레안드로",
      "number": 70,
      "role": "MID"
    },
    {
      "id": "20180196",
      "name": "무고사",
      "number": 9,
      "role": "FWD"
    },
    {
      "id": "20170147",
      "name": "문지환",
      "number": 6,
      "role": "MID"
    },
    {
      "id": "20250189",
      "name": "박경섭",
      "number": 20,
      "role": "DEF"
    },
    {
      "id": "20230054",
      "name": "박승호",
      "number": 77,
      "role": "FWD"
    },
    {
      "id": "20240102",
      "name": "백민규",
      "number": 14,
      "role": "FWD"
    },
    {
      "id": "20220279",
      "name": "서재민",
      "number": 15,
      "role": "MID"
    },
    {
      "id": "20220087",
      "name": "여승원",
      "number": 27,
      "role": "DEF"
    },
    {
      "id": "20260166",
      "name": "오준엽",
      "number": 55,
      "role": "MID"
    },
    {
      "id": "20180127",
      "name": "오후성",
      "number": 7,
      "role": "FWD"
    },
    {
      "id": "20260167",
      "name": "왕민준",
      "number": 74,
      "role": "GK"
    },
    {
      "id": "20190131",
      "name": "이동률",
      "number": 10,
      "role": "FWD"
    },
    {
      "id": "20120127",
      "name": "이명주",
      "number": 5,
      "role": "MID"
    },
    {
      "id": "20230071",
      "name": "이민혁",
      "number": 26,
      "role": "MID"
    },
    {
      "id": "20170188",
      "name": "이상기",
      "number": 3,
      "role": "DEF"
    },
    {
      "id": "20140059",
      "name": "이주용",
      "number": 32,
      "role": "DEF"
    },
    {
      "id": "20260165",
      "name": "이준섭",
      "number": 24,
      "role": "DEF"
    },
    {
      "id": "20040081",
      "name": "이청용",
      "number": 72,
      "role": "MID"
    },
    {
      "id": "20260161",
      "name": "이케르",
      "number": 8,
      "role": "MID"
    },
    {
      "id": "20140100",
      "name": "이태희",
      "number": 21,
      "role": "GK"
    },
    {
      "id": "20160125",
      "name": "정원진",
      "number": 88,
      "role": "MID"
    },
    {
      "id": "20160094",
      "name": "정치인",
      "number": 23,
      "role": "MID"
    },
    {
      "id": "20210223",
      "name": "제르소",
      "number": 11,
      "role": "MID"
    },
    {
      "id": "20240187",
      "name": "최승구",
      "number": 13,
      "role": "DEF"
    },
    {
      "id": "20260168",
      "name": "페리어",
      "number": 99,
      "role": "FWD"
    },
    {
      "id": "20230031",
      "name": "하동선",
      "number": 34,
      "role": "FWD"
    },
    {
      "id": "20260160",
      "name": "후안 이비자",
      "number": 2,
      "role": "DEF"
    }
  ],
  "gangwon": [
    {
      "id": "20240115",
      "name": "강성윤",
      "number": 71,
      "role": "DEF"
    },
    {
      "id": "20210192",
      "name": "강윤구",
      "number": 14,
      "role": "MID"
    },
    {
      "id": "20230270",
      "name": "강준혁",
      "number": 99,
      "role": "DEF"
    },
    {
      "id": "20230308",
      "name": "강투지",
      "number": 23,
      "role": "DEF"
    },
    {
      "id": "20200066",
      "name": "고영준",
      "number": 11,
      "role": "MID"
    },
    {
      "id": "20260300",
      "name": "고은석",
      "number": 38,
      "role": "DEF"
    },
    {
      "id": "20220065",
      "name": "권석주",
      "number": 37,
      "role": "DEF"
    },
    {
      "id": "20160113",
      "name": "김건희",
      "number": 9,
      "role": "FWD"
    },
    {
      "id": "20160098",
      "name": "김대원",
      "number": 7,
      "role": "FWD"
    },
    {
      "id": "20230203",
      "name": "김도현",
      "number": 27,
      "role": "DEF"
    },
    {
      "id": "20180235",
      "name": "김동현",
      "number": 6,
      "role": "MID"
    },
    {
      "id": "20260373",
      "name": "김슬기",
      "number": 61,
      "role": "MID"
    },
    {
      "id": "20260041",
      "name": "김어진",
      "number": 46,
      "role": "MID"
    },
    {
      "id": "20240099",
      "name": "김유성",
      "number": 41,
      "role": "GK"
    },
    {
      "id": "20250220",
      "name": "김정훈",
      "number": 21,
      "role": "GK"
    },
    {
      "id": "20260301",
      "name": "김태혁",
      "number": 42,
      "role": "MID"
    },
    {
      "id": "20250071",
      "name": "김태환",
      "number": 16,
      "role": "MID"
    },
    {
      "id": "20220063",
      "name": "김해승",
      "number": 43,
      "role": "FWD"
    },
    {
      "id": "20170164",
      "name": "모재현",
      "number": 10,
      "role": "FWD"
    },
    {
      "id": "20210116",
      "name": "박상혁",
      "number": 19,
      "role": "FWD"
    },
    {
      "id": "20250074",
      "name": "박수환",
      "number": 38,
      "role": "DEF"
    },
    {
      "id": "20130134",
      "name": "박청효",
      "number": 1,
      "role": "GK"
    },
    {
      "id": "20240100",
      "name": "박태랑",
      "number": 77,
      "role": "DEF"
    },
    {
      "id": "20180157",
      "name": "박호영",
      "number": 24,
      "role": "DEF"
    },
    {
      "id": "20200077",
      "name": "서민우",
      "number": 4,
      "role": "MID"
    },
    {
      "id": "20250091",
      "name": "성기완",
      "number": 77,
      "role": "FWD"
    },
    {
      "id": "20210112",
      "name": "송준석",
      "number": 34,
      "role": "DEF"
    },
    {
      "id": "20240097",
      "name": "신민하",
      "number": 47,
      "role": "DEF"
    },
    {
      "id": "20260043",
      "name": "아부달라",
      "number": 77,
      "role": "FWD"
    },
    {
      "id": "20260039",
      "name": "여준엽",
      "number": 30,
      "role": "MID"
    },
    {
      "id": "20240128",
      "name": "원희도",
      "number": 40,
      "role": "MID"
    },
    {
      "id": "20250070",
      "name": "유병헌",
      "number": 22,
      "role": "FWD"
    },
    {
      "id": "20210104",
      "name": "이기혁",
      "number": 13,
      "role": "DEF"
    },
    {
      "id": "20230067",
      "name": "이승원",
      "number": 8,
      "role": "MID"
    },
    {
      "id": "20260130",
      "name": "이용재",
      "number": 57,
      "role": "MID"
    },
    {
      "id": "20170182",
      "name": "이유현",
      "number": 97,
      "role": "MID"
    },
    {
      "id": "20260036",
      "name": "이은호",
      "number": 17,
      "role": "FWD"
    },
    {
      "id": "20260040",
      "name": "이정현",
      "number": 45,
      "role": "DEF"
    },
    {
      "id": "20250075",
      "name": "이지호",
      "number": 39,
      "role": "FWD"
    },
    {
      "id": "20260038",
      "name": "이효빈",
      "number": 25,
      "role": "DEF"
    },
    {
      "id": "20250073",
      "name": "정승빈",
      "number": 3,
      "role": "DEF"
    },
    {
      "id": "20250307",
      "name": "정인증",
      "number": 30,
      "role": "FWD"
    },
    {
      "id": "20260348",
      "name": "제시",
      "number": 70,
      "role": "FWD"
    },
    {
      "id": "20230068",
      "name": "조민규",
      "number": 51,
      "role": "GK"
    },
    {
      "id": "20260037",
      "name": "조원우",
      "number": 26,
      "role": "FWD"
    },
    {
      "id": "20240294",
      "name": "진준서",
      "number": 15,
      "role": "FWD"
    },
    {
      "id": "20180057",
      "name": "최병찬",
      "number": 96,
      "role": "FWD"
    },
    {
      "id": "20260317",
      "name": "최재혁",
      "number": 29,
      "role": "DEF"
    },
    {
      "id": "20260042",
      "name": "최지남",
      "number": 74,
      "role": "FWD"
    },
    {
      "id": "20260356",
      "name": "카림",
      "number": 5,
      "role": "DEF"
    },
    {
      "id": "20220064",
      "name": "홍성무",
      "number": 27,
      "role": "MID"
    },
    {
      "id": "20250305",
      "name": "홍진혁",
      "number": 31,
      "role": "GK"
    },
    {
      "id": "20100014",
      "name": "홍철",
      "number": 33,
      "role": "DEF"
    },
    {
      "id": "20250072",
      "name": "황은총",
      "number": 66,
      "role": "MID"
    }
  ],
  "daejeon": [
    {
      "id": "20160037",
      "name": "강윤성",
      "number": 6,
      "role": "DEF"
    },
    {
      "id": "20260314",
      "name": "구훈민",
      "number": 37,
      "role": "FWD"
    },
    {
      "id": "20230014",
      "name": "김경환",
      "number": 16,
      "role": "MID"
    },
    {
      "id": "20230015",
      "name": "김도윤",
      "number": 81,
      "role": "MID"
    },
    {
      "id": "20170122",
      "name": "김문환",
      "number": 33,
      "role": "DEF"
    },
    {
      "id": "20190041",
      "name": "김민덕",
      "number": 3,
      "role": "DEF"
    },
    {
      "id": "20240116",
      "name": "김민수",
      "number": 31,
      "role": "GK"
    },
    {
      "id": "20210176",
      "name": "김봉수",
      "number": 30,
      "role": "MID"
    },
    {
      "id": "20180135",
      "name": "김준범",
      "number": 14,
      "role": "MID"
    },
    {
      "id": "20260312",
      "name": "김지호",
      "number": 28,
      "role": "FWD"
    },
    {
      "id": "20170166",
      "name": "김진야",
      "number": 13,
      "role": "DEF"
    },
    {
      "id": "20220096",
      "name": "김태현",
      "number": 32,
      "role": "DEF"
    },
    {
      "id": "20170040",
      "name": "김현욱",
      "number": 70,
      "role": "MID"
    },
    {
      "id": "20260062",
      "name": "디오고",
      "number": 9,
      "role": "FWD"
    },
    {
      "id": "20230105",
      "name": "루빅손",
      "number": 17,
      "role": "MID"
    },
    {
      "id": "20190209",
      "name": "마사",
      "number": 7,
      "role": "MID"
    },
    {
      "id": "20230185",
      "name": "문건호",
      "number": 29,
      "role": "FWD"
    },
    {
      "id": "20190357",
      "name": "박규현",
      "number": 2,
      "role": "DEF"
    },
    {
      "id": "20260315",
      "name": "박병찬",
      "number": 41,
      "role": "MID"
    },
    {
      "id": "20230326",
      "name": "밥신",
      "number": 8,
      "role": "MID"
    },
    {
      "id": "20200310",
      "name": "서영재1",
      "number": 23,
      "role": "DEF"
    },
    {
      "id": "20190130",
      "name": "서진수",
      "number": 19,
      "role": "FWD"
    },
    {
      "id": "20230048",
      "name": "안톤",
      "number": 98,
      "role": "DEF"
    },
    {
      "id": "20190172",
      "name": "엄원상",
      "number": 11,
      "role": "MID"
    },
    {
      "id": "20100126",
      "name": "오재석",
      "number": 22,
      "role": "DEF"
    },
    {
      "id": "20150151",
      "name": "유강현",
      "number": 99,
      "role": "FWD"
    },
    {
      "id": "20250322",
      "name": "이경태",
      "number": 40,
      "role": "GK"
    },
    {
      "id": "20140041",
      "name": "이명재",
      "number": 16,
      "role": "DEF"
    },
    {
      "id": "20220098",
      "name": "이선호",
      "number": 66,
      "role": "DEF"
    },
    {
      "id": "20170097",
      "name": "이순민",
      "number": 44,
      "role": "MID"
    },
    {
      "id": "20210125",
      "name": "이준서",
      "number": 25,
      "role": "GK"
    },
    {
      "id": "20120148",
      "name": "이창근",
      "number": 1,
      "role": "GK"
    },
    {
      "id": "20180110",
      "name": "이현식",
      "number": 20,
      "role": "MID"
    },
    {
      "id": "20090025",
      "name": "임종은",
      "number": 5,
      "role": "DEF"
    },
    {
      "id": "20160178",
      "name": "정재희",
      "number": 27,
      "role": "FWD"
    },
    {
      "id": "20230239",
      "name": "조성권",
      "number": 4,
      "role": "DEF"
    },
    {
      "id": "20130248",
      "name": "주민규",
      "number": 10,
      "role": "FWD"
    },
    {
      "id": "20250360",
      "name": "주앙 빅토르",
      "number": 77,
      "role": "FWD"
    },
    {
      "id": "20170173",
      "name": "하창래",
      "number": 45,
      "role": "DEF"
    }
  ],
  "jeju": [
    {
      "id": "20260227",
      "name": "강동휘",
      "number": 55,
      "role": "MID"
    },
    {
      "id": "20250100",
      "name": "강효온",
      "number": 63,
      "role": "MID"
    },
    {
      "id": "20260390",
      "name": "구본서",
      "number": 30,
      "role": "MID"
    },
    {
      "id": "20260223",
      "name": "권기민",
      "number": 6,
      "role": "DEF"
    },
    {
      "id": "20160156",
      "name": "김동준",
      "number": 1,
      "role": "GK"
    },
    {
      "id": "20210165",
      "name": "김륜성",
      "number": 40,
      "role": "DEF"
    },
    {
      "id": "20220166",
      "name": "김신진",
      "number": 18,
      "role": "FWD"
    },
    {
      "id": "20240217",
      "name": "김재민",
      "number": 39,
      "role": "MID"
    },
    {
      "id": "20180166",
      "name": "김재우",
      "number": 41,
      "role": "DEF"
    },
    {
      "id": "20250095",
      "name": "김준하",
      "number": 27,
      "role": "MID"
    },
    {
      "id": "20250098",
      "name": "김지운",
      "number": 38,
      "role": "DEF"
    },
    {
      "id": "20260228",
      "name": "네게바",
      "number": 94,
      "role": "FWD"
    },
    {
      "id": "20260226",
      "name": "박민재",
      "number": 47,
      "role": "DEF"
    },
    {
      "id": "20250134",
      "name": "박수빈",
      "number": 33,
      "role": "MID"
    },
    {
      "id": "20180104",
      "name": "박창준",
      "number": 7,
      "role": "FWD"
    },
    {
      "id": "20260221",
      "name": "세레스틴",
      "number": 3,
      "role": "DEF"
    },
    {
      "id": "20210123",
      "name": "신상은",
      "number": 11,
      "role": "FWD"
    },
    {
      "id": "20260359",
      "name": "아이아스",
      "number": 9,
      "role": "FWD"
    },
    {
      "id": "20200070",
      "name": "안찬기",
      "number": 21,
      "role": "GK"
    },
    {
      "id": "20210108",
      "name": "오재혁",
      "number": 14,
      "role": "MID"
    },
    {
      "id": "20200103",
      "name": "유인수",
      "number": 17,
      "role": "DEF"
    },
    {
      "id": "20140115",
      "name": "이창민",
      "number": 8,
      "role": "MID"
    },
    {
      "id": "20240126",
      "name": "이탈로",
      "number": 5,
      "role": "MID"
    },
    {
      "id": "20100101",
      "name": "임창우",
      "number": 23,
      "role": "DEF"
    },
    {
      "id": "20250093",
      "name": "장민규",
      "number": 20,
      "role": "DEF"
    },
    {
      "id": "20120108",
      "name": "정운",
      "number": 13,
      "role": "DEF"
    },
    {
      "id": "20240129",
      "name": "조인정",
      "number": 88,
      "role": "DEF"
    },
    {
      "id": "20250099",
      "name": "주승민",
      "number": 31,
      "role": "GK"
    },
    {
      "id": "20250094",
      "name": "최병욱",
      "number": 24,
      "role": "FWD"
    },
    {
      "id": "20260372",
      "name": "치나리",
      "number": 22,
      "role": "FWD"
    },
    {
      "id": "20260294",
      "name": "토비아스",
      "number": 2,
      "role": "DEF"
    },
    {
      "id": "20210111",
      "name": "허강준",
      "number": 4,
      "role": "DEF"
    },
    {
      "id": "20200104",
      "name": "허자웅",
      "number": 81,
      "role": "GK"
    }
  ],
  "gwangju": [
    {
      "id": "20250047",
      "name": "강희수",
      "number": 42,
      "role": "MID"
    },
    {
      "id": "20260210",
      "name": "공배현",
      "number": 26,
      "role": "DEF"
    },
    {
      "id": "20200029",
      "name": "권성윤",
      "number": 22,
      "role": "FWD"
    },
    {
      "id": "20140102",
      "name": "김경민",
      "number": 1,
      "role": "GK"
    },
    {
      "id": "20250048",
      "name": "김동화",
      "number": 23,
      "role": "GK"
    },
    {
      "id": "20260209",
      "name": "김용혁",
      "number": 24,
      "role": "DEF"
    },
    {
      "id": "20260343",
      "name": "김우진",
      "number": 70,
      "role": "MID"
    },
    {
      "id": "20240332",
      "name": "김윤호",
      "number": 25,
      "role": "FWD"
    },
    {
      "id": "20160126",
      "name": "김종석",
      "number": 21,
      "role": "MID"
    },
    {
      "id": "20220053",
      "name": "김진호",
      "number": 27,
      "role": "DEF"
    },
    {
      "id": "20240236",
      "name": "리영직",
      "number": 37,
      "role": "MID"
    },
    {
      "id": "20240210",
      "name": "문민서",
      "number": 88,
      "role": "MID"
    },
    {
      "id": "20100131",
      "name": "민상기",
      "number": 39,
      "role": "DEF"
    },
    {
      "id": "20260347",
      "name": "바 루아",
      "number": 50,
      "role": "FWD"
    },
    {
      "id": "20260309",
      "name": "박성현",
      "number": 28,
      "role": "MID"
    },
    {
      "id": "20170036",
      "name": "박원재",
      "number": 33,
      "role": "DEF"
    },
    {
      "id": "20260350",
      "name": "반 흐룬스벤",
      "number": 4,
      "role": "DEF"
    },
    {
      "id": "20250200",
      "name": "배진우",
      "number": 66,
      "role": "DEF"
    },
    {
      "id": "20260351",
      "name": "사이토스키",
      "number": 7,
      "role": "FWD"
    },
    {
      "id": "20140134",
      "name": "신창무",
      "number": 40,
      "role": "FWD"
    },
    {
      "id": "20250193",
      "name": "아이데일",
      "number": 18,
      "role": "FWD"
    },
    {
      "id": "20120116",
      "name": "안영규",
      "number": 6,
      "role": "DEF"
    },
    {
      "id": "20240209",
      "name": "안혁주",
      "number": 19,
      "role": "FWD"
    },
    {
      "id": "20260344",
      "name": "오하종",
      "number": 77,
      "role": "MID"
    },
    {
      "id": "20220186",
      "name": "유제호",
      "number": 14,
      "role": "MID"
    },
    {
      "id": "20160072",
      "name": "이민기",
      "number": 3,
      "role": "DEF"
    },
    {
      "id": "20260353",
      "name": "이윤성",
      "number": 71,
      "role": "GK"
    },
    {
      "id": "20190213",
      "name": "임승겸",
      "number": 20,
      "role": "DEF"
    },
    {
      "id": "20230099",
      "name": "장석환",
      "number": 2,
      "role": "DEF"
    },
    {
      "id": "20260211",
      "name": "정규민",
      "number": 79,
      "role": "MID"
    },
    {
      "id": "20230080",
      "name": "정지훈",
      "number": 16,
      "role": "FWD"
    },
    {
      "id": "20120151",
      "name": "주세종",
      "number": 8,
      "role": "MID"
    },
    {
      "id": "20260352",
      "name": "주앙 페드로",
      "number": 17,
      "role": "DEF"
    },
    {
      "id": "20240224",
      "name": "최경록",
      "number": 10,
      "role": "MID"
    },
    {
      "id": "20250366",
      "name": "프리드욘슨",
      "number": 11,
      "role": "FWD"
    },
    {
      "id": "20190114",
      "name": "하승운",
      "number": 9,
      "role": "FWD"
    },
    {
      "id": "20250049",
      "name": "홍용준",
      "number": 99,
      "role": "MID"
    }
  ],
  "anyang": [
    {
      "id": "20260089",
      "name": "강지완",
      "number": 6,
      "role": "MID"
    },
    {
      "id": "20180108",
      "name": "강지훈",
      "number": 17,
      "role": "MID"
    },
    {
      "id": "20130102",
      "name": "권경원",
      "number": 21,
      "role": "DEF"
    },
    {
      "id": "20260093",
      "name": "김강",
      "number": 47,
      "role": "MID"
    },
    {
      "id": "20100031",
      "name": "김다솔",
      "number": 31,
      "role": "GK"
    },
    {
      "id": "20140135",
      "name": "김동진",
      "number": 22,
      "role": "DEF"
    },
    {
      "id": "20160004",
      "name": "김보경",
      "number": 24,
      "role": "MID"
    },
    {
      "id": "20230180",
      "name": "김성동",
      "number": 42,
      "role": "GK"
    },
    {
      "id": "20130101",
      "name": "김영찬",
      "number": 5,
      "role": "DEF"
    },
    {
      "id": "20240084",
      "name": "김운",
      "number": 19,
      "role": "FWD"
    },
    {
      "id": "20260092",
      "name": "김재현",
      "number": 25,
      "role": "DEF"
    },
    {
      "id": "20160073",
      "name": "김정현",
      "number": 8,
      "role": "MID"
    },
    {
      "id": "20190375",
      "name": "김정훈",
      "number": 23,
      "role": "GK"
    },
    {
      "id": "20250084",
      "name": "김지훈",
      "number": 3,
      "role": "DEF"
    },
    {
      "id": "20260358",
      "name": "대니 바커",
      "number": 33,
      "role": "DEF"
    },
    {
      "id": "20240078",
      "name": "마테우스",
      "number": 7,
      "role": "MID"
    },
    {
      "id": "20230138",
      "name": "문성우",
      "number": 14,
      "role": "FWD"
    },
    {
      "id": "20240081",
      "name": "박정훈",
      "number": 15,
      "role": "FWD"
    },
    {
      "id": "20220038",
      "name": "박종현",
      "number": 66,
      "role": "DEF"
    },
    {
      "id": "20260357",
      "name": "블레이즈",
      "number": 28,
      "role": "FWD"
    },
    {
      "id": "20260091",
      "name": "아일톤",
      "number": 11,
      "role": "FWD"
    },
    {
      "id": "20260090",
      "name": "엘쿠라노",
      "number": 9,
      "role": "FWD"
    },
    {
      "id": "20260094",
      "name": "오형준",
      "number": 70,
      "role": "FWD"
    },
    {
      "id": "20250365",
      "name": "유키치",
      "number": 10,
      "role": "FWD"
    },
    {
      "id": "20200084",
      "name": "이진용",
      "number": 26,
      "role": "MID"
    },
    {
      "id": "20130191",
      "name": "이창용",
      "number": 4,
      "role": "DEF"
    },
    {
      "id": "20150080",
      "name": "이태희",
      "number": 32,
      "role": "DEF"
    },
    {
      "id": "20250086",
      "name": "장정우",
      "number": 77,
      "role": "MID"
    },
    {
      "id": "20260382",
      "name": "정민재",
      "number": 1,
      "role": "GK"
    },
    {
      "id": "20150026",
      "name": "주현우",
      "number": 99,
      "role": "DEF"
    },
    {
      "id": "20240243",
      "name": "채현우",
      "number": 71,
      "role": "FWD"
    },
    {
      "id": "20200170",
      "name": "최건주",
      "number": 27,
      "role": "FWD"
    },
    {
      "id": "20260346",
      "name": "크네제비치",
      "number": 18,
      "role": "MID"
    },
    {
      "id": "20240080",
      "name": "한가람",
      "number": 13,
      "role": "MID"
    }
  ],
  "gimcheon": [
    {
      "id": "20220138",
      "name": "강민규",
      "number": 49,
      "role": "FWD"
    },
    {
      "id": "20240278",
      "name": "강주혁",
      "number": 50,
      "role": "FWD"
    },
    {
      "id": "20180123",
      "name": "고재현",
      "number": 7,
      "role": "FWD"
    },
    {
      "id": "20170153",
      "name": "김민규",
      "number": 5,
      "role": "DEF"
    },
    {
      "id": "20240315",
      "name": "김서진",
      "number": 43,
      "role": "DEF"
    },
    {
      "id": "20210227",
      "name": "김이석",
      "number": 8,
      "role": "MID"
    },
    {
      "id": "20200174",
      "name": "김인균",
      "number": 21,
      "role": "FWD"
    },
    {
      "id": "20230103",
      "name": "김주찬",
      "number": 17,
      "role": "FWD"
    },
    {
      "id": "20180324",
      "name": "김태환",
      "number": 11,
      "role": "DEF"
    },
    {
      "id": "20220248",
      "name": "김현우",
      "number": 4,
      "role": "DEF"
    },
    {
      "id": "20210162",
      "name": "노경호",
      "number": 53,
      "role": "MID"
    },
    {
      "id": "20220142",
      "name": "문현호",
      "number": 37,
      "role": "GK"
    },
    {
      "id": "20220112",
      "name": "민경현",
      "number": 2,
      "role": "DEF"
    },
    {
      "id": "20250068",
      "name": "박만호",
      "number": 41,
      "role": "GK"
    },
    {
      "id": "20190022",
      "name": "박민서",
      "number": 44,
      "role": "DEF"
    },
    {
      "id": "20230049",
      "name": "박세진",
      "number": 14,
      "role": "MID"
    },
    {
      "id": "20220270",
      "name": "박용희",
      "number": 58,
      "role": "FWD"
    },
    {
      "id": "20210119",
      "name": "박진성",
      "number": 33,
      "role": "DEF"
    },
    {
      "id": "20220139",
      "name": "박철우",
      "number": 3,
      "role": "DEF"
    },
    {
      "id": "20180096",
      "name": "박태준",
      "number": 55,
      "role": "MID"
    },
    {
      "id": "20190154",
      "name": "백종범",
      "number": 1,
      "role": "GK"
    },
    {
      "id": "20200317",
      "name": "변준수",
      "number": 45,
      "role": "DEF"
    },
    {
      "id": "20210178",
      "name": "안준수",
      "number": 51,
      "role": "GK"
    },
    {
      "id": "20240183",
      "name": "윤재석",
      "number": 54,
      "role": "MID"
    },
    {
      "id": "20210136",
      "name": "이강현",
      "number": 56,
      "role": "MID"
    },
    {
      "id": "20200164",
      "name": "이건희",
      "number": 9,
      "role": "FWD"
    },
    {
      "id": "20170022",
      "name": "이상헌",
      "number": 47,
      "role": "FWD"
    },
    {
      "id": "20190124",
      "name": "이수빈",
      "number": 6,
      "role": "MID"
    },
    {
      "id": "20230198",
      "name": "이정택",
      "number": 26,
      "role": "DEF"
    },
    {
      "id": "20210273",
      "name": "이찬욱",
      "number": 20,
      "role": "DEF"
    },
    {
      "id": "20190127",
      "name": "임덕근",
      "number": 15,
      "role": "MID"
    },
    {
      "id": "20210124",
      "name": "전병관",
      "number": 10,
      "role": "FWD"
    },
    {
      "id": "20240204",
      "name": "정마호",
      "number": 46,
      "role": "MID"
    },
    {
      "id": "20230157",
      "name": "정재민",
      "number": 57,
      "role": "FWD"
    },
    {
      "id": "20200105",
      "name": "홍시후",
      "number": 42,
      "role": "DEF"
    },
    {
      "id": "20230332",
      "name": "홍윤상",
      "number": 48,
      "role": "FWD"
    }
  ]
};
