import {animateNets} from './goal-net.js';
import {GameplayPanel} from './gameplay-panel.js';
import {PlayerEditor} from './player-editor.js';
import {CardPackUI} from './card-pack-ui.js';
import {addCoins,matchReward} from './wallet.js';
import {applyLineups} from './squads.js';
import {ResearchLibrary} from './research-library.js';
import {LocalPresentation} from './render-state.js';
import {MotionPreview} from './motion-preview.js';
import {assistanceDefaults} from './control-assist.js';
import * as THREE from 'three';
import {installQA} from './qa.js';
import {updateControlLabels} from './control-help.js';
import {Replay} from './replay.js';
const replay=new Replay(),presentation=new LocalPresentation();
import {buildStadium,createBall} from './stadium.js';
import {createPlayer,animatePlayer,disposePlayerRig} from './player.js';
import {Online} from './online.js';
import {Match} from './match.js';
import {MatchCamera} from './camera.js';
import {Input} from './input.js';
import {StadiumAudio} from './audio.js';
import {UI,show} from './ui.js';
import {loadSettings,saveSettings} from './settings.js';
import {TUNING,TEAMS} from './config.js';
const $=id=>document.getElementById(id),settings=loadSettings(),ui=new UI(),audio=new StadiumAudio(settings);
let renderer,match,input,online,preview,editor,rigs=[],appliedSquads='',stadium,hero,frame=0,last=performance.now(),accumulator=0,frameTimes=[],fps=60,previousState='playing';
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.08,250);camera.position.set(3.4,2.15,30.2);const director=new MatchCamera(camera);director.target.set(-1.55,1.08,24.7);
function onEvent(type,data){if(type==='card')ui.toast(`${data.card==='red'?'🟥 퇴장':'🟨 경고'} · ${data.player.name}${data.secondYellow?' · 경고 누적':''}`);if(type==='advantage')ui.toast('어드밴티지 · 플레이 계속');if(type==='addedTime')ui.toast('추가 시간');if(type==='command')ui.toast(data.text);if(type==='kick'){audio.kick(data.type==='shoot'?1.3:.7);if(online?.active&&data.contact){match.contacts.push(data.contact);if(match.contacts.length>80)match.contacts.shift();}}if(type==='tackle')audio.kick(.6);if(type==='save'){audio.noise(.15,.2,700);ui.toast('골키퍼 선방');}if(type==='start'){replay.clear();show('menu',false);show('hud');show('results',false);hero.root.visible=false;audio.init();}if(type==='kickoff'){audio.whistle();ui.event(match.practice?'TRAINING':'KICK OFF',match.practice?'TRAINING GROUND':TEAMS[data.team].name,match.direction(settings.userTeam)>0?'오른쪽 골문으로 공격하세요 →':'← 왼쪽 골문으로 공격하세요',1400);}if(type==='goal'){replay.begin();audio.goal();ui.event('GOAL!',TEAMS[data.team].name,`${match.score[0]} — ${match.score[1]}  ·  ${data.scorer?.name||''}`,3200);}if(type==='restart'){audio.whistle();ui.toast(`${data.label} · ${TEAMS[data.team].name}`);}if(type==='halftime'){audio.whistle();ui.event('HALF TIME','전반 종료','진영을 교체합니다',2900);}if(type==='fulltime'){audio.whistle();ui.results(match);if(!match.practice){const reward=matchReward(match.score,settings.userTeam);addCoins(reward);ui.toast(`카드팩 코인 +${reward}`);}}if(type==='resumePlay')input.enabled=true;}
function pause(){if(online?.active&&online.started){online.paused=!online.paused;input.clear();input.enabled=!online.paused;show('pause',online.paused);document.querySelector('#pause h2').textContent='온라인 경기 · 계속 진행 중';document.querySelector('#pause p').textContent='메뉴를 열어도 상대의 경기는 계속됩니다.';$('restart').classList.add('hidden');return;}document.querySelector('#pause h2').textContent='경기 일시정지';document.querySelector('#pause p').textContent='다음 플레이를 준비하세요.';$('restart').classList.remove('hidden');if(match.state==='menu'||match.state==='fulltime')return;if(match.state==='paused'){match.state=previousState;show('pause',false);input.clear();input.enabled=match.state==='playing';}else{previousState=match.state;match.state='paused';input.enabled=false;input.clear();match.charging=false;show('pause');}}
function start(practice=false){show('setup',false);show('pause',false);show('results',false);show('help',false);input.clear();setSquads(online?.active?editor.onlineSquads(online.squads,online.team):editor?.lineups());match.contacts=[];match.start(practice);presentation.reset(match);ui.update(match,fps,renderer);input.enabled=false;}
function setSquads(squads){if(!squads)return;const key=JSON.stringify(squads);if(key===appliedSquads)return;appliedSquads=key;applyLineups(match,squads);for(const old of rigs){disposePlayerRig(old);}rigs=[];for(const p of match.players){const rig=createPlayer(p.team,p.number,p.role==='GK',p);scene.add(rig.root);p.rig=rig;rigs.push(rig);}}
function menu(){if(online?.active){online.leave();return;}match.state='menu';input.enabled=false;input.clear();hero.root.visible=true;['hud','pause','results','event'].forEach(id=>show(id,false));show('menu');}
function quality(){const q=settings.quality;renderer.setPixelRatio(Math.min(devicePixelRatio,q==='high'?1.25:1)*settings.scale);renderer.shadowMap.enabled=settings.shadows&&q!=='low';stadium.crowdGroup.visible=settings.crowd&&q!=='low';stadium.sun.shadow.mapSize.set(q==='high'?2048:1024,q==='high'?2048:1024);renderer.setSize(innerWidth,innerHeight);saveSettings(settings);}
try{
 renderer=new THREE.WebGLRenderer({canvas:$('scene'),antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.06;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 stadium=buildStadium(scene);quality();
 match=new Match(settings,onEvent);input=new Input(settings,(action,options)=>{if(action==='pause'){if(!$('help').classList.contains('hidden')){show('help',false);return}pause();}else if(action==='blur'){if(online?.active){input.clear();online.latestInput={axis:{x:0,z:0}};}else if(match.state==='playing')pause();}else if(action==='camera'){settings.camera=(settings.camera+1)%3;saveSettings(settings);ui.toast(['중계 카메라','전술 카메라','클로즈업 카메라'][settings.camera]);}else if(action==='debug')ui.debug=!ui.debug;else if(action==='help'){pause();show('help');}else if(action==='replaySkip'&&match.state==='goal'){if(!online?.active)match.timer=0;replay.playback=null;}else if(online?.active){online.command(action,options);}else {match.input=input;match.action(action,options);}},()=>match.controlContext());
 editor=new PlayerEditor(()=>{});setSquads(editor.lineups());editor.ready.then(()=>{if(!online?.active)setSquads(editor.lineups());});new ResearchLibrary();new CardPackUI(editor);
 new GameplayPanel(settings,()=>saveSettings(settings));
 hero=createPlayer(0,10);preview=new MotionPreview(hero);hero.root.position.set(0,0,24.6);hero.root.rotation.y=.28;scene.add(hero.root);
 const heroLight=new THREE.PointLight(0xfff2d2,9,9,2);heroLight.position.set(1,3.2,27);scene.add(heroLight);
 const ballMesh=createBall();scene.add(ballMesh);const ballShadow=new THREE.Mesh(new THREE.CircleGeometry(.20,24),new THREE.MeshBasicMaterial({color:0x061806,transparent:true,opacity:.35,depthWrite:false}));ballShadow.rotation.x=-Math.PI/2;scene.add(ballShadow);
 const selection=new THREE.Mesh(new THREE.RingGeometry(.48,.55,40),new THREE.MeshBasicMaterial({color:0xc6ff5d,side:THREE.DoubleSide,depthWrite:false}));selection.rotation.x=-Math.PI/2;scene.add(selection);
 const arrow=new THREE.Mesh(new THREE.ConeGeometry(.14,.28,3),new THREE.MeshBasicMaterial({color:0xc6ff5d}));arrow.rotation.z=Math.PI;scene.add(arrow);
 const ballMarker=new THREE.Mesh(new THREE.RingGeometry(.19,.21,24),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.5,depthWrite:false}));ballMarker.rotation.x=-Math.PI/2;scene.add(ballMarker);
 const setpieceAim=new THREE.Mesh(new THREE.RingGeometry(.18,.23,32),new THREE.MeshBasicMaterial({color:0xc6ff5d,side:THREE.DoubleSide,depthTest:false,depthWrite:false,transparent:true,opacity:.9}));setpieceAim.rotation.y=Math.PI/2;setpieceAim.visible=false;setpieceAim.renderOrder=20;scene.add(setpieceAim);
 $('kickoff').onclick=()=>show('setup');$('practice').onclick=()=>start(true);$('how-to').onclick=()=>show('help');$('close-help').onclick=()=>show('help',false);$('resume').onclick=pause;$('pause-button').onclick=pause;$('restart').onclick=()=>start(match.practice);$('exit').onclick=menu;$('play-again').onclick=()=>{if(!online?.rematch())start(false);};$('result-menu').onclick=menu;$('camera-button').onclick=()=>{settings.camera=(settings.camera+1)%3;saveSettings(settings);ui.toast(['중계 카메라','전술 카메라','클로즈업 카메라'][settings.camera]);};
 $('quality').value=settings.quality;$('quality').onchange=e=>{settings.quality=e.target.value;quality();};document.querySelectorAll('.sound-button').forEach(el=>{const sync=()=>el.querySelector('span').textContent=settings.sound?'사운드 ON':'사운드 OFF';sync();el.onclick=()=>{settings.sound=!settings.sound;audio.init();audio.setVolume();saveSettings(settings);sync();};});
 const bindAssists=()=>{for(const key of Object.keys(assistanceDefaults)){const el=$(key+'-select');if(el.type==='checkbox')el.checked=settings[key];else el.value=settings[key];el.onchange=()=>{settings[key]=el.type==='checkbox'?el.checked:key==='runType'?Number(el.value):el.value;saveSettings(settings);};}};bindAssists();$('assist-preset').onclick=()=>{Object.assign(settings,assistanceDefaults);bindAssists();saveSettings(settings);ui.toast('추천 조작 지원 설정을 적용했습니다.');};
 $('controls-select').value=settings.controls;$('defence-select').value=settings.defence;updateControlLabels(settings);$('team-select').value=settings.userTeam;$('duration-select').value=settings.halfSeconds;$('difficulty-select').value=settings.difficulty;$('camera-select').value=settings.camera;$('volume-select').value=settings.volume;$('resolution-select').value=settings.scale;$('shadow-select').checked=settings.shadows;$('crowd-select').checked=settings.crowd;$('deadzone-select').value=settings.deadzone;
 const controls={'controls-select':['controls',String],'defence-select':['defence',String],'team-select':['userTeam',Number],'duration-select':['halfSeconds',Number],'difficulty-select':['difficulty',String],'camera-select':['camera',Number],'volume-select':['volume',Number],'resolution-select':['scale',Number],'deadzone-select':['deadzone',Number]};for(const [id,[key,convert]]of Object.entries(controls))$(id).onchange=e=>{settings[key]=convert(e.target.value);if(key==='controls'||key==='defence'){input.clear();updateControlLabels(settings);}if(key==='volume'){settings.sound=true;audio.init();audio.setVolume();}if(key==='scale')quality();saveSettings(settings);};for(const [id,key] of [['shadow-select','shadows'],['crowd-select','crowd']])$(id).onchange=e=>{settings[key]=e.target.checked;quality();};$('setup-start').onclick=()=>start(false);$('setup-close').onclick=()=>show('setup',false);$('fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>ui.toast('전체화면을 지원하지 않는 브라우저입니다.'));};
 $('replay-skip').onclick=()=>{if(match.state==='goal'){if(!online?.active)match.timer=0;replay.playback=null;}};
 window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
 match.physics.ball.addEventListener('collide',event=>{const speed=Math.abs(event.contact.getImpactVelocityAlongNormal());if(speed<1.5||match.state==='menu')return;const surface=event.body.material?.name;if(surface==='post')audio.tone(450,.22,Math.min(.15,speed*.008),'triangle',270);else if(surface==='net')audio.noise(.09,.08,900);else if(surface==='turf')audio.kick(Math.min(.45,speed*.035));});
 document.querySelector('.match-details span:last-child').textContent=`${settings.halfSeconds*2/60} MIN · 맑음 · 야간`;
 installQA(match,ui);show('loading',false);show('menu');online=new Online(match,settings,{begin:()=>start(false),event:onEvent,end:()=>menu(),networkLineup:(team,share)=>editor.networkLineup(team,share)});
 // Public read-only diagnostics aid manual QA without altering simulation state.
 window.touchline={snapshot:()=>({state:match.state,score:[...match.score],half:match.half,elapsed:match.elapsed,ball:{x:match.physics.ball.position.x,y:match.physics.ball.position.y,z:match.physics.ball.position.z,speed:match.physics.ball.velocity.length()},controlled:{name:match.controlled.name,x:match.controlled.x,z:match.controlled.z},owner:match.owner?.name,frames:frame,fps,drawCalls:renderer.info.render.calls,online:online?.active?{room:online.room,team:online.team,connected:online.connected,frame:online.lastFrame}:null,motion:match.controlled?.rig?.motionState}),settings};
 function animate(now){requestAnimationFrame(animate);if(match.state==='menu'&&(!$('players-panel').classList.contains('hidden')||!$('cards-panel').classList.contains('hidden'))){last=now;return;}const frameDt=(now-last)/1000,realDt=Math.min(frameDt,.1);last=now;frameTimes.push(frameDt);match.frameMetrics={p95:Math.round([...frameTimes].sort((a,b)=>a-b)[Math.floor((frameTimes.length-1)*.95)]*1000),max:Math.round(Math.max(...frameTimes)*1000)};if(frameTimes.length>120)frameTimes.shift();if(frame%20===0)fps=Math.round(1/(frameTimes.reduce((a,b)=>a+b,0)/frameTimes.length));input.enabled=match.state==='playing'&&(!online?.active||online.connected&&!online.paused&&!online.lobby?.paused);input.poll();if(online?.active){online.update(input,now);accumulator=0;replay.record(match,realDt);}else{accumulator+=Math.min(realDt,.05);while(accumulator>=TUNING.step){match.step(TUNING.step,match.qaInput||input);presentation.step(match);replay.record(match,TUNING.step);accumulator-=TUNING.step;}}
 const display=online?.active?null:presentation.sample(accumulator/TUNING.step);const displayBall=display?{x:display.ball[0],y:display.ball[1],z:display.ball[2]}:match.physics.ball.position;
 const playback=match.state==='goal'&&match.timer<5?replay.sample(5-match.timer):null;show('replay-skip',!!playback);const time=now/1000;for(const p of match.players){const rig=p.rig;rig.contactDetail=p===match.controlled;rig.root.visible=match.state!=='menu'&&p.active;if(!rig.root.visible)continue;const distant=camera.position.distanceTo(rig.root.position)>23;if(distant!==rig.distant){rig.distant=distant;for(const detail of rig.details)detail.visible=!distant;for(const level of rig.lod){level.far.visible=distant;level.near.forEach(m=>m.visible=!distant);}}const pose=playback?playback.players[p.id]:display?.players[p.id]||p;rig.root.position.set(pose.x,0,pose.z);rig.root.rotation.y=pose.yaw;const animated=playback?{...p,...pose,vx:Math.sin(pose.yaw)*pose.speed,vz:Math.cos(pose.yaw)*pose.speed}:pose;animatePlayer(rig,playback?pose.speed:Math.hypot(pose.vx,pose.vz),realDt,playback?.time??display?.time??match.time,!playback&&match.state==='goal'&&p.team===match.goalTeam,animated,playback?playback.ball:displayBall);}
 if(match.state==='menu'){if(preview.active)preview.animate(ballMesh,camera,realDt);else{animatePlayer(hero,0,realDt,time);hero.root.rotation.y=.25+Math.sin(time*.2)*.14;ballMesh.position.set(.45,.11,25.05);ballMesh.rotation.y=time*.06;}}else{if(playback){ballMesh.position.copy(playback.ball);ballMesh.quaternion.copy(playback.ball.q);}else {ballMesh.position.copy(displayBall);if(display)ballMesh.quaternion.set(...display.ball.slice(6,10));else ballMesh.quaternion.copy(match.physics.ball.quaternion);}}
 animateNets(stadium.goals,ballMesh.position,realDt);
 setpieceAim.visible=match.state==='playing'&&!!match.setPiece&&['free','penalty'].includes(match.setPiece.kind);$('hud').classList.toggle('setpiece-aiming',setpieceAim.visible);if(setpieceAim.visible){const s=match.setPiece;setpieceAim.position.set(match.direction(s.team)*52.35,s.aimHeight,s.aimZ);setpieceAim.material.color.setHex(Math.abs(s.aimZ)>3.5||s.aimHeight>2.3?0xff7666:0xc6ff5d);}
 ballShadow.position.set(ballMesh.position.x,.012,ballMesh.position.z);ballShadow.scale.setScalar(1+ballMesh.position.y*.15);ballShadow.material.opacity=.34/(1+ballMesh.position.y*.25);ballMarker.position.set(ballMesh.position.x,.017,ballMesh.position.z);ballMarker.visible=match.state!=='menu';selection.visible=arrow.visible=match.state!=='menu';const selected=display?.players[match.controlled.id]||match.controlled;selection.position.set(selected.x,.021,selected.z);arrow.position.set(selected.x,2.23+Math.sin(time*5)*.035,selected.z);if(playback){director.update({state: "playing", controlled:playback.players[match.controlled.id],physics:{ball:{position:playback.ball,velocity:{x:0,z:0}}}},2,realDt,time);selection.visible=arrow.visible=false;}else if(!preview.active)director.update(display?{...match,controlled:selected,physics:{ball:{position:displayBall,velocity:match.physics.ball.velocity}}}:match,settings.camera,realDt,time);const measured=preview.active?hero:match.controlled.rig;if(frame%6===0)$('scene').dataset.motionDiagnostics=JSON.stringify({state:measured.motionState,armBend:measured.arms.map(a=>Math.round(a.lower.rotation.x*100)/100),plantCm:(measured.plantError||0)*100,locks:measured.plantLocks||0,impactCm:measured.impactError===undefined?null:measured.impactError*100,impactClamped:!!measured.impactClamped,fps,drawCalls:renderer.info.render.calls,frame:frame,contact:match.contacts.at(-1),online:online.active?{room:online.room,team:online.team,connected:online.connected,serverFrame:online.lastFrame}:null});heroLight.visible=match.state==='menu';renderer.render(scene,camera);if(frame++%6===0&&match.state!=='menu')ui.update(match,fps,renderer);if(frame%60===0&&match.state==='playing')audio.update(Math.max(0,(Math.abs(match.physics.ball.position.x)-25)/30));}
 requestAnimationFrame(animate);
}catch(error){console.error(error);$('loading-text').textContent=`실행 오류: ${error.message}. 최신 Chrome 또는 Edge에서 다시 실행해 주세요.`;document.querySelector('.loading-track').style.display='none';}
