import {seededRandom} from './attributes.js';

// Opt-in local measurement UI. This is not loaded by the production entry point.
export function installMatchAudit({match,input,renderer,scene,camera,stadium,settings,start}){
 const label=new URLSearchParams(location.search).get('audit')||'run';
 const panel=document.createElement('aside');panel.id='match-audit';panel.style.cssText='position:fixed;right:8px;top:72px;z-index:50;background:#071b19e8;color:#fff;padding:9px;width:220px;font:11px monospace';
 const status=document.createElement('output');panel.append(status);document.body.append(panel);
 const button=(text,run)=>{const b=document.createElement('button');b.textContent=text;b.style.cssText='display:block;width:100%;padding:5px;margin-top:4px;background:#214741;color:#fff;font-size:11px';b.onclick=run;panel.append(b);};
 let active=false,startAt=0,lastAt=0,lastCommand=-1,pendingShot=0,previousKeys=new Set(),frameCosts={},frames=[],events=[],hidden=0,report=null,screenshot=false,sheets=[],pendingSheet=null;
 const now=()=>performance.now(),gl=renderer.getContext(),gpuExt=gl.getExtension('EXT_disjoint_timer_query_webgl2'),pendingQueries=[],gpu=[];
 const stats=values=>{const sorted=[...values].sort((a,b)=>a-b);return {count:values.length,mean:values.reduce((a,b)=>a+b,0)/(values.length||1),p95:sorted[Math.floor((sorted.length-1)*.95)]||0,max:sorted.at(-1)||0};};
 const download=(name,data,type)=>{const filename=`touchline-${label}-${name}`;const payload=typeof data==='string'&&data.startsWith('data:')?fetch(data).then(r=>r.blob()):Promise.resolve(new Blob([data],{type}));payload.then(body=>fetch('/__audit/evidence?name='+encodeURIComponent(filename),{method:'POST',body})).catch(()=>{});const link=document.createElement('a'),url=typeof data==='string'&&data.startsWith('data:')?data:URL.createObjectURL(new Blob([data],{type}));link.download=filename;link.href=url;link.click();if(!url.startsWith('data:'))setTimeout(()=>URL.revokeObjectURL(url),3000);};
 const cost=(name,fn,that,args)=>{const t=now();try{return fn.apply(that,args);}finally{frameCosts[name]=(frameCosts[name]||0)+now()-t;}};
 const wrap=(object,key,name)=>{const original=object[key];object[key]=function(...args){return active||ab?cost(name,original,this,args):original.apply(this,args);};};
 wrap(match,'step','simulation');wrap(match.physics,'step','physics');wrap(renderer.shadowMap,'render','shadowCpu');
 const known=new WeakSet();scene.traverse(o=>{if(o.skeleton&&!known.has(o.skeleton)){known.add(o.skeleton);wrap(o.skeleton,'update','skinning');}});
 const emit=match.emit;match.emit=(kind,data)=>{emit(kind,data);if(!active)return;if(['kick','save','goal','restart','control','miss'].includes(kind)){events.push({wallSeconds:(now()-startAt)/1000,simulationTime:match.time,kind,team:data?.player?.team??data?.team,type:data?.type,player:data?.player?.id,contact:data?.contact});if(kind==='kick'&&data?.contact&&!sheets.some(s=>s.type===data.type)&&!pendingSheet){pendingSheet={type:data.type,frames:0,canvas:document.createElement('canvas')};pendingSheet.canvas.width=1920;pendingSheet.canvas.height=1260;}}};
 const render=renderer.render;renderer.render=function(...args){
  let query;if(active&&gpuExt&&frames.length>0&&frames.length%20===0&&pendingQueries.length<4){query=gl.createQuery();gl.beginQuery(gpuExt.TIME_ELAPSED_EXT,query);}
  if(ab?.formation){camera.position.set(0,104,55);camera.lookAt(0,0,0);}
  const t=now();render.apply(this,args);frameCosts.render=now()-t;
  if(query){gl.endQuery(gpuExt.TIME_ELAPSED_EXT);pendingQueries.push(query);}
  if(active&&gpuExt){for(let i=pendingQueries.length-1;i>=0;i--){const q=pendingQueries[i];if(gl.getQueryParameter(q,gl.QUERY_RESULT_AVAILABLE)){if(!gl.getParameter(gpuExt.GPU_DISJOINT_EXT))gpu.push(gl.getQueryParameter(q,gl.QUERY_RESULT)/1e6);gl.deleteQuery(q);pendingQueries.splice(i,1);}}}
  if(screenshot){screenshot=false;const c=document.createElement('canvas');c.width=renderer.domElement.width;c.height=renderer.domElement.height;c.getContext('2d').drawImage(renderer.domElement,0,0);download(`scene-${Math.round(match.time)}.png`,c.toDataURL('image/png'));}
  if(pendingSheet){const s=pendingSheet,ctx=s.canvas.getContext('2d'),i=s.frames++,x=i%4*480,y=Math.floor(i/4)*210;ctx.fillStyle='#081817';ctx.fillRect(x,y,480,210);ctx.drawImage(renderer.domElement,x,y,480,190);ctx.fillStyle='white';ctx.font='13px Arial';ctx.fillText(`${s.type} / rendered frame ${i+1} / t=${match.time.toFixed(3)}`,x+6,y+204);if(s.frames===24){sheets.push(s);pendingSheet=null;}}
 };
 const hold=keys=>{for(const key of previousKeys)if(!keys.has(key))input.keyUp(key);for(const key of keys)if(!previousKeys.has(key))input.keyDown(key);previousKeys=keys;};
 const control=t=>{if(match.state!=='playing'){hold(new Set());return;}const p=match.controlled,b=match.physics.ball.position,dir=match.direction(settings.userTeam),attack=match.owner?.team===settings.userTeam,cycle=Math.floor(t/5),keys=new Set();
  if(attack){if(t%12<8)keys.add(dir>0?'ArrowRight':'ArrowLeft');if(t%16<4)keys.add('ArrowUp');else if(t%16>12)keys.add('ArrowDown');if(t%10<4)keys.add('KeyE');}
  else {const dx=b.x-p.x,dz=b.z-p.z;if(Math.abs(dx)>1.4)keys.add(dx>0?'ArrowRight':'ArrowLeft');if(Math.abs(dz)>1.4)keys.add(dz>0?'ArrowDown':'ArrowUp');keys.add('KeyD');if(Math.hypot(dx,dz)>6)keys.add('KeyE');}
  hold(keys);
  if(pendingShot&&t>=pendingShot){input.keyUp('KeyD');pendingShot=0;}
  if(cycle!==lastCommand){lastCommand=cycle;if(attack){const key=match.setPiece?'KeyD':cycle%5===3?'KeyD':cycle%5===2?'KeyA':cycle%5===1?'KeyW':'KeyS';input.keyDown(key);if(key==='KeyD')pendingShot=t+.24;else input.keyUp(key);}else {input.keyDown('KeyS');input.keyUp('KeyS');}}
 };
 const environment=()=>{const ext=gl.getExtension('WEBGL_debug_renderer_info');return {userAgent:navigator.userAgent,hardwareConcurrency:navigator.hardwareConcurrency,deviceMemoryGiB:navigator.deviceMemory,webglVendor:ext?gl.getParameter(ext.UNMASKED_VENDOR_WEBGL):gl.getParameter(gl.VENDOR),webglRenderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),viewport:[innerWidth,innerHeight],drawingBuffer:[gl.drawingBufferWidth,gl.drawingBufferHeight],devicePixelRatio,settings:JSON.parse(JSON.stringify(settings)),gpuTimerSupported:!!gpuExt};};
 function finish(){active=false;hold(new Set());input.clear();const intervals=frames.map(f=>f.interval),seconds=intervals.reduce((a,b)=>a+b,0)/1000;report={label,method:'Real-time browser 11v11 with scripted keyboard reducer inputs; no fast-forward. First 10 seconds warmup, then 300 seconds visible RAF sampling. Not human play.',environment:environment(),wallSeconds:(now()-startAt)/1000,measuredSeconds:seconds,hiddenFrames:hidden,averageFps:frames.length/seconds,frameMs:stats(intervals),cpu:Object.fromEntries(['simulation','physics','animation','skinning','shadowCpu','render'].map(k=>[k,stats(frames.map(f=>f[k]||0))])),gpuRenderMs:stats(gpu),drawCalls:stats(frames.map(f=>f.calls)),triangles:stats(frames.map(f=>f.triangles)),score:[...match.score],matchStats:match.stats,events,frames,notes:['physics is nested within simulation; skinning/shadow CPU are nested within render; do not add these nested values','GPU total query only when supported; crowd measured separately by fixed-scene A/B']};report.valid=seconds>=300&&hidden===0&&report.wallSeconds<330&&report.cpu.render.max<10000;status.textContent=report.valid?`완료 ${report.averageFps.toFixed(1)} FPS / P95 ${report.frameMs.p95.toFixed(1)} ms`:'시간 단절 감지 · 이 기록은 비교에서 제외하고 재측정';match.state='paused';download('match.json',JSON.stringify(report,null,2),'application/json');}
 button('5분 입력 경기 기록',()=>{Object.assign(settings,{quality:'high',camera:0,halfSeconds:600,difficulty:'normal',userTeam:0,shadows:true,crowd:true,scale:1,sound:false,controls:'online'});match.random=seededRandom(260926);start(false);frames=[];events=[];gpu.length=0;sheets=[];hidden=0;startAt=now();lastAt=startAt;lastCommand=-1;pendingShot=0;active=true;status.textContent='10초 준비 후 300초 기록';});
 button('경기 화면 PNG 저장',()=>{screenshot=true;});
 button('동작 24프레임 저장',()=>{for(const s of sheets)download(`${s.type}-frames.png`,s.canvas.toDataURL('image/png'));status.textContent=`${sheets.length}개 실제 렌더 연속 프레임 저장`;});
 button('기록 JSON 저장',()=>{if(report)download('match.json',JSON.stringify(report,null,2),'application/json');});
 button('중단',()=>{if(active)finish();});
 let ab=null;
 button('정지 장면 관중·그림자 비용 비교',()=>{if(active)return;match.state='paused';ab={phase:0,index:0,samples:[[],[],[],[]],originalCrowd:stadium.crowdGroup.visible,originalShadow:renderer.shadowMap.enabled};status.textContent='같은 정지 장면 4조건 × 90프레임';});
 button('22명 동일 배치 비용 비교',()=>{if(active)return;start(false);match.state='paused';ab={formation:true,phase:0,index:0,samples:[[],[],[],[]],originalCrowd:stadium.crowdGroup.visible,originalShadow:renderer.shadowMap.enabled};status.textContent='22명 고정 배치 · 관중/그림자 4조건';});
 status.textContent=`LOCAL AUDIT / ${label} / GPU timer ${gpuExt?'지원':'미지원'}`;
 return {begin(t){frameCosts={};if(active){const elapsed=(t-startAt)/1000;control(elapsed);if(elapsed>=310.1){finish();return;}status.textContent=`${Math.min(300,Math.max(0,elapsed-10)).toFixed(0)} / 300초 · ${match.state} · ${frames.length} frames`;}
   if(ab){stadium.crowdGroup.visible=ab.phase%2===0;renderer.shadowMap.enabled=ab.phase<2;}
  },animation(ms){frameCosts.animation=ms;},end(t){if(active){if(document.hidden)hidden++;if(t-startAt>=10000&&!document.hidden)frames.push({interval:t-lastAt,...frameCosts,calls:renderer.info.render.calls,triangles:renderer.info.render.triangles});lastAt=t;}
   if(ab){if(ab.index++>=15)ab.samples[ab.phase].push({...frameCosts,calls:renderer.info.render.calls,triangles:renderer.info.render.triangles});if(ab.index===90){ab.index=0;if(++ab.phase===4){download(ab.formation?'formation-ab.json':'render-ab.json',JSON.stringify({environment:environment(),scope:ab.formation?'Identical kickoff formation, all 22 players, camera [0,104,55], CPU submission A/B; GPU not isolated':'Fixed scene CPU submission difference; not isolated GPU crowd timing',samples:ab.samples.map((r,i)=>({crowd:i%2===0,shadows:i<2,render:stats(r.map(v=>v.render)),shadow:stats(r.map(v=>v.shadowCpu||0)),calls:stats(r.map(v=>v.calls)),triangles:stats(r.map(v=>v.triangles))}))},null,2),'application/json');stadium.crowdGroup.visible=ab.originalCrowd;renderer.shadowMap.enabled=ab.originalShadow;ab=null;status.textContent='정지 장면 A/B 완료';}}}
  }};
}
