import {BodyStudio} from './body-studio.js';
import {cleanBody,BODY_PRESETS,applyBodyPreset} from './body-shape.js';
import {celebrationOptions} from './celebrations.js';
import {ratingLabels,ratingRange,displayValue,engineValue,ratingGrade,ratingSummary,overallRating} from './player-ratings.js';
import {FaceStudio} from './face-studio.js';
import {cleanFace,networkFace} from './face-settings.js';
import {getFaceAsset,putFaceAssets,cleanFaceAsset} from './face-assets.js';
import {PlayerPortrait} from './player-portrait.js';
import {STAT_FIELDS,cleanLibrary,cleanProfile,loadSquads,saveSquads,lineupProfiles} from './squads.js';
const $=id=>document.getElementById(id);
const el=(tag,text,className)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;};
export class PlayerEditor{
 constructor(onChange){this.data=loadSquads();this.selected=this.data.players[9].uid;this.team=0;this.onChange=onChange;this.undo=[];this.fields={};this.portrait=null;this.assets=new Map();this.faceDraft=cleanFace();this.bodyDraft=cleanBody();this.ready=this.loadAssets();this.studio=new FaceStudio((face,asset)=>{this.faceDraft=face;if(asset){this.assets.set(asset.id,asset);this.fields.skin.value=asset.skin;}this.previewDraft();this.faceStatus();this.status('페이스온을 준비했습니다. 선수 설정 저장을 누르면 다음 경기부터 적용됩니다.');});$('player-face-open').onclick=()=>this.studio.open(this.draft(),this.assets.get(this.faceDraft.assetId),this.team);$('player-face-enabled').onchange=e=>{this.faceDraft.enabled=e.target.checked;this.previewDraft();};
  this.bodyStudio=new BodyStudio(p=>{this.bodyDraft=p.body;this.fields.bodyType.value=p.bodyType;for(const key of ['height','weight','build'])this.fields[key].value=displayValue(key,p[key]);this.previewDraft();this.status('체형을 적용했습니다. 선수 설정 저장을 누르면 다음 경기부터 적용됩니다.');});$('player-body-open').onclick=()=>{const p=this.draft();p.faceTexture=p.face.enabled?this.assets.get(p.face.assetId)?.atlas:null;this.bodyStudio.open(p,this.team);};$('players-open').onclick=()=>this.open();$('players-close').onclick=()=>{$('players-panel').classList.add('hidden');};$('player-team').onchange=e=>{this.team=Number(e.target.value);this.renderLineup();this.previewDraft();};
  $('player-add').onclick=()=>this.add(false);$('player-clone').onclick=()=>this.add(true);$('player-delete').onclick=()=>this.remove();$('player-undo').onclick=()=>{if(this.undo.length){this.data=this.undo.pop();this.selected=this.data.players[0].uid;this.persist();this.render();}};
  $('player-save').onclick=()=>this.save();$('player-export').onclick=()=>this.exportFile();
  $('player-import').onchange=e=>this.importFile(e.target);
  this.addField('name','선수 이름','text',null,24);this.addField('number','등번호','number',[1,99,1]);this.addField('role','포지션','select',{GK:'골키퍼',DEF:'수비수',MID:'미드필더',FWD:'공격수'});this.addField('foot','주발','select',{right:'오른발',left:'왼발'});this.addField('height','키 · cm','number',[155,210,.1]);this.addField('weight','몸무게 · kg','number',[45,125,.1]);this.addField('build','체격 · 기준 100%','number',[80,125,1]);this.addField('bodyType','체형 유형','select',Object.fromEntries(Object.entries(BODY_PRESETS).map(([k,v])=>[k,v.label])));this.fields.bodyType.onchange=()=>{const p=applyBodyPreset(this.draft(),this.fields.bodyType.value);this.bodyDraft=p.body;this.previewDraft();};this.addField('skin','피부 색','color');this.addField('hair','머리 색','color');this.addField('boots','축구화 색','color');this.addField('hairStyle','머리 모양','select',{short:'짧은 머리',crop:'크롭',crest:'크레스트',bald:'삭발'});this.addField('motionStyle','동작 스타일','select',{balanced:'균형',compact:'짧고 민첩하게',power:'크고 힘있게'});
  this.addField('celebration','골 세리머니','select',celebrationOptions);
  for(const key of Object.keys(STAT_FIELDS))this.addField(key,ratingLabels[key]+' · 100점','number',ratingRange(key));
 }
 addField(key,label,type,options,max){const wrap=el('label',label),input=el(type==='select'?'select':'input');input.id='edit-'+key;input.setAttribute('aria-label',label);if(type==='select')for(const [v,t]of Object.entries(options)){const o=el('option',t);o.value=v;input.append(o);}else{input.type=type;if(type==='number')input.required=true;if(options)[input.min,input.max,input.step]=options;if(max)input.maxLength=max;}wrap.append(input);if(STAT_FIELDS[key]){wrap.classList.add('rating-field');const track=el('span',undefined,'rating-track'),fill=el('i');fill.id='rating-bar-'+key;track.append(fill);wrap.append(track);const grade=el('small');grade.id='rating-note-'+key;wrap.append(grade);input.oninput=()=>this.renderRatings();}$('player-fields').append(wrap);this.fields[key]=input;if(['name','number','role','height','weight','build','skin','hair','boots','hairStyle'].includes(key))input.onchange=()=>this.previewDraft();}
 readField(key,input){if(input.type!=='number')return input.value;const original=this.data.players.find(p=>p.uid===this.selected)?.[key];return input.value===String(displayValue(key,original))?original:engineValue(key,Number(input.value));}
 renderRatings(){const p=this.draft(),overall=overallRating(p);$('rating-overall').textContent=overall;$('rating-position').textContent=p.role;$('rating-grade').textContent=ratingGrade(overall);$('player-rating-card').dataset.grade=ratingGrade(overall);const summary=$('rating-summary');summary.replaceChildren();for(const item of ratingSummary(p)){const cell=el('div'),label=el('span',item.label),score=el('b',String(item.value));cell.append(score,label);summary.append(cell);}for(const key of Object.keys(STAT_FIELDS)){const value=displayValue(key,p[key]),fill=$('rating-bar-'+key);if(!fill)continue;fill.style.width=value+'%';fill.dataset.grade=ratingGrade(value);$('rating-note-'+key).textContent=value+' / 100 · '+ratingGrade(value);}}
 status(text){$('player-status').textContent=text;}
 snapshot(){this.undo.push(structuredClone(this.data));if(this.undo.length>20)this.undo.shift();}
 persist(){try{this.data=saveSquads(this.data);this.onChange();return true;}catch(e){this.status(e.message);return false;}}
 applyLibrary(data){const previous=this.data;this.snapshot();this.data=data;if(!this.persist()){this.data=previous;this.undo.pop();throw Error('선수 라이브러리를 저장하지 못했습니다.');}if(!$('players-panel').classList.contains('hidden'))this.render();return this.data;}
 draft(){const raw={...this.data.players.find(p=>p.uid===this.selected),face:structuredClone(this.faceDraft),body:structuredClone(this.bodyDraft)};for(const [key,input]of Object.entries(this.fields))raw[key]=this.readField(key,input);return cleanProfile(raw);}
 faceStatus(){$('player-face-enabled').checked=this.faceDraft.enabled;$('player-face-state').textContent=this.faceDraft.assetId?(this.assets.has(this.faceDraft.assetId)?(this.faceDraft.mode==='sculpt'?'입체 3D 얼굴 준비됨':'사진 표면 준비됨'):'사진을 이 브라우저에서 찾을 수 없습니다. 사진을 다시 넣어 주세요.'):'기본 얼굴 · 윤곽과 사진을 편집할 수 있습니다.';}
 previewDraft(){this.renderRatings();const body=this.draft();$('player-body-state').textContent=displayValue('height',body.height)+' cm · '+body.weight+' kg · 부위별 16가지 조절';if(!this.portrait)return;const profile=this.draft();profile.faceTexture=profile.face.enabled?this.assets.get(profile.face.assetId)?.atlas:null;this.portrait.update(profile,this.team);}
 async loadAssets(){for(const id of new Set(this.data.players.map(p=>p.face?.assetId).filter(Boolean)))try{const asset=await getFaceAsset(id);if(asset)this.assets.set(id,cleanFaceAsset(asset));}catch(e){this.status(e.message);}if(this.portrait){this.previewDraft();this.faceStatus();}}
 async exportFile(){try{await this.ready;const ids=new Set(this.data.players.map(p=>p.face?.assetId).filter(Boolean)),faceAssets=[...ids].map(id=>this.assets.get(id)).filter(Boolean),data={...this.data,version:2,faceAssets};const a=el('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));a.download='touchline-players-with-faces.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);this.status('저장된 선수와 사진을 함께 내보냈습니다.');}catch(e){this.status(e.message);}}
 async importFile(input){const file=input.files[0];if(!file)return;try{if(file.size>64*1024*1024)throw Error('64MB 이하의 선수 파일을 선택해 주세요.');const raw=JSON.parse(await file.text());if(![1,2].includes(raw.version))throw Error('선수 파일 버전을 확인해 주세요.');const data=cleanLibrary({...raw,version:1});if(raw.faceAssets!==undefined&&(!Array.isArray(raw.faceAssets)||raw.faceAssets.length>200))throw Error('페이스온 목록을 확인해 주세요.');const assets=(raw.faceAssets||[]).map(cleanFaceAsset);if(new Set(assets.map(a=>a.id)).size!==assets.length)throw Error('페이스온 식별자가 중복됐습니다.');const required=new Set(data.players.map(p=>p.face.assetId).filter(Boolean));if([...required].some(id=>!assets.some(a=>a.id===id)&&!this.assets.has(id)))throw Error('선수에 연결된 사진이 파일에 없습니다. 사진을 포함해 다시 내보내 주세요.');if(assets.length)await putFaceAssets(assets.filter(a=>required.has(a.id)));const saved=saveSquads(data);this.snapshot();for(const a of assets)this.assets.set(a.id,a);this.data=saved;this.selected=saved.players[0].uid;this.onChange();this.render();this.status('선수·팀 구성과 페이스온을 불러왔습니다.');}catch(e){this.status(e.message);}finally{input.value='';}}
 open(){$('players-panel').classList.remove('hidden');if(!this.portrait)try{this.portrait=new PlayerPortrait($('player-portrait'));}catch{}this.render();this.status('수정 후 저장하세요. 선수를 팀의 자리에 배치하면 다음 경기부터 적용됩니다.');}
 render(){const list=$('player-list');list.replaceChildren();for(const p of this.data.players){const b=el('button',`${String(p.number).padStart(2,'0')}  ${p.name} · ${p.role}`,p.uid===this.selected?'selected':'');b.onclick=()=>{this.selected=p.uid;this.render();};list.append(b);}const p=this.data.players.find(p=>p.uid===this.selected)||this.data.players[0];this.selected=p.uid;this.faceDraft=cleanFace(p.face);this.bodyDraft=cleanBody(p.body);this.faceStatus();for(const [key,input]of Object.entries(this.fields))input.value=typeof p[key]==='number'?displayValue(key,p[key]):p[key];$('player-count').textContent=`${this.data.players.length} PLAYERS`;$('player-undo').disabled=!this.undo.length;this.renderLineup();this.previewDraft();}
 renderLineup(){const list=$('player-lineup');list.replaceChildren();this.data.lineups[this.team].forEach((uid,index)=>{const row=el('label',index===0?'01 · GK':`${String(index+1).padStart(2,'0')} · ${index<5?'수비':index<8?'중원':'공격'}`),select=el('select');select.setAttribute('aria-label',`${this.team===0?'홈':'원정'} ${index+1}번 자리`);for(const p of this.data.players.filter(p=>index===0?p.role==='GK':p.role!=='GK')){const option=el('option',`${p.number} · ${p.name}`);option.value=p.uid;select.append(option);}select.value=uid;select.onchange=()=>{this.snapshot();const lineup=this.data.lineups[this.team],old=lineup.indexOf(select.value);if(old>=0)lineup[old]=uid;lineup[index]=select.value;if(this.persist()){this.renderLineup();this.status('팀 구성을 저장했습니다.');}};row.append(select);list.append(row);});}
 save(){const current=this.data.players.find(p=>p.uid===this.selected),raw={...current,face:structuredClone(this.faceDraft),body:structuredClone(this.bodyDraft)};for(const [key,input]of Object.entries(this.fields)){if(!input.checkValidity()){input.reportValidity();return;}raw[key]=this.readField(key,input);}if(raw.role!==current.role&&((raw.role==='GK')!==(current.role==='GK'))&&this.data.lineups.some(l=>l.includes(current.uid))){this.status('팀에 배치된 선수의 골키퍼 여부를 바꾸려면 먼저 다른 선수로 교체해 주세요.');return;}this.snapshot();Object.assign(current,cleanProfile(raw));if(this.persist()){this.render();this.status('선수 설정을 저장했습니다. 다음 경기부터 적용됩니다.');}}
 add(clone){if(this.data.players.length>=200){this.status('선수는 최대 200명까지 보관할 수 있습니다.');return;}this.snapshot();const p=cleanProfile({...this.data.players.find(p=>p.uid===this.selected),uid:crypto.randomUUID(),name:clone?this.fields.name.value+' COPY':'새 선수'});this.data.players.push(p);this.selected=p.uid;if(this.persist()){this.render();this.status('새 선수를 추가했습니다. 설정을 저장하고 오른쪽 팀에 배치하세요.');}}
 remove(){if(this.data.lineups.some(l=>l.includes(this.selected))){this.status('팀에 배치된 선수입니다. 다른 선수로 교체한 뒤 삭제해 주세요.');return;}this.snapshot();this.data.players=this.data.players.filter(p=>p.uid!==this.selected);this.selected=this.data.players[0].uid;this.persist();this.render();this.status('선수를 삭제했습니다. 되돌리기로 복원할 수 있습니다.');}
 lineups(){return [0,1].map(team=>lineupProfiles(this.data,team).map(p=>({...p,faceTexture:p.face.enabled?this.assets.get(p.face.assetId)?.atlas||null:null})));}
 onlineSquads(squads,team){return squads?.map((lineup,t)=>lineup.map(p=>{if(t!==team)return p;const local=this.data.players.find(q=>q.uid===p.uid),asset=local&&this.assets.get(local.face.assetId);return local?{...p,skin:local.skin,face:local.face,faceTexture:local.face.enabled?asset?.atlas||null:null}:p;}));}
 networkLineup(team,share=false){return lineupProfiles(this.data,team).map(p=>networkFace(p,this.assets.get(p.face.assetId)?.online,share));}
}
