import {FACE_ANCHORS,identityWarp} from './face-identity.js';
import {distantGeometry} from './geometry-lod.js';
import * as THREE from '../vendor/three.module.js';
import {anatomy} from './anatomy-data.js';
import {cleanFace} from './face-settings.js';
const bell=(v,s)=>Math.exp(-((v/s)**2)),clamp=THREE.MathUtils.clamp;
export function sculptPoint(x,y,z,shape){const original=[x,y,z],neckFade=clamp((y+.09)/.06,0,1),f=shape,front=clamp((z+.015)/.075,0,1),jaw=bell(y+.075,.045),nose=bell(x,.022)*bell(y-.012,.039)*front,mouth=bell(y+.045,.018)*front,eye=bell(y-.047,.021)*front;
 x*=f.width*(1+(f.jaw-1)*jaw+(f.cheek-1)*bell(y,.04)*.45);x*=1+(f.noseWidth-1)*nose+(f.mouth-1)*mouth+(f.eyes-1)*eye;
 y*=f.length;y+=(f.chin-1)*Math.min(0,y+.048)+(f.eyeHeight-1)*.10*eye;
 z=z*f.depth+(f.nose-1)*.037*nose+(f.lips-1)*.006*mouth;
 return [x,y,z].map((v,i)=>original[i]+(v-original[i])*neckFade);
}
export function sculptedHeadGeometry(config={}){const f=cleanFace(config),shape=f.shape,warp=identityWarp(f.identity),positions=[];for(let i=0;i<anatomy.head.positions.length;i+=3)positions.push(...sculptPoint(...warp(...anatomy.head.positions.slice(i,i+3)),shape));const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setIndex(anatomy.head.indices);g.computeVertexNormals();return g;}
function mesh(parent,g,m){const o=new THREE.Mesh(g,m);o.castShadow=true;parent.add(o);return o;}
function oval(parent,m,p,s){const o=mesh(parent,new THREE.SphereGeometry(1,24,16),m);o.position.set(...p);o.scale.set(...s);return o;}
function irisMap(seed){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#402e1d';ctx.fillRect(0,0,128,128);for(let i=0;i<180;i++){const a=i*Math.PI/90;ctx.strokeStyle=i%3?'#785c39':'#211a13';ctx.beginPath();ctx.moveTo(64+Math.cos(a)*22,64+Math.sin(a)*22);ctx.lineTo(64+Math.cos(a)*57,64+Math.sin(a)*57);ctx.stroke();}ctx.fillStyle='#030607';ctx.beginPath();ctx.arc(64,64,23,0,7);ctx.fill();const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function hairMesh(parent,config,style,mat){const shape=config.shape,source=sculptedHeadGeometry(config),p=source.attributes.position,n=source.attributes.normal,indices=[];for(let i=0;i<source.index.count;i+=3){const tri=[source.index.getX(i),source.index.getX(i+1),source.index.getX(i+2)];if(tri.every(k=>{const front=clamp((p.getZ(k)+.022)/(.116*shape.depth),0,1);return p.getY(k)>(-.018+.122*front)*shape.length && !(Math.abs(p.getX(k))>.078*shape.width&&p.getY(k)<.055*shape.length);}))indices.push(...tri);}source.setIndex(indices);for(let i=0;i<p.count;i++){const lift=(style==='crop'?.0018:.0035)+(style==='crest'?.009*bell(p.getX(i),.026)*clamp((p.getY(i)-.09)/.06,0,1):0),noise=Math.sin(i*13.7)*.0003;p.setXYZ(i,p.getX(i)+n.getX(i)*(lift+noise),p.getY(i)+n.getY(i)*(lift+noise),p.getZ(i)+n.getZ(i)*(lift+noise));}source.computeVertexNormals();mesh(parent,source,mat);}
export function createSculptedHead(profile={},number=10){const config=cleanFace(profile.face),f=config.shape,warp=identityWarp(config.identity),point=(x,y,z)=>sculptPoint(...warp(x,y,z),f),group=new THREE.Group(),near=new THREE.Group(),far=new THREE.Group();group.add(near,far);far.visible=false;
 const g=sculptedHeadGeometry(config),p=g.attributes.position,skinBase=new THREE.Color(profile.skin||'#c89572'),colors=[],jaw=p.clone(),blink=p.clone(),smile=p.clone();
 for(let i=0;i<p.count;i++){const x=anatomy.head.positions[i*3],y=anatomy.head.positions[i*3+1],z=anatomy.head.positions[i*3+2],px=p.getX(i),py=p.getY(i),pz=p.getZ(i),front=clamp((z-.035)/.035,0,1),lip=bell(y+.033,.008)*bell(x,.029*f.width*f.mouth)*front,cheek=bell(Math.abs(x)-.046*f.width,.02)*bell(y+.008,.025)*front,noseShade=bell(x,.018)*bell(y-.002,.009)*front;const col=skinBase.clone();col.r*=1-.14*lip+.025*cheek-.08*noseShade;col.g*=1-.32*lip-.055*cheek-.11*noseShade;col.b*=1-.18*lip-.035*cheek-.10*noseShade;colors.push(col.r,col.g,col.b);
  const jw=clamp((-.022-y)/.06,0,1)*clamp((z+.05)/.10,0,1);jaw.setY(i,py-jw*.010);jaw.setZ(i,pz-jw*.003);
  const eyeY=.0468,eyeX=.03092,eye=bell(Math.abs(x)-eyeX,.014*f.eyeSize)*front,ey= y-eyeY;if(Math.abs(ey)<.014){const amount=eye*(ey>0?Math.min(.010,ey+.003):-Math.min(.004,-ey));blink.setY(i,py-amount);}
  const corner=bell(Math.abs(x)-.025*f.mouth,.014)*bell(y+.034,.013)*front;smile.setY(i,py+corner*.005);smile.setX(i,px+Math.sign(x)*corner*.003);
 }
 g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));g.morphAttributes.position=[jaw,blink,smile];const skin=new THREE.MeshPhysicalMaterial({vertexColors:true,roughness:.61,clearcoat:.06,clearcoatRoughness:.65}),face=mesh(near,g,skin);face.receiveShadow=true;const lowGeometry=distantGeometry(g,.013),lowColor=lowGeometry.attributes.color,lowPosition=lowGeometry.attributes.position,hairColor=new THREE.Color(profile.hair||'#211a15');if(profile.hairStyle!=='bald')for(let i=0;i<lowPosition.count;i++){const front=clamp((lowPosition.getZ(i)+.022)/(.116*f.depth),0,1);if(lowPosition.getY(i)>(-.018+.122*front)*f.length)lowColor.setXYZ(i,hairColor.r,hairColor.g,hairColor.b);}const low=mesh(far,lowGeometry,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.8}));low.castShadow=false;
 const surfaceZ=(x,y)=>{let z=-1;const a=g.attributes.position,ids=g.index.array;for(let k=0;k<ids.length;k+=3){const i=ids[k],j=ids[k+1],l=ids[k+2],ax=a.getX(i),ay=a.getY(i),bx=a.getX(j),by=a.getY(j),cx=a.getX(l),cy=a.getY(l),den=(by-cy)*(ax-cx)+(cx-bx)*(ay-cy);if(Math.abs(den)<1e-10)continue;const u=((by-cy)*(x-cx)+(cx-bx)*(y-cy))/den,v=((cy-ay)*(x-cx)+(ax-cx)*(y-cy))/den,w=1-u-v;if(u>=0&&v>=0&&w>=0)z=Math.max(z,u*a.getZ(i)+v*a.getZ(j)+w*a.getZ(l));}return z===-1?.09:z;};
 const hair=new THREE.MeshStandardMaterial({color:profile.hair||'#211a15',roughness:.88}),white=new THREE.MeshPhysicalMaterial({color:0xe9e3d7,roughness:.25,clearcoat:.55}),iris=new THREE.MeshPhysicalMaterial({map:irisMap(number),roughness:.22,clearcoat:.65}),eyes=[];
 for(const sign of [-1,1]){const x=sign*.03092,y=.0468,z=.078,eye=new THREE.Group();eye.position.set(...point(x,y,z));near.add(eye);oval(eye,white,[0,0,0],[.014*f.eyeSize,.012*f.eyeSize,.013]);const irisDisk=mesh(eye,new THREE.CircleGeometry(.0055*f.eyeSize,32),iris);irisDisk.position.z=.0132;eyes.push(eye);
  const points=[],ids=sign<0?[107,66,105,63,70]:[336,296,334,293,300];for(const id of ids){const base=FACE_ANCHORS[id],target=config.identity?.points.find(p=>p[0]===id),q=target?sculptPoint(target[1],target[2]-.002+(f.brow-1)*.04,base[2],f):point(base[0],base[1]-.005+(f.brow-1)*.04,base[2]);points.push(new THREE.Vector3(q[0],q[1],surfaceZ(q[0],q[1])+.0015));}mesh(near,new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),18,.0016,6,false),hair);
 }
 const mouth=new THREE.MeshStandardMaterial({color:0x40201b,roughness:.82});const mouthPoint=point(0,-.034,.096);mouthPoint[2]=surfaceZ(mouthPoint[0],mouthPoint[1])-.005;oval(near,mouth,mouthPoint,[.014*f.mouth,.0015,.002]);
 if(profile.hairStyle!=='bald'){hairMesh(near,config,profile.hairStyle,hair);}
 const animate=(time,speed,celebrate,look=0)=>{const phase=(time+number*.31)%4.3,b=clamp(1-Math.abs(phase-4.05)/.085,0,1);face.morphTargetInfluences[0]=celebrate?.65:clamp(speed*.025,0,.2);face.morphTargetInfluences[1]=b;face.morphTargetInfluences[2]=celebrate?.7:0;for(const e of eyes){e.rotation.y=clamp(look,-.2,.2);e.rotation.x=Math.sin(time*.8)*.025;}};
 return {group,near,far,face,eyes:[],animate,ready:Promise.resolve(),dispose:()=>{}};
}
