import {SETPIECE_STYLES} from './setpiece-styles.js';
import {TEAMS,FIELD} from './config.js';
import {clockText} from './rules.js';
const $=id=>document.getElementById(id);
export const show=(id,visible=true)=>$(id).classList.toggle('hidden',!visible);
export class UI{
 constructor(){this.radar=$('radar').getContext('2d');this.toastTime=0;this.eventTime=0;this.debug=false;this.lastUpdate=0;}
 toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(this.toastTime);this.toastTime=setTimeout(()=>$('toast').classList.remove('show'),2700);}
 event(title,small='',detail='',duration=2200){$('event-title').textContent=title;$('event-small').textContent=small;$('event-detail').textContent=detail;show('event');clearTimeout(this.eventTime);this.eventTime=setTimeout(()=>show('event',false),duration);}
 update(match,fps,renderer){$('home-score').textContent=match.score[0];$('away-score').textContent=match.score[1];$('clock').textContent=match.practice?'TRAINING':clockText(match.elapsed||0,match.half,match.settings.halfSeconds);$('period').textContent=match.half===1?'1ST':'2ND';const decision=match.advantage?'ADVANTAGE · 플레이 계속':match.setPiece?`${match.setPiece.label} · ${['free','penalty'].includes(match.setPiece.kind)?'←→ 좌우 / ↑↓ 높이 · D 누르고 놓기 · 조준 '+(match.setPiece.aimZ||0).toFixed(1)+'m / 높이 '+(match.setPiece.aimHeight||.85).toFixed(1)+'m':'S 패스 / A 크로스 / D 슛'}${match.setPiece.kind==='free'?' · 1~7 '+SETPIECE_STYLES[match.setPiece.style||'inside']:''}`:match.addedTime?'추가 시간':'';$('referee-hud').textContent=decision+(match.pressHelpers?.length?`\n협력 수비 ${Math.round(match.pressEnergy*100)}%`:'');const p=match.controlled;document.querySelector("#player-hud small").firstChild.textContent=TEAMS[p.team].name+" ";$('player-name').textContent=p.name;document.querySelector('.player-number').textContent=p.number;$('stamina').style.width=p.stamina*100+'%';$('possession').textContent=p.autoDefending?'자동 수비':match.owner?.team===match.settings.userTeam?'IN POSSESSION':'DEFENDING';show('shot-meter',match.charging);document.querySelector('#shot-meter i').style.width=match.charge*100+'%';$('performance').textContent=this.debug?`${fps} FPS / ${renderer.info.render.calls} DRAW / P95 ${match.frameMetrics?.p95||0}ms\nPHYS ${Number(match.physicsMs||0).toFixed(2)}ms | AI ${Number(match.aiMs||0).toFixed(2)}ms\nBALL ${match.physics.ball.velocity.length().toFixed(1)}m/s · SPIN ${match.physics.ball.angularVelocity.length().toFixed(0)}\nPLANT ${((p.rig?.plantError||0)*100).toFixed(1)}cm · IMPACT ${((p.rig?.impactError||0)*100).toFixed(1)}cm\nINPUT → CONTACT ${Math.round(((match.contacts?.at(-1)?.contactTime||0)-(match.contacts?.at(-1)?.inputTime||0))*1000)}ms\n${match.state} · ${match.owner?.name||'FREE'}\nLAST ${match.lastTouch?.name||'—'} · ${p.aiState}`:'';this.drawRadar(match);}
 drawRadar(match){const c=this.radar,w=288,h=180;c.clearRect(0,0,w,h);const X=x=>12+(x+52.5)/105*264,Y=z=>8+(z+34)/68*164;c.strokeStyle='#c4dcc666';c.lineWidth=1;c.strokeRect(12,8,264,164);c.beginPath();c.moveTo(w/2,8);c.lineTo(w/2,172);c.stroke();c.beginPath();c.ellipse(w/2,h/2,23,22,0,0,7);c.stroke();c.strokeRect(12,41,42,98);c.strokeRect(234,41,42,98);for(const p of match.players){if(!p.active)continue;c.fillStyle=p.team===0?'#c6ff5d':'#ef7965';c.beginPath();c.arc(X(p.x),Y(p.z),p===match.controlled?4.5:2.8,0,7);c.fill();if(p===match.controlled){c.strokeStyle='#fff';c.lineWidth=1.3;c.stroke();}}const b=match.physics.ball.position;c.fillStyle='#fff';c.beginPath();c.arc(X(b.x),Y(b.z),2.5,0,7);c.fill();c.fillStyle='#ffffff88';c.font='9px Arial';c.fillText(match.direction(match.settings.userTeam)>0?'ATTACK →':'← ATTACK',111,178);}
 results(match){show('results');$('result-title').textContent=match.score[match.settings.userTeam]>match.score[1-match.settings.userTeam]?'승리의 순간':match.score[0]===match.score[1]?'끝까지 팽팽했던 승부':'다음 경기를 향해';$('result-score').textContent=match.score.join(' : ');const total=match.stats.possession[0]+match.stats.possession[1]||1;const poss=Math.round(match.stats.possession[0]/total*100);$('statistics').innerHTML=`<div><b>${match.stats.shots[0]}</b><span>슈팅</span><b>${match.stats.shots[1]}</b></div><div><b>${match.stats.passes[0]}</b><span>패스</span><b>${match.stats.passes[1]}</b></div><div><b>${poss}%</b><span>점유율</span><b>${100-poss}%</b></div><div><b>${match.stats.saves[0]}</b><span>선방</span><b>${match.stats.saves[1]}</b></div><div><b>${match.stats.fouls[0]}</b><span>파울</span><b>${match.stats.fouls[1]}</b></div><div><b>${match.stats.yellows?.[0]||0} / ${match.stats.reds?.[0]||0}</b><span>경고 / 퇴장</span><b>${match.stats.yellows?.[1]||0} / ${match.stats.reds?.[1]||0}</b></div>`;}
}
